### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by jessejoe** [jay0lee/got-your-back#10]
Getting this error pretty frequently this week:

```
  File "/mnt/nas/Backups/email/gyb/gyb.py", line 1011, in <module>
    main(sys.argv[1:])
  File "/mnt/nas/Backups/email/gyb/gyb.py", line 594, in main
    for everything_else_string, full_message in (x for x in d if x != ')'):
ValueError: too many values to unpack
```

Pulled most recent version and seeing the same issue:
```
$ python gyb.py --email foo@gmail.com --service-account xxx@developer.gserviceaccount.com --action backup --local-folder /mnt/nas/Backups/email/foo\@gmail.com/

Using backup folder /mnt/nas/Backups/email/foo@gmail.com/
Using folder [Gmail]/All Mail
GYB needs to examine 70637 messages
GYB already has a backup of 70627 messages
GYB needs to backup 10 messages
Traceback (most recent call last):
  File "gyb.py", line 1473, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 830, in main
    for everything_else_string, full_message in (x for x in d if x != ')'):
ValueError: too many values to unpack
```

EDIT to add version:
```
$ python gyb.py --version
Got Your Back 0.28
Jay Lee - jay0lee@gmail.com
Python 2.7.6 64-bit final
Linux-3.8.0-27-generic-x86_64-with-Ubuntu-14.04-trusty x86_64
```

**Comment by 066960992** [comment]
> I'm also getting this error message too:
> 
> GYB needs to refresh 446289 messages refreshed 200000 of 446289 messagesTraceback (most recent call last): File "gyb.py", line 1317, in main(sys.argv[1:]) File "gyb.py", line 789, in main labels = shlex.split(search_results.group(1), posix=False) AttributeError: 'NoneType' object has no attribute 'group'

**Comment by 066960992** [comment]
> I'm also getting this error message too:
> 
> GYB needs to refresh 446289 messages refreshed 200000 of 446289 messagesTraceback (most recent call last): File "gyb.py", line 1317, in main(sys.argv[1:]) File "gyb.py", line 789, in main labels = shlex.split(search_results.group(1), posix=False) AttributeError: 'NoneType' object has no attribute 'group'

![Uploading IMG_0210.jpeg…]()
