### ISSUE TITLE
Exception preventing restore on Linux and Windows

### ISSUE THREAD

**Issue by effnorwood** [jay0lee/got-your-back#101]
Hi,

I am trying to restore to a new .IO domain from and old .COM domain and I have the following issue on both Linux and Windows. My only guess is that it doesn't like .IO because it is only 2 characters and not 3? Thank you!

Linux Ubuntu 16.04
got-your-back-0.45$ python3 gyb.py --email effrem.norwood@newcodomain.io --action restore --local-folder GYB-GMail-Backup-effrem.norwood@oldcodomain.com --label-restored "cmtsent"

Using backup folder GYB-GMail-Backup-effrem.norwood@comedtech.com
Traceback (most recent call last):
  File "gyb.py", line 563, in get_db_settings
    sqlcur.execute('SELECT name, value FROM settings')
sqlite3.OperationalError: no such table: settings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 1503, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 930, in main
    db_settings = get_db_settings(sqlcur)
  File "gyb.py", line 567, in get_db_settings
    if e.message == 'no such table: settings':
AttributeError: 'OperationalError' object has no attribute 'message'

Windows:
gyb.exe --email effrem.norwood@newcodomain.io --action restore --local-folder GYB-GMail-Backup-effrem.norwood@oldcodomain.com --label-restored "cmtsent"

Using backup folder GYB-GMail-Backup-effrem.norwood@comedtech.com
Traceback (most recent call last):
  File "<string>", line 563, in get_db_settings
sqlite3.OperationalError: no such table: settings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1503, in <module>
  File "<string>", line 930, in main
  File "<string>", line 567, in get_db_settings
AttributeError: 'OperationalError' object has no attribute 'message'
gyb returned -1

**Comment by jay0lee** [comment]
The error indicates a corrupt database. Delete the backup folder and re-perform the backup.
