### ISSUE TITLE
Mid-backup: “OSError: [Errno 22] Invalid argument” at gyb.py line 828

### ISSUE THREAD

**Issue by rchesnut** [jay0lee/got-your-back#103]
I’m using the latest (0.47) version of GYB on Windows 7 SP1 (64-bit) with all Windows updates. I’m attempting to do a simple backup, specifying my gmail address on the command line (using --email) and letting all other options default.  I’m using GYB for the first time.  After backing up about 9 GB (220162 messages) of my 14 GB Google Apps for Work mailbox, GYB quits with the below stack trace and messages.  I tried quitting other apps and rerunning it, but it failed with the same messages soon after reporting the number of messages it needs to backup.  I still have plenty enough free disk space for the backup to complete, so that’s not the problem.  Here is the output from the command prompt window:

```
Got 348315 Message IDs
GYB needs to examine 348315 messages
GYB already has a backup of 220162 messages
GYB needs to backup 128153 messages
Traceback (most recent call last):
  File "gyb.py", line 1503, in <module>
  File "gyb.py", line 969, in main
  File "gyb.py", line 460, in callGAPI
  File "oauth2client\util.py", line 135, in positional_wrapper
  File "googleapiclient\http.py", line 1435, in execute
  File "gyb.py", line 828, in backup_message
OSError: [Errno 22] Invalid argument
Failed to execute script gyb
```

I reran with the --debug option.  The output seems to indicate that both of the last couple of requests returned a 200/OK status.  The second-to-last request appears to be a POST containing 100 “GET /gmail/v1/users/me/messages…” requests.  The last request appears to be a “GET /gmail/v1/users/me/labels…” request.  The Reply from that last request was:

```
reply: 'HTTP/1.1 200 OK\r\n'
header: Cache-Control header: Pragma header: Expires header: Date header: ETag header: Vary header: Vary header: Content-Type header: Content-Encoding header: X-Content-Type-Options header: X-Frame-Options header: X-XSS-Protection header: Server header: Alternate-Protocol header: Alt-Svc header: Transfer-Encoding
```

I’m guessing that there must be something about one of my messages or labels that GYB can’t handle.

Expected behavior would be for GYB to handle this situation, or identify the message/label causing the problem (so that I could change or delete it from my mailbox) and ideally skip that message/label and continue with the backup operation.

I'd greatly appreciate a workaround (or a GYB patch that I could try).

Thanks for any help you can provide!

**Comment by tjakober** [comment]
I am using also gyb version 0.47 on a Windows Server 2012R2 installation.
I've got the same error (Error 22) with the following message:
Got 79658 Message IDs
GYB needs to examine 79658 messages
GYB already has a backup of 76502 messages
GYB needs to backup 3156 messages
Traceback (most recent call last):
  File "gyb.py", line 1503, in <module>
  File "gyb.py", line 969, in main
  File "gyb.py", line 460, in callGAPI
  File "oauth2client\util.py", line 135, in positional_wrapper
  File "googleapiclient\http.py", line 1435, in execute
  File "gyb.py", line 840, in backup_message
OSError: [Errno 22] Invalid argument: 'GYB-GMail-Backup-ursula.jones1211@gmail.c
om\\2016\\7\\31\\1564052821d0ecd2.eml'
Failed to execute script gyb

As far as I can see (i am not familiar with phyton) it is an open file statement. But the path is correct, the file does not yet exist and there are two other files in that folder. I tried to execute the script again but it fails at the same place, of course with another filename.

I hope this could help to find the bug. 
Thomas

**Comment by parabex** [comment]
I also have the same issue:

Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
  File "gyb.py", line 1044, in main
  File "gyb.py", line 487, in callGAPI
  File "oauth2client\util.py", line 137, in positional_wrapper
  File "googleapiclient\http.py", line 1435, in execute
  File "gyb.py", line 855, in backup_message
OSError: [Errno 22] Invalid argument
Failed to execute script gyb
