### ISSUE TITLE
Need an option for --noauth_local_webserver

### ISSUE THREAD

**Issue by timothyclemansinsea** [jay0lee/got-your-back#104]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Use a remote machine via SSH
2. Try setting up for first time, get told to use --noauth_local_webserver
3. Try using --noauth_local_webserver and get error

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behavior do you see instead?):

**Comment by jay0lee** [comment]
GYB looks for a file called nobrowser.txt instead of using the command line argument. Just create the file in the same folder as gyb.exe or gyb.py.
