### ISSUE TITLE
HTTPError which backing up large amounts of mail.

### ISSUE THREAD

**Issue by jreeseue** [jay0lee/got-your-back#106]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. python3 gyb.py --email user@gmail.com --action backup

Expected outcome (what are you trying to do?):
Backup of all emails, folders, and labels.

Actual outcome (what errors or bad behavior do you see instead?):
Your browser has been opened to visit:

    https://goo.gl/AC5xLs

If your browser is on a different machine then exit and re-run this
application with the command-line parameter 

  --noauth_local_webserver

Authentication successful.

Using backup folder GYB-GMail-Backup-user@gmail.com
Got 23771 Message IDs                                                           
GYB needs to examine 23771 messages
GYB already has a backup of 0 messages
GYB needs to backup 23771 messages
<HttpError 429 when requesting https://www.googleapis.com/gmail/v1/users/me/messages/14d148c2dcef5344?fields=id%2ClabelIds%2CinternalDate%2Craw&format=raw&alt=json returned "Too many concurrent requests for user">

This is following by loads of the same HTTPError,

**Comment by jay0lee** [comment]
Can you include the actual error message?

**Comment by jay0lee** [comment]
Are you running multiple instances of GYB against one Gmail mailbox or do you have other programs accessing the mailbox at the same time? 429 error indicates you've either hit bandwidth limits (downloaded many GBs of mail in 24 hours) or you are doing concurrent requests against a single mailbox:

https://developers.google.com/gmail/api/v1/reference/quota#bandwidth_limits

**Comment by jreeseue** [comment]
I tried to sync the account last night using the POP3 functionality, but that didn’t work. My mail app is also accessing gmail — don’t think that is doing many requests though. Maybe trying to sync last night is the problem.

Will try again tomorrow to see if the error persists.

josh

**Comment by jreeseue** [comment]
Looks like waiting worked.

**Comment by y24jds** [comment]
Using your program for first time to backup a very large mailbox.  It is going very fast because I'm on a network with a fast connection to the internet but I am getting bursts of logs that say HttpError 429.  I understand its google enforcing some rate limiting (no I'm not running it concurrently, just in my one shell prompt).  But when you get a 429, does your software just try again on the particular message it got the errors on, or will those messages now be missing from the backup file?  So in other words, do you detect the 429, wait, and retry the same message that the error occurred on? Thanks.

**Comment by Vayu** [comment]
It looks like 429 errors are not retried, so better run second backup with --fast-incremental after the first one

**Comment by sensunny** [comment]
Hi i am facing the same issue @droptablestar please tell me how it is worked, what you did for this issue?
I retired after the retry period but shows same message "**retry after xyz date and time**" with increase time period of retry option.

error message:
An error occurred: <HttpError 429 when requesting https://www.googleapis.com/gmail/v1/users/me/messages?q=after%3A2017%2F04%2F04&alt=json returned "User-rate limit exceeded. Retry after 2017-04-05T10:55:14.686Z">

Please help!

Thank You
