### ISSUE TITLE
403: Insufficient Permission - insufficientPermissions

### ISSUE THREAD

**Issue by samuellay** [jay0lee/got-your-back#112]
I confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue. yes
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki yes

Full steps to reproduce the issue:
1. Downloaded gmail emails from corp sponsored acct:
C:\gyb>gyb.exe --email xxx.xxx@xxx.com --action backup
Using backup folder GYB-GMail-Backup-xxx.xxx@xxx.com
Got 2768 Message IDs
GYB needs to examine 2768 messages
GYB already has a backup of 0 messages
GYB needs to backup 2768 messages
backed up 2768 of 2768 messages
GYB needs to refresh 0 messages
2. Attempted to upload to different pesonal acct:
C:\gyb>gyb.exe --email yyyyyyyy@gmail.com --action restore --local-folder c:\gyb\GYB-GMail-Backup-xxx.xxx@xxx.com --label-restored xxxx.xxx@xxx.com

Using backup folder c:\gyb\GYB-GMail-Backup-xxx.xxx@xxx.com

403: Insufficient Permission - insufficientPermissions
3.  I had successfully connected to the second server to backup that mailbox.
The auth pages didn't open on the last attempt to upload

Expected outcome (what are you trying to do?):
Trying to copy email from one acct to another
Actual outcome (what errors or bad behavior do you see instead?):

**Comment by jay0lee** [comment]
You probably only gave backup, not restore permission to the Gmail account. Try deleting the .cfg file for the Gmail account and then run again. This time when you authorize make sure you have restore selected.
