### ISSUE TITLE
backup of a Suspended user account - Temp error backendError.

### ISSUE THREAD

**Issue by daniejstriata** [jay0lee/got-your-back#114]
Using Got Your Back 1.0
http://git.io/gyb
Jay Lee - jay0lee@gmail.com
Python 3.5.1 64-bit final
Linux-4.7.4-200.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four x86_64

Full steps to reproduce the issue:
1.  Disable user from Google Admin console
2. run new backup for existing user:
python3 ./gyb.py --action backup --service-account --email <email address>
3. Start printing of Temp errors:
Using backup folder GYB-GMail-Backup-<email address>
Got 700 Message IDs                                                             
Temp error backendError. Backing off 16 seconds...
attempt 5/10

Temp error backendError. Backing off 32 seconds...attempt 6/10

Temp error backendError. Backing off 60 seconds...attempt 7/10

Temp error backendError. Backing off 60 seconds...attempt 8/10

Temp error backendError. Backing off 60 seconds...

4. adding  --spam-trash --fast-incremental causes the error to happen at 200 Message IDs

5. Expected outcome (what are you trying to do?):
Create a final backup for a user that will be deleted once final backup is completed.
6. Actual outcome (what errors or bad behavior do you see instead?):
After 10 attempts the backup failed
7. This used to work.

**Comment by jay0lee** [comment]
This is working as intended. Google doesn't allow backup of suspended user and there's nothing GYB can do to change that. You'll need to unsuspended before attempting backup.
