### ISSUE TITLE
Google for Work GYB - 403 permission - forbidden

### ISSUE THREAD

**Issue by freddyfa** [jay0lee/got-your-back#116]
Hello,
we are currently using our Google for Work GYB as a backup tool.
This has worked so far perfectly.

However, backups have not been possible for about three weeks and i don't know why.
When I run the following command to start the backup:

**C:\gyb\gyb.exe --email mail@toback.up --action backup --service-account --local-folder C:\My\BackupFolder\MailtoBackup**

I get the following error after about 3 to 8 seconds:

**403: The caller does not have permission - forbidden**

Here the whole issue including my command:

**C:\gyb>C:\gyb\gyb.exe --email mail@toback.up --action backup --service-account --local-folder C:\My\BackupFolder\MailtoBackup

Using backup folder C:\My\BackupFolder\MailtoBackup
Got 2300 Message IDs
403: The caller does not have permission - forbidden

C:\gyb>**

No changes have been made to the service account, the project, or the token. I've updated to the newest Version of GYB (V 1.0)

Thanks in advance for your help!

Greeting,
freddyfa

**Comment by willpolley** [comment]
I have this issue as well. The number of IDs grabbed varies per run. Interestingly, I was able to grab a user with over 15K in emails.
