### ISSUE TITLE
Authentication Successful But With Error Message.

### ISSUE THREAD

**Issue by abby1990** [jay0lee/got-your-back#119]
Your browser has been opened to visit:

    https://goo.gl/fEJhX6

If your browser is on a different machine then press CTRL+C and
create a file called nobrowser.txt in the same folder as GYB.

Authentication successful.
Error: you did not authorize the OAuth token in the browser with the myemail@gmail.com Google Account. Please make sure you are logged in to the correct account when authorizing the token in the browser.

I enter correct password and authentication gets successfull but when i try to initiate backup it gives me this error.

Thanks

**Comment by maphew** [comment]
This happened to me when I had signed in to more than one Google account in the same browser. Switching accounts by signing out of one account and into the next using the google "add account" from top right avatar icon wasn't good enough. 

However after going to accounts.google.com, signing out of all accounts, then starting GYB again I was able to get authentication to work all the way through.

**Comment by paragbaxi** [comment]
+1 even after trying maphew's suggestion
