### ISSUE TITLE
imaplib.error: UID command error: BAD ['Could not parse command']

### ISSUE THREAD

**Issue by litera** [jay0lee/got-your-back#12]
I'm trying to run actions on a subset of all mails by using search criteria. The problem I'm facing is that these labels that I'm including in my search use NON-US characters like Č Š and Ž.

When I try to search mail using such label characters I get the error from the Subject.

I've tried percent/URL encoding but it doesn't help.

**Comment by rlanyi** [comment]
please try if my fix works for you: https://github.com/jay0lee/got-your-back/pull/49/files

**Comment by litera** [comment]
@rlanyi: Thanks for your updated code, but I can't test it as I used this tool as a one off when I had to migrate an account. It's long been migrated so I can't test it any more. But I renamed all my labels to only include standard English characters.
