### ISSUE TITLE
Restore mbox without running a back first fails on sqlite error

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [jay0lee/got-your-back#122]
Hi

Wanted only to use GYB to restore au Google Takeout MBOX file
Running version 1.0 Windows
Authentication was done fine

gyb.exe --email example@gmail.com --action split-mbox --action restore-mbox --local-folder "d:\takeout\"

Using backup folder d:\takeout"
Traceback (most recent call last):
  File "gyb.py", line 1580, in <module>
  File "gyb.py", line 992, in main
sqlite3.OperationalError: unable to open database file
Failed to execute script gyb

I was able to fix the issue by running a backup first, and then launching again the same command (sqlite database didn't exist without running a backup)

**Comment by MpegEVIL** [comment]
Hi,

Having the same issue, except even after running a backup, it still doesn't work. Please advise.

**Comment by pcolton** [comment]
Same issue here:

Traceback (most recent call last):
  File "gyb.py", line 1583, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 995, in main
    detect_types=sqlite3.PARSE_DECLTYPES)
sqlite3.OperationalError: unable to open database file

**Comment by jay0lee** [comment]
this should be fixed in latest releases. Closing.
