### ISSUE TITLE
409: Label name exists or conflicts - aborted error

### ISSUE THREAD

**Issue by JeDay17** [jay0lee/got-your-back#124]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Perform a back up of email address
2. Attempt to restore to new email address for archiving.  Email is shared with multiple backups of other email addresses.  Use '--label restore" to label back up under email name
3. Process for restore begins, then halts with "409: Label name exists or conflicts - aborted"

Expected outcome (what are you trying to do?):
I am trying to restore the backups of employee email domains to a single archive domain. 

Actual outcome (what errors or bad behavior do you see instead?):
The process of back up suddenly halts, either half way or part way with this error even if the intended label is brand new.  This is happening with two different email addresses, and repeats regardless of a new name or label being assigned to the restored files

**Comment by lbenelli** [comment]
Hi, I'm seeing this issue too. 

In one case it's a label with a whitespace at the end (possibly generated via IMAP), in another case it's a simple "sonstiges" (else in german). 

Haven't reached the label limit, under 2000.... 

Anything i can do to help idnetifiying this? 

Thanks Luca

**Comment by JeDay17** [comment]
I was able to find a work around for the problem.  I added initials to all
existing labels in the original email to prevent duplicate labels and
previous emails that were having issues I stripped of their old labels and
created a new overall label designation.  After these adjustments I had had
no problem restoring them to an archive regardless of how many files were
being backed up.

Thanks for touching base


*Jessica Dayley*
Admin Assistant, Canyon State Electric Co., Inc.
602-437-3088 | jdayley@canyonstateelectric.com | www.canyonstateelectric.com
|
4640 E. McDowell Rd, Phoenix, AZ 85008
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=582954008207327>
