### ISSUE TITLE
Bad Linux Executable 1.0?

### ISSUE THREAD

**Issue by nathanieltagg** [jay0lee/got-your-back#127]
I've just downloaded the 'linux' version from the site, after unpacking:

$ tar xvf gyb-1.0-linux-x86_64.tar.xz
gyb/
gyb/client_secrets.json
gyb/gyb
gyb/LICENSE
$ ./gyb
-bash: ./gyb: cannot execute binary file: Exec format error

I'm running ubuntu 16.04.01 LTS.

I tried to run or compile from the source files, but they appear to use python 3.x print() syntax, and so won't run.

**Comment by nneul** [comment]
Assuming you are on a x86_64 (and not 32bit) os install, issue "ldd ./gyb" and see if any dependent libraries are missing.

On my UB 16.04 x86_64 system I see:

```
nneul@infinity:/tmp/gyb$ ldd gyb 
	linux-vdso.so.1 =>  (0x00007ffc931ba000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcbcc8f2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fcbcc6d8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcbcc30e000)
	/lib64/ld-linux-x86-64.so.2 (0x00005645ab849000)

nneul@infinity:/tmp/gyb$ dpkg-query -S /lib/x86_64-linux-gnu/libdl.so.2
libc6:amd64: /lib/x86_64-linux-gnu/libdl.so.2
nneul@infinity:/tmp/gyb$ dpkg-query -S /lib/x86_64-linux-gnu/libz.so.1
zlib1g:amd64: /lib/x86_64-linux-gnu/libz.so.1
nneul@infinity:/tmp/gyb$ dpkg-query -S /lib/x86_64-linux-gnu/libc.so.6
libc6:amd64: /lib/x86_64-linux-gnu/libc.so.6
nneul@infinity:/tmp/gyb$ dpkg-query -S /lib64/ld-linux-x86-64.so.2
libc6:amd64: /lib64/ld-linux-x86-64.so.2

```

If you are on a 32bit system, you'll have to get correct executables or build from source.
