### ISSUE TITLE
Imap support for the restore process // Gmail Failover

### ISSUE THREAD

**Issue by mehdi-belkhayat** [jay0lee/got-your-back#128]
Hi,

thanks for your great work ! it 's life saver.

I experimented a long connection failure with no possible access to my emails and folders due to my provider.

Is it possible to : 
-configure the restore process with IMAP server support ? 
-with fast-incremental option

Then it would be possible with a crowned task to have : 
- all my emails and folders mirrored on an IMAP server o f my choice (remote or local)
- the mirror accessible from any IMAP compatible device (smartphone or PC or even webmail)

Thanks.

**Comment by jay0lee** [comment]
GYB is a backup application, it's not intended for use as a mirroring tool.
