### ISSUE TITLE
ERROR: 400: Bad Request when restoring mailboxes

### ISSUE THREAD

**Issue by wicknet** [jay0lee/got-your-back#132]
First off, Thank you SO much for this wonderful product!

I'm Running latest gyb from source on Ubuntu 16.04.1 with all updates. Using it to transfer/archive mailboxes (244Gb) from a G Suite for Education domain to a secondary G Suite for Education domain via service accounts on both domains.  Backups (>100000 msgs/mailbox) work fine with practically no errors. 

Restoring mailboxes using syntax below:
./gyb --email user1@domain2.org --action restore --service-account --local-folder /root/bin/gyb-domain1/GYB-GMail-Backup-user1@domain1.org

gives almost continuous errors on every mailbox as below:
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (4623/100827)

Would prefer not to use -- fast-restore as we would lose message threading.

There are no internet connectivity issues on the server doing the restore. 

Any suggestions to remedy this issue will be deeply appreciated.

**Comment by wicknet** [comment]
Additional troubleshooting info: 400 Error: Bad Request persists when tried restoring the same mailboxes on a Mac (OSX 10.11.6) using gyb 1.x binary and on Windows. These are 3 different systems, with one even connected directly to a DMZ with external DNS, to obviate the issue of bad DNS entries for resolving external sites.

**Comment by wicknet** [comment]
Finally, tried restoring mailboxes with --fast-restore option. Still gives 400 Error: Bad Request on almost every alternate batch of 10 emails being restored.

ANY help would be appreciated.

**Comment by jay0lee** [comment]
The error indicates that Google's servers don't consider the message a legit message format. You should try opening a few of the failing messages in a text editor and seeing if there's anything strange about them. Feel free to post a few samples here if you can. No timeline guarantees though.

**Comment by mystix** [comment]
I'm seeing "400: Bad request" errors when attempting to restore mbox files created using [Google's own Email Audit API](https://developers.google.com/admin-sdk/email-audit/). Only *some* of the mbox files exported using the Email Audit API experience 400 errors though. I don't think message format is an issue here. Still trying to figure out the root cause though.

**Comment by shaffermonell** [comment]
FWIW, I just encountered this with a restore as well.  ~900 out of 28000 messages reported the same error.  I have examined the text file associated with a number of messages and cannot find anything even remotely suspicious and they don't appear to have anything in common.  One of them contained only a simple email signature (identical in countless other emails from that time) and an attachment.  

The only thing that is slightly interesting is the age of the messages involved.  ~14k of the most recent  messages transferred without error.  Then a few errors cropped up in messages from April of 2014.  As the restore continued, the messages were from earlier dates and as they got older, the frequency of the errors increased.   Once the errors started I saw 0-3 errors per page (~40 messages on my spreadsheet).  Towards the end it was consistently 4-6 per page.   I suppose that could have just been a coincidence though.

**Comment by dmb0058** [comment]
Same problem here with GYB 1.0 on Windows:
400: Invalid label name - invalidArgument

The debug output is:

send: b'{"labelListVisibility": "labelShow", "messageListVisibility": "show", "name": "BIN"}'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Vary header: Vary header: Content-Type header: Content-Encoding header: Date header: Expires header: Cache-Control header: X-Content-Type-Options header: X-Frame-Options header: X-XSS-Protection header: Server header: Alt-Svc header: Transfer-Encoding

**Comment by mikejeep** [comment]
Same issue here. Hundreds of messages throwing the same error, cannot identify a reason why some are having trouble but others are not.

**Comment by jay0lee** [comment]
someone would need to post debug logs and/or failed messages...

**Comment by dmb0058** [comment]
Did that and emailed it too ;)

Chee
Davidrs

**Comment by mikejeep** [comment]
Actually I just did some more testing, and after trying multiple times, it processed all of the messages except for two of them. I can't find the two, but it's better than the few hundred that were previously failing. Perhaps it's on Google's end and it's a temporary problem that occasionally pops up.

**Comment by wcbonner** [comment]
I've received similar messages..  Does GYB keep a log of which messages it had problems with? How do I know which messages it's having a problem with?

Here's a section of my current console:

```
restoring 10 messages (3428/220904)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore

ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (3438/220904)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (3449/220904)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (3460/220904)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore

```

**Comment by shaffermonell** [comment]
@wcbonner, I've done it, but my method is very tedious.  

If you look in the folder associated with the backup, you will find a database named XYZ@gmail.com-restored.sqlite.  It contains a table named restored_messages which is just an index and a list of the message IDs that were successfully restored.  You have to cross reference the missing message_num IDs with the  message table in the msg-db.sqlite database (in the same location) to get the message)filename value.  If you just want to find a couple of examples you can do it with something like the db browser utility at http://sqlitebrowser.org/.

FWIW, as far as I can tell, these errors are caused by actual errors in the format of the message headers and they almost always come from automated systems (e.g. emails from a scheduling system).  Presumably the message envelope was correct, but the headers in the actual message (which is what Gmail stores and GYB backs up) are invalid in some way.  For example, IIRC in one case the messages had two addresses on the from line (again, within the message).

**Comment by wcbonner** [comment]
@shaffermonell Thanks for the information..  Knowing that it keeps track of what has been successfully restored vs not is helpful.

One of the interesting things for me is that if I quit the restore do some other things with my machine, and restart the restore with the exact same command line, it seems to continue for some amount of time without any error messages..  

I was simply hoping that it was being smart about things and will retry messages it had errors with earlier..  I'm attempting to move a mailbox that I've been filling for nearly 20 years to a different account, so it's got lots of messages and lots of labels.

**Comment by wcbonner** [comment]
It's almost like Google starts throttling the connection after several thousand messages were uploaded..   it restored 2097 messages before throwing any errors, then seems to throw errors every batch..   

I'm happy enough starting and restarting every half an hour if it gets the messages transferred in the end.  

```
10:06:47.12 C:\Users\Wim\Downloads\gyb-1.0-windows\gyb>gyb --email xxxx@gmail.com --action restore
label-restored "xxxxx"

Using backup folder GYB-GMail-Backup-xxxx@xxxx.com
restoring 10 messages (2097/216783)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (2127/216783)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (2147/216783)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (2157/216783)

10:41:12.24 C:\Users\Wim\Downloads\gyb-1.0-windows\gyb>
```

**Comment by junhochoi** [comment]
Hi I have same issue here. seems getting 400 all the time after recovering ~19,000 emails (from 228k messages from mbox). Also getting "temp error" sometimes. Anyone have an update?

```ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (45804/228921)
Temp error backendError. Backing off 16 seconds...attempt 5/10```

**Comment by junhochoi** [comment]
Curiously, with `--fast-restore` I don't get 400 bad requests.

**Comment by lobsterkatie** [comment]
> Curiously, with --fast-restore I don't get 400 bad requests.

Same here.

And I'll echo the thanks from the OP - this is a lifesaver! Thanks so much!!

**Comment by tombusby** [comment]
I have a suspicion that we're running up against some sort of rate-limiting at Google's end. If I do it in 1000 message batches, I don't seem to see many of those errors. If I just let it run, I do.

**Comment by dmb0058** [comment]
After a few months with next to zero response I assumed gyb was a dead duck
and just used Thunderbird ... maybe gyb should be allowed to RIP ...

**Comment by wcbonner** [comment]
Are you referring to the Thunderbird desktop email app?

The huge advantage of gyb is that it transfers the labels along with the
messages. I definitely ran into the rate limit issues when I transferred my
mailbox from one account to another, but the way gyb kept track of which
messages had been successfully transferred meant that I could stop the
process and start it again a bit later.

Unless Google rejects the gyb app for some reason, I'll continue to
recommend it over any other method of moving a mailbox.

Wim

**Comment by shaffermonell** [comment]
FWIW, I have recently done a few restores with 20k+ messages and have not run into this problem at all.  I am not using any special settings to rate limit.  For whatever reason though, our connections for this purpose seem to be rather slow (restoring 20k messages takes ~8 hours).

**Comment by nzvorno** [comment]
What is the correct way to use --fast-restore?

Something like?
gyb --email test@gmail.com --fast-restore --local-folder "c:\test@gmail.com"

**Comment by jay0lee** [comment]
Just add the --fast-restore to your existing restore command.

**Comment by nzvorno** [comment]
Jay0lee - firstly, thank you VERY VERY much for this program.

Secondly, got a step closer, thank you.

Now receiving this issue:
`Traceback (most recent call last):
  File "gyb.py", line 2072, in <module>
  File "gyb.py", line 1682, in main
sqlite3.OperationalError: database resume is locked
[12156] Failed to execute script `gyb``

**Comment by nzvorno** [comment]
PS: Happy to donate something as thanks for putting this amazing cmd program together!

**Comment by pavlus007** [comment]
Hi guys. Are that above problems actual on newest GYM? I performed test restore with 1 ERROR 400 while backing 80 messages, and fast-restore helped.
But I have gmail account with 35k messages (11GB) to backup - **what should I do that to minimise problems? Should I pause restoring from time to time? And should I do that?**

I'm also making backup (only inbox) via Thunderbird... but one-time synchronization downloads only 20-50 messages(and while switching offline it download 300-600), so I think **Gmail may be throttling connection**, like someone said before

**Comment by pavlus007** [comment]
@up

any suggestions guys? :)

**Comment by vl-sher** [comment]
I've had 81 of 70000+ restored messages with "ERROR: 400: Request contains an invalid argument". All of them are shown in the original mailbox with "Anti-virus warning" from Google and can not be resent as EML attachment via regular Gmail. So it's normal.
