### ISSUE TITLE
GYB restoring mailbox from scratch

### ISSUE THREAD

**Issue by wicknet** [jay0lee/got-your-back#133]
Running latest gyb on Ubuntu 16.04.1 with all updates. Using it to transfer/archive mailboxes (244Gb) from a G Suite for Education domain to a secondary G Suite for Education domain via service accounts on both domains. 

After backing up restoring 30 mailboxes, transferred the entire backup directory via rsync to another server (with more space) and decommissioned old server.  Then ran backups again on new server and it worked normally, finding anywhere from 2 to 30 new mails per mailbox. However, when restoring those accounts to the domain2, each mailbox is now being restored from scratch (> 100,000 emails) even though there exists in each backup directory a user@domain1.org.restored.sqlite file whose table contains records of all the previously restored emails.

The only change from before is that all directories were transferred to another server running the same OS and under the same creds (root). Apart from loss of time, worried about gyb creating duplicates of 100K emails per mailbox.

**Comment by jay0lee** [comment]
Almost certainly something broke in the rsync process. Not really a GYB issue. However as long as you don't use --fast-restore Gmail should de-dup any messages that have already been migrated.
