### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\xcf' in file gyb on line 1

### ISSUE THREAD

**Issue by amandelman** [jay0lee/got-your-back#134]
Using GYB 1.0 on Mac OS 10.11.6 with Python 3.5.2 installed.

In Terminal, I entered the command:

`python3 gyb --email youremail@gmail.com --action estimate` using my email address. (I did'nt use `gyb.py` as that returned a "No such file" error.)

I received the following error message:

```
File "gyb", line 1
SyntaxError: Non-UTF-8 code starting with '\xcf' in file gyb on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by walkindude** [comment]
+1, I'm experiencing this exact issue as well.

**Comment by ncarota** [comment]
walkindude's solution worked for me.

**Comment by amandelman** [comment]
That worked! Thanks!

**Comment by triguelon** [comment]
Unfortunately it didn't work for me, I'm on MacOS 10.10.3 with Python 3.4.2_1. Anyone else kept on having the issue?

**Comment by tomsitoms** [comment]
@triguelon it's because gyb is an executable not a Python script. just get rid of the "python3" part to get it to work:
`python3 gyb --email youremail@gmail.com --action estimate`

**Comment by carbonsoda** [comment]
@triguelon It's been a while, but have you either updated to MacOS 10.13 to Python 3.6.3? I was having the same issue initially, but @walkindude's response worked like a charm 👍 

The wiki for sure needs to be updated, it doesn't say anything about the "No such file" thing if you keep "gyb.py"
