### ISSUE TITLE
400: Invalid label name - invalidArgument

### ISSUE THREAD

**Issue by borisvereertbrugghen** [jay0lee/got-your-back#135]
I have similar issue as with issue #82 (already closed)
.
running following command with current master:
py gyb.py --email xxx@mydomain.com --action restore-mbox --local-folder "localdir\Takeout\Mail" --debug

Last part of debug output is:

send: b'{"labelListVisibility": "labelShow", "messageListVisibility": "show", "name": "Ongelezen"}'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Vary header: Vary header: Content-Type header: Content-Encoding header: Date header: Expires header: Cache-Control header: X-Content-Type-Options header: X-Frame-Options header: X-XSS-Protection header: Server header: Alt-Svc header: Transfer-Encoding 

The import is not done.

**Comment by borisvereertbrugghen** [comment]
It seems that I have dutch versions of all the reseved labels. and they are not accepted either.
If I add them to the reseved list it works (and stops at next reserved one)

**Comment by barrystaes** [comment]
Same here. Using gyb 1.0 i got this:

```
restoring 10 messages (1227/11389)
ERROR: 400: Invalid label: CHAT. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (2057/11389)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
restoring 10 messages (2077/11389)
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore

.. and errors all the way down
```
But i see `chat` is [already on the reserved list for 1.0](https://github.com/jay0lee/got-your-back/blob/adee034fd47bbcf797397a930725a7b57e5c7c40/gyb.py#L38-L40) .. odd.  

Coincidently about the time i got that error, in Gmail i changed a setting to "Chat Off"..
