### ISSUE TITLE
Not valid Win32

### ISSUE THREAD

**Issue by SorinDobrila** [jay0lee/got-your-back#136]
I confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1.  Followed all steps specified in above GAM Wiki link
2. Run cmd as specified for first use
3. Error message Not valid Win23 application

![image](https://cloud.githubusercontent.com/assets/27282520/24907556/a4c6667c-1eb4-11e7-9971-b384fa973d3d.png)

![image](https://cloud.githubusercontent.com/assets/27282520/24907598/c0790758-1eb4-11e7-8e78-a3201fbb7018.png)

**Comment by jay0lee** [comment]
GYB is 64-bit. You need 64-bit Windows to run it.
