### ISSUE TITLE
GYB Backup and Restore would pause

### ISSUE THREAD

**Issue by Diamondketo** [jay0lee/got-your-back#139]
Ran GYB on Powershell to back up a user email's onto local drive and restore on to a google group. I wish to be able to do this overnight and the issue is that the program would not automate (it would pause in between).

The program would often pause on print:
"backed up 4900 of 15493 messages"

This is not a visual pause because the next morning it will not be finished and I have to click Powershell to have it running again. This occurs during restore as well.

**Comment by cinPlicity** [comment]
private / personal email? ip address or iod proxy? wrking with extendors?

**Comment by Diamondketo** [comment]
1. Organization email
2. ip address
3. No (unsure what that is)

**Comment by jay0lee** [comment]
If powershell is pausing the gyb operation there's not much gyb can do about it.
