### ISSUE TITLE
Invalid argument: BIN

### ISSUE THREAD

**Issue by dmb0058** [jay0lee/got-your-back#140]
I'm running GYB 1.0 on Windows, trying to restore a single .mbx file from Takeout and getting an error 400. The debug output suggests that there's a problem with a label "BIN", but doesn't matter if I use the --spam-trash flag or not.

The output is "400: Invalid label name - invalidArgument" and the restore then aborts.

Any ideas ?

send: b'{"messageListVisibility": "show", "labelListVisibility": "labelShow", "name": "BIN"}'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Vary header: Vary header: Content-Type header: Content-Encoding header: Date header: Expires header: Cache-Control header: X-Content-Type-Options header: X-Frame-Options header: X-XSS-Protection header: Server header: Alt-Svc header: Transfer-Encoding

**Comment by cinPlicity** [comment]
get verified first Before configuring?

**Comment by dmb0058** [comment]
I don't know what you mean but I don't think that's the problem - the error is after 700+ messages have been imported.

**Comment by vinid223** [comment]
I have the same problem, but not any message have been restored and I get this error message. I do have a mbox file of about 800 mb. When I tried to look in the sqlite files to see if there is something that could help, but they are completely empty
