### ISSUE TITLE
Multiple Issues with Restore

### ISSUE THREAD

**Issue by Commocean** [jay0lee/got-your-back#142]
Greetings,

I have a successful backup of the old address, but am unable to restore to the new address, based on the following errors.  Of course, the actual email addresses are used in place of "newaddress" and "oldaddress."  Any help would be most appreciated.  The "oldaddress" account will be terminated on Thursday.

C:\gyb>gyb --email newaddress@gmail.com --action restore --local-folder GYB-GMail-B

ackup-oldaddress

 

Using backup folder GYB-GMail-Backup-oldaddress

Traceback (most recent call last):

  File "gyb.py", line 589, in get_db_settings

sqlite3.OperationalError: no such table: settings

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "gyb.py", line 1580, in <module>

  File "gyb.py", line 997, in main

  File "gyb.py", line 593, in get_db_settings

AttributeError: 'OperationalError' object has no attribute 'message'

Failed to execute script gyb

**Comment by minimalart** [comment]
I'm having the same issue, with MacOS Sierra (I had to chmod+x gyb as explained in https://github.com/jay0lee/got-your-back/issues/134 in order to backup first)

**Comment by kirkegaard** [comment]
did anyone find a solution to this problem?

**Comment by scirocco-github** [comment]
I am having this problem now, using 1.11  in Windows 10 Pro.

It's a very large mbox (56 gb), which I understand would be a problem for GYB 1.1 but has been improved for the recent update.

Here's the consistent results I get:

 C:\Users\xxx\Dropbox (Personal)\Apps\Oct 2018 All Mail>dir
 Volume in drive C is TI10687400D
 Volume Serial Number is DCB8-3993

 Directory of C:\Users\xxx\Dropbox (Personal)\Apps\Oct 2018 All Mail

11/12/2018  11:51 AM    <DIR>          .
11/12/2018  11:51 AM    <DIR>          ..
11/12/2018  11:47 AM             3,327 xxx@gmail.com.cfg
12/29/2017  12:17 PM    56,788,460,469 All mail Including Spam and Trash-007.mbox
11/06/2018  02:25 PM         2,895,871 All mail Including Spam and Trash-007.mbox.mboxview
11/12/2018  11:48 AM    <DIR>          GYB-GMail-Backup-xxx@gmail.com
11/12/2018  11:46 AM                10 lastcheck.txt
11/12/2018  11:51 AM                 0 msg-db.sqlite
               5 File(s) 56,791,359,677 bytes
               3 Dir(s)  43,222,884,352 bytes free

C:\Users\xxx\Dropbox (Personal)\Apps\Oct 2018 All Mail>gyb --email xxx@gmail.com --action restore-mbox --local-folder "C:\Users\xxx\Dropbox (Personal)\Apps\Oct 2018 All Mail" --label-restored "XXX Archive"

Using backup folder C:\Users\xxx\Dropbox (Personal)\Apps\Oct 2018 All Mail
Traceback (most recent call last):
  File "gyb.py", line 874, in get_db_settings
sqlite3.OperationalError: no such table: settings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 1875, in <module>
  File "gyb.py", line 1254, in main
  File "gyb.py", line 878, in get_db_settings
AttributeError: 'OperationalError' object has no attribute 'message'
[15644] Failed to execute script gyb

C:\Users\xxx\Dropbox (Personal)\Apps\Oct 2018 All Mail>

**Comment by scirocco-github** [comment]
Nevermind, this was answered long ago, it's a corrupt database file.

Delete or rename the database file.

[https://github.com/jay0lee/got-your-back/issues/101#issuecomment-222167776](url)
