### ISSUE TITLE
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore

### ISSUE THREAD

**Issue by Ron0x99** [jay0lee/got-your-back#143]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
Confirmed
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki
Confirmed

Expected outcome (what are you trying to do?):
Trying to restore a mailbox from one account to the other.

Actual outcome (what errors or bad behavior do you see instead?):
At first everything is fine. But after a while I receive the following error:
ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore

**Comment by jay0lee** [comment]
This is not a gyb error. Google's servers rejected the message and restore will continue on the next message. GYB is instructing you that you may be able to retry with --fast-restore to get the message into Gmail.
