### ISSUE TITLE
Ability To Nest Labels for Archiving

### ISSUE THREAD

**Issue by MrCaspan** [jay0lee/got-your-back#146]
I love your tool for archiving a user at work. The user leaves we back up their account using GYB and then we restore to an archive user. Problem I have is that I have to do a restore with a custom label then move all their labels under a parent label so that they stay containerized IE User A has a label called Client A when restored it goes to label User A > Client A. This would help a lot for archiving users and keeping their email under a single label but still the same hierarchy as their mailbox. Is there any way to do this?

**Comment by MrCaspan** [comment]
ohh maybe i need to archive all the users email first to a label in their mailbox then backup that mailbox then restore? Would that be a better way? that is still more work for me and would love to have the option of creating a parent label that all email goes under when restored!

**Comment by virtualvlad** [comment]
You could do it at the source mailbox as you suggested, by nesting all of the labels under one master label.

GMail's native import tool (GMail -> Settings -> Accounts and Import -> Import mail and contacts) also does this, putting all of the labels under one label, "source_email@website.com", which you could rename afterwards.

**Comment by MrCaspan** [comment]
I just ended up using Gmail migration tool in Admin Tools and migrating their content to another mail box and arching the email there. It retains all the emails and labels

**Comment by kitgillingham** [comment]
Hi guys, is there any way to backup sub-labels? eg I have a label called Offices that has 5 messages in it but also 4 sub-labels that also contain messages. Can these sub-labels be backed up and maintained?

**Comment by Turok21** [comment]
Hi,

I trying to update GYB to adding a NEST Label (parent label) on --action restore

Step 1 :  Adding one parser option : 
```
parser.add_argument('--label-prefix',
                        action='append',
                        dest='label_prefix',
                        help='Optional: On restore, all labels will additionally receive \
  this prefix label. For example, "--label-prefix gyb-archive" will become main label of all \
  uploaded labels with a gyb-prefix label.',
                        default=[])
```

Step 2 : Adding Nest label to the request if it's input by the user 
```
[..................]
 if not options.strip_labels:
           sqlcur.execute('SELECT DISTINCT label FROM labels WHERE message_num = ?', (message_num,))
           labels_results = sqlcur.fetchall()
           for l in labels_results:
                      # TODO TUROK LABEL PREFIX BEGIN
                      if options.label_prefix:
                                 labels.append(options.label_prefix[0] + "/" + l[0])
                      else:
                      # TODO TUROK LABEL PREFIX END
                                 labels.append(l[0])
if options.label_restored:
[..................]
```

Result on destination Mail is "correct" about gMail categorisation 
Label are well placed under one parent label
Email are all categorized on the good destination nested label

==> But email are all marked as "Read" even if they were unread on the source

I don't see any trace of on the main.py app, Where please does this is set to "read"/"unread"

There is this information stored and updated?
Thanks =)
