### ISSUE TITLE
Error 400: "Expected a single 'From' header" when trying to migrate from Google apps to Gmail

### ISSUE THREAD

**Issue by talldonkey** [jay0lee/got-your-back#147]
I am trying to migrate from google apps to gmail.  There is about 93K messages, the vast majority of which I think worked.  Multiple runs of GYB got me to this poing:

- first run had multiple 400 Single From Header error messages, along with Error 400 Bad requests.
- Second run (5.3K messages left) whittled this down to 179
- Third run brought it down to 166, and no longer encountered Error 400 Bad request messages.  
- Fourth and ongoing has 166 messages with the "Expected a single 'From' header" problem.

I notice this also happens on 'large message restores' which seems to rule out chats, and I understand chats are no longer backed up by gyb.

I'm running GYB 1.0.0 on windows.

Running in --debug mode did not allow me much insight.

I'm also not sure how to identify the 166 messages that are failing so I can inspect them for any weirdness.

I was an occasional user of the 'send email as' feature in gmail, if its relevant any way.

Happy to grab any logs that would be helpful.

Thanks!
Daniel

**Comment by calebfavor** [comment]
I am getting the same issue. It would be nice if it just stripped out all the from headers except the first one.

**Comment by acidnine** [comment]
I am getting this as well (importing to g suite from a massive custom export), if it would give any file/message information I could at least go correct the emails and re-upload.

**Comment by maxgit2** [comment]
GYB create 2 sql lite database, one for the backed up messages, and one for the restored messages.
If you open and query those databases you could check the list of the messages that weren't restored.

Let's say that you use SQLiteStudio,
Attach the backup DB as 'bck', and the restore DB as 'rst'.
Then you can run an SQL like this:

```
select b.*, r.message_num, l.label

from bck.messages b left join rst.restored_messages r  on b.message_num = r.message_num left join bck.labels l on b.message_num = l.message_num

where r.message_num is null and l.label<>'CHAT'
```

to get the list of the message not present in the restore DB.

![test restore email](https://user-images.githubusercontent.com/35954615/49207930-a903dc00-f3b6-11e8-9ffb-8b9b2993d9bf.png)

This didn't help me much, the few messages (not restored) which I checked revealed to be some chat messages (even if I excluded the message labelled CHAT in die query) and some pretty normal email (maybe the header had something wrong... but no multiple from)

**Comment by lrhazi** [comment]
Thanks for the SQL @maxgit2 
In my case, it seems the messages that failed with the error about the From header actually had From header missing! They did not have one!
