### ISSUE TITLE
Character encoding is not correctly restored to Group

### ISSUE THREAD

**Issue by infovations** [jay0lee/got-your-back#148]
Full steps to reproduce the issue:
1. Backup emails from GMail account: ./gyb --email <my_email@gmail.com> --local-folder "/my/local/folder/" --search "after:2013/12/31 before:2015/01/01 smaller:16M"
2. Restore to Google group in GSuite: ./gyb --email <group_account@mydomain.tld> --service-account --use-admin <my_admin_account@mydomain.tld> --action restore-group --local-folder "/my/local/folder/"
3. Special characters (e.g. ä, ö, ü) in e-mails that had been sent to GMail with the following encoding will appear scrambled in the restored mails:

Content-Type: text/plain; charset=iso-8859-15
Content-Transfer-Encoding: 8bit

Expected outcome:
Special characters should be displayed in the same way as in the original message as seen in the GMail account.

Actual outcome (what errors or bad behavior do you see instead?):
ä is displayed as ï¿œ
ö is also displayed as ï¿œ
ü is also displayed as ï¿œ

**Comment by jay0lee** [comment]
Can you attach a sample message file that has this issue?

**Comment by infovations** [comment]
The e-mails all contain confidential information and our business 
identities, so I can unfortunately not share any original e-mails.
