### ISSUE TITLE
How to backup/restore gmail messages with mixed English and non-English characters

### ISSUE THREAD

**Issue by SheldonBlu** [jay0lee/got-your-back#157]
I ran a selective gyb backup and restore to a different gmail account.  The backup was from a label with 3 emails, each with between 9 and 29 messages
1) I noticed that the backed up files on my Windows 10 machine encoded the non-English (in this case Hebrew) characters with symbols like =EE =EB =E9  etc.
2) Only 2 of the 3 emails was restored.  I presume that the non-English characters messed up the restore.
3) The 2 restores were messed up.  Messages were missing from each of the 2 restored emails and the message order was not as the original.

Is there  a language/encoding parameter to gyb backup or restore?

**Comment by jay0lee** [comment]
can you provide sample messages that cause this issue? The raw file or a backup would be fine.
