### ISSUE TITLE
version `ZLIB_1.2.9' not found 

### ISSUE THREAD

**Issue by laakkus** [jay0lee/got-your-back#162]
Trying to use gyb for the first time using gyb --email username@gmail.com --estimate

**Actual outcome **

mkdir: symbol lookup error: mkdir: undefined symbol: mode_to_security_class
/usr/bin/google-chrome-stable: /tmp/_MEIlmrI05/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
/usr/bin/google-chrome-stable: /tmp/_MEIlmrI05/libz.so.1: version `ZLIB_1.2.3.4' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
mkdir: symbol lookup error: mkdir: undefined symbol: mode_to_security_class
/usr/bin/x-www-browser: /tmp/_MEIlmrI05/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
/usr/bin/x-www-browser: /tmp/_MEIlmrI05/libz.so.1: version `ZLIB_1.2.3.4' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
XPCOMGlueLoad error for file /usr/lib/firefox/libmozgtk.so:
/tmp/_MEIlmrI05/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
Couldn't load XPCOM.
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: chromium-browser: not found
mkdir: symbol lookup error: mkdir: undefined symbol: mode_to_security_class
/usr/bin/google-chrome: /tmp/_MEIlmrI05/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
/usr/bin/google-chrome: /tmp/_MEIlmrI05/libz.so.1: version `ZLIB_1.2.3.4' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: w3m: not found

removed the https links from output above

**Comment by laakkus** [comment]
Lubuntu 17.10

Where does gyb copy libz.so.1 from? Ubuntu 17.10 seems to have problems with that lib.
Tried this workaround from [Ubuntu forums](https://ubuntuforums.org/showthread.php?t=2375927#3) 
with no luck.

**Comment by jay0lee** [comment]
this is an issue with your Python installation, not GYB.
