### ISSUE TITLE
python3: can't open file 'gyb.py': [Errno 2] 

### ISSUE THREAD

**Issue by SimonMuraya** [jay0lee/got-your-back#164]
Hi,

Am having the below error as indicated in the subject. After running

`python3 gyb.py --email simon.muraya@********.com --action estimate`

Kindly assist.

**Comment by sylvan-d-ash** [comment]
Where are you running the above command from? You need to run it in the same folder where you installed the `gyb.py`

**Comment by SimonMuraya** [comment]
@danielar-hyuna write this command in your terminal from the parent directory.

`gyb/gyb --email abc@mail.com --action estimate`

**Comment by sylvan-d-ash** [comment]
In the terminal, make sure you're in the directory where `gyb.py` is. That is, you should be in the `gyb` folder, and if you were to run `ls`, you'd see `gyb.py` among the items there.

If you're not in the `gyb` folder, the best option would be to change directory into it (using `cd` command).

**Comment by danielar-hyuna** [comment]
Hi guys

Yes I am in the correct directory where I downloaded the package. I just run the --backup command without performing the action estimate command and it worked. 

Thanks @SimonMuraya and @sylvan-d-ash

**Comment by jay0lee** [comment]
This is an issue with basic command line issue, not gyb. Closing.
