### ISSUE TITLE
Error during mbox restore - AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by BradGraham** [jay0lee/got-your-back#17]
During an mbox restore, I get these messages frequently.  If I wait a few hours, the issue seems to go away by itself, but returns after a few dozen more messages are restored.  Any ideas?

I'm using:

Got Your Back 0.29
Jay Lee - jay0lee@gmail.com
Python 2.7.8 64-bit final
Windows-2008ServerR2-6.1.7601-SP1 AMD64

Restoring from h:\quinnj_emails_with_specific_terms_hammackw@recoverydomain.com_0.mbox
 message 1 of 175Traceback (most recent call last):
  File "gyb.py", line 1323, in <module>
  File "gyb.py", line 1033, in main
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by daanodinot** [comment]
Hi Jay, I really love your tool, but unfortunately I receive (almost) the same error:

 message 2423 of 3338Traceback (most recent call last):
  File "<string>", line 1333, in <module>
  File "<string>", line 1036, in main
AttributeError: 'NoneType' object has no attribute 'group'

I've already shared the problematic mbox file via Google Drive.
Thanks in advance.

**Comment by daanodinot** [comment]
Alright, I tried it again today and it worked! So problem 'solved' then.
