### ISSUE TITLE
Import continues even after process terminated, emails added to Inbox

### ISSUE THREAD

**Issue by leithyn** [jay0lee/got-your-back#172]
I used GYB to backup work emails and import into personal email account. It seemed to work fine, the process completed, all was good in the world. 
A week or so later, out of nowhere, I started to get 2000 emails a day added to my inbox. These 2000 emails were mostly Sent emails or All Mail emails, and were newly added each day to my Inbox (they were incremental as the All Mail total incremented by 2000 each day as well).
It is going systematically and chronologically backwards, and adds 2000 emails (1000 at around 11pm GMT, 1000 around 8am GMT0 every day, into my Inbox.
I've also noted the GYB application files on my computer have a Date Modified date of this week, even though the import completed via the Terminal window weeks ago.
And emails from Sent and All Mail keep being imported from the backed up email. What is crazy is I've also deleted the backed up file, cleared my Trash... and the import continues regardless, every day.
Please help me... I want this process to stop. I've changed my passwords, I've done everything, but seems the process is continuing regardless. Surely this can be stopped somehow?

**Comment by leithyn** [comment]
Today I tried resetting passwords from the original Gmail account and the destination Gmail account. at 10:45pm, right on schedule, another 1000 emails from 2012 flooded my inbox. Again. 
Please - can someone tell me how to stop this process?

**Comment by jay0lee** [comment]
GYB cannot do this. Once the process is terminated it's not running, it can't still import mail. Closing this issue.
