### ISSUE TITLE
TypeError: Got an unexpected keyboard argument "maxItems" Failed to execute script gyb

### ISSUE THREAD

**Issue by funksake** [jay0lee/got-your-back#174]
Getting the above after granting authorisation

**Comment by funksake** [comment]
Backup and restore still works fine regardless

**Comment by SGayner** [comment]
Just installed today. Version 1.01. Same issue for me. But --estimate does not work. Will try a backup, but this does not give me confidence in the process.

**Comment by leezimm** [comment]
I am seeing the same error when trying to use the --action estimate flag. I switched back version 1.0 for  now.

**Comment by jay0lee** [comment]
Fixed in 1.1

https://git.io/gyb-releases
