### ISSUE TITLE
sqlite3.OperationalError: database resume is locked

### ISSUE THREAD

**Issue by GBakshi** [jay0lee/got-your-back#179]
Trying to run this command to restore the backup to a new account using service account.

gyb --email newemailaddress@xxxx.edu --service-account --action restore --local-folder GYB-Gmail-Backup-oldemailaddress@xxxxx.edu --label-restored "OLDADDRESS"

Failed with the following output:

Using backup folder GYB-Gmail-Backup-oldemailaddress@xxxx.edu

Traceback (most recent call last):
  File "gyb.py", line 1583, in <module>
  File "gyb.py", line 1210, in main
sqlite3.OperationalError: database resume is locked
[3028] Failed to execute script gyb

Please help !

**Comment by GBakshi** [comment]
I deleted the old backup.
Started a new backup and ran the same command without any issues.

Thanks,
GB

**Comment by astreeter** [comment]
I came across the same issue and used the --noresume flag on the next run. It starts over but the lock is gone.

**Comment by Don-Dossa** [comment]
I got the database locked error when I restarted a restore.  There are about 300 of 17,000 messages left to restore. I don't want to start the 8 hour import again and have to worry that everything will end up being duplicated.
Is there a simple way to clear the DB lock?

**Comment by luctus** [comment]
+1

**Comment by Revulse** [comment]
Using gyb v1.11

I was able to successfully restore from my backup that I had created using gyb. But after restoring, I wanted to test and make sure that it would not import duplicates by running the same command again.

When attempting to run this command again, I got the same error
"sqlite3.OperationalError: database resume is locked"


Command ran:
"gyb.exe --email email@mail.com --action restore --local-folder "D:\email""

**Comment by maxgit2** [comment]
My experience is that after a backup, you can run a restore.
After the restore, if you run the same restore command, you'll get the "database resume is locked" error.
But then, if you run the  backup again, and IF the backup download some new messages, then you will be able to run the restore again without getting the error.
Only the new messages will be restored.

Another possibility is that when you get the "database resume is locked" error, you run the restore with the --noresume option.
This way, you wont get the error.
During my test with --noresume option, the restore tried to restore all the emails.
All the message was already existing on the destination account: I didn't get any duplicates.

If you use both the --noresume AND --fast-restore options, then YOU WILL get duplicated messages.

I made those test on a small account, just about 400 emails to understand how backup/restore works.
