### ISSUE TITLE
Cloud to cloud import mbox file data into archive gmail account

### ISSUE THREAD

**Issue by rajasegrove** [jay0lee/got-your-back#181]
Is there any possibility to use the mbox folder directly from the cloud (google drive - zip file format), without downloading the file into the local system, for the restore process?

**Comment by jay0lee** [comment]
Can you clarify what you mean? What do you want to see happen?

Assuming you can map the cloud mbox file to a local drive / folder then in
theory it would work....

Jay

**Comment by rajasegrove** [comment]
In that case, the mbox file will be in .zip format, Is GYB is support for Zip file also?

**Comment by rajasegrove** [comment]
I need the system to be able to go from cloud to cloud. So I want it to be on a simple web interface, then I point to where the file is in Google Drive and then it get's processed without having to download it. I need to do about 50+ of these and if I need to download every file it will be painful (some of the files can be 10-20Gb!
Also, I'd like it to be a utility that has a simple web interface - not an installable file on my computer.

**Comment by rajasegrove** [comment]
Is there any possible ways?

**Comment by priyaruby86** [comment]
Read this blog, It is very helpful for me that import all emails from .mbox to my gmail account: [https://tech-vita.blogspot.com/2018/12/how-to-import-mbox-to-gmail.html](https://tech-vita.blogspot.com/2018/12/how-to-import-mbox-to-gmail.html)

**Comment by jay0lee** [comment]
GYB is by design a command line tool. It doesn't care where it runs. You could run it in the cloud to prevent local network Internet usage, up to you.
