### ISSUE TITLE
gyb generates Syntax Error

### ISSUE THREAD

**Issue by epsteins** [jay0lee/got-your-back#183]
Running on Fedora 28

python3 is at level 3.6.5

Downloaded and extracted gyb 1.11

I get the following:

$ python3 gyb --email epsteins@gmail.com --action estimate
  File "gyb", line 1
SyntaxError: Non-UTF-8 code starting with '\xe8' in file gyb on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Any ideas? Many thanks.

**Comment by jay0lee** [comment]
You downloaded the binary file. You  shouldn't include python as part of
the command.

Jay
