### ISSUE TITLE
Label changes in original account are not reflected in restored account

### ISSUE THREAD

**Issue by maltokyo** [jay0lee/got-your-back#190]
Full steps to reproduce the issue:
1. Run commands in this order:
python3 /root/got-your-back/got-your-back/gyb.py --email email1@company.com --action backup
python3 /root/got-your-back/got-your-back/gyb.py --email email2@company.com --action restore --local-folder GYB-GMail-Backup-email1@company.com --label-restored "gyb-backup-email1@company.com"
2. Change some labels in email1@company.com account online in Gmail
3. Run step 1. again

Expected outcome (what are you trying to do?):  I would expect that the changed labels in step 2. above in email1@company.com get also changed/refreshed in email2@company.com upon the restore

Actual outcome (what errors or bad behavior do you see instead?):  Only brand new messages get restored in email2@company.com and the changes in labels of old messages do not get refreshed.

Anyway to do a FULL refresh of all labels, even for old emails where the label may have been changed?

**Comment by maltokyo** [comment]
Any possible fix for this one, just wondering.  Thank you, I like the project a lot.

**Comment by hirenshah** [comment]
Came across this as I am looking for the same thing.  The alternative method I can think of is to purge everything in the new account and then restore from scratch, but that would take absolutely ages.

**Comment by maltokyo** [comment]
I can’t really use the alternative method anymore as many emails in the backup account are not in the original account anymore.... still looking for some way to go forward here

**Comment by jay0lee** [comment]
What you are describing here is more of a "sync" between Gmail accounts rather than a backup and it's not something GYB is likely to do anytime soon.

**Comment by maltokyo** [comment]
> What you are describing here is more of a "sync" between Gmail accounts rather than a backup and it's not something GYB is likely to do anytime soon.

It is a backup, then a restore (to another gmail account), using two separate commands.  So does label backup not work, in this case?

**Comment by maltokyo** [comment]
bump
