### ISSUE TITLE
Fails to restore from mbox

### ISSUE THREAD

**Issue by ilium007** [jay0lee/got-your-back#191]
Attempted to restore an mbox that was exported from Apple mail on OSX 10.14.1.

`$ ./gyb --email trevorxxxxx@gmail.com --action restore-mbox --local-folder /Users/xxxxxxx/Downloads/xxxxxx\ Archive/ --label-restored temp`

It immediately returns:

```
Using backup folder /Users/xxxxx/Downloads/xxxx Archive/

done!
```

Nothing is restored to GMail

**Comment by headlands** [comment]
I'm having the same issue.  In my case, I thought it was due to having copied .mbox folder from under ~/Library/Mail/ rather than using the Export function.  OS X treats the mbox package as a folder rather than a file, and I was assuming GYB ignored it for that reason?

**Comment by chrisndeca** [comment]
Having this same issue. Nothing is being transfered. Any help or suggestions would be appreciated!

**Comment by krauth** [comment]
Oohh... I was hoping it was my fault, still possible if we both do the same
stupid thing... :-)

Maybe you can try the following as well - to confirm my findings:

I did a restore of the exact same backup and with the same command (I used
previously) but this time to my own account, data got pushed there, but not
only >20M and doing multiple of those in parallel, with different labels,
gets the labels multi assigned...

So, when restoring to my own account, with own credentials (which actually
are super admin credentials - don't know, this might be important...) and
multiple restores at the same time with different labels the outcome is:

labels do get created
restore works (didn't check if it is complete though) but doesn't adhere to
the >20M search
get restored with all labels attached to all restored emails

GYB is a great tool, full support from me. Let me know if I can help more
with testing etc!


cu
Franz

**Comment by Adam0111** [comment]
Hey,
It would be very helpful to make a youtube video on how to restore a .mbox file (GoogleTakeOut file).
