### ISSUE TITLE
RESTORE starting, but NOT Completing Job

### ISSUE THREAD

**Issue by u2rcrazy** [jay0lee/got-your-back#192]
**EXPLANATION**
I am able to Download, Install, Estimate, and BACKUP from my OLD ADDRESS.  When I RESTORE to my NEW ADDRESS, it doesn't complete.  Below is what the screen says during the RESTORE process.  The OLD ADDRESS has 15.43 GB (102%) of 15 GB used in that Gmail account and all, but .4 GB is used for email.  I'm not a programmer, just the average user.

**MY QUESTIONS:**
- How can I get GYB to finish RESTORING to the NEW ADDRESS?
- If I BACKED UP too many times withing a day, I would get an error message that said I went over some limit.  Similarly, is there some limit when restoring?  
- If there is a Data Transfer or another limit, how can I break up the my Gmail email data into segments and transfer them over time?

Thanks everyone for your assistance:)!

**Below is what the CMD screen says during the RESTORE process.**  
> Select the actions you wish GYB to be able to perform for OLDADDRESS@gmail.com
> 
> [ ]  0)  Gmail Backup And Restore - read/write mailbox access
> [ ]  1)  Gmail Backup Only - read-only mailbox access
> [*]  2)  Gmail Restore Only - write-only mailbox access and label management
> [ ]  3)  Gmail Full Access - read/write mailbox access and message purge
> [ ]  4)  No Gmail Access
> 
> [*]  5)  Groups Restore - write to G Suite Groups Archive
> [*]  6)  Storage Quota - Drive app config scope used for --action quota
> 
>       7)  Continue
> 7
> 
> Your browser has been opened to visit:
> 
>     https://accounts.google.com/o/oauth2/auth?client_id=xxxxx.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.insert+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.labels+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fapps.groups.migration+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&login_hint=thechristianjsalmon%40gmail.com&access_type=offline&response_type=code
> 
> If your browser is on a different machine then press CTRL+C and
> create a file called nobrowser.txt in the same folder as GYB.
> 
> Authentication successful.
> 
> Using backup folder GYB-GMail-Backup-OLDADDRESS@gmail.com
> restoring 5 messages (3624/61231)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> 
> Temp error backendError. Backing off 32 seconds...attempt 6/10
> 
> Temp error backendError. Backing off 60 seconds...attempt 7/10
> 
> Temp error backendError. Backing off 60 seconds...attempt 8/10
> restoring 1.11mb message (4488/61231)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> restoring 5 messages (7240/61231)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> 
> Temp error backendError. Backing off 32 seconds...attempt 6/10
> 
> Temp error backendError. Backing off 60 seconds...attempt 7/10
> restoring 5 messages (13640/61231)
> ERROR: 400: Bad Request. Skipping message restore, you can retry later with --fast-restore
> restoring 5 messages (18332/61231)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> 
> Temp error backendError. Backing off 32 seconds...attempt 6/10
> restoring 5 messages (18899/61231)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> 
> Temp error backendError. Backing off 32 seconds...attempt 6/10
> restoring 5 messages (19379/61231)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> 
> Temp error backendError. Backing off 32 seconds...attempt 6/10
> 
> Temp error backendError. Backing off 60 seconds...attempt 7/10
> restoring 5 messages (26424/61231)
> 400: Invalid label name - invalidArgument

**Here's where I tried it again this morning:**
> C:\Users\CS - HP Envy\Desktop\gyb3 - Copy\gyb>gyb --email NEWADDRESS@gmail.com --action restore --local-folder GYB-GMail-Backup-OLDADDRESS@gmail.com
> 
> Using backup folder GYB-GMail-Backup-OLDADDRESS@gmail.com
> 
> 400: Invalid label name - invalidArgument
> 
> C:\Users\CS - HP Envy\Desktop\gyb3 - Copy\gyb>

**Comment by ralph** [comment]
I had better success when decreasing the batch size with the `--batch-size 5` parameter. It might take longer b/c of less parallel requests, with a batch size of 5 I was able to complete the process without errors. So I guess Google is rate limiting the upload requests and causing errors when you exceed the limits.
