### ISSUE TITLE
no workaround for initial Google signin

### ISSUE THREAD

**Issue by Time-Saving** [jay0lee/got-your-back#194]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Follow the steps for an initial setup and sign in to your Google account using the Wiki and https://github.com/jay0lee/got-your-back/issues/134
2.
3.

Expected outcome (what are you trying to do?):  Initial setup by logging into Google and allowing it to link to GYB.  (I've done this successfully in the past with another account.)

Actual outcome (what errors or bad behavior do you see instead?):  "Sign in with Google temporarily disabled for this app.  This app has not been verified yet by Google in order to use Google Sign In."
![gyb](https://user-images.githubusercontent.com/48172394/53692276-a6ac7780-3d41-11e9-99cc-64d1f86d5651.jpeg) .  I also see other users having trouble as reported in the Google forum.

**Comment by johanburatti** [comment]
I have also heard reports about this problem. Specifically when trying to restore emails. Does gyb ask for any additional scopes that would trigger this?

**Comment by scirocco-github** [comment]
I am here because I am experiencing this same issue.

OSX version 1.11 and 1.1

This error occurs with any attempt to authenticate, with an action or not.  

./gyb --email email@gmail.com

**Comment by davebalzotti** [comment]
Same issue. It looks like the app will need to be verified as outlined here: https://support.google.com/cloud/answer/7454865?hl=en&ref_topic=3473162

This may have to be done by jay0lee.

**Comment by Lawpoint** [comment]
Same here =(

**Comment by Rikav** [comment]
This tool is awesome, but I can’t use it because of the issue with app verification :(.

**Comment by lifetimex** [comment]
Same

**Comment by rsnr** [comment]
same issue.

**Comment by rhlahuja** [comment]
Same

**Comment by letechnology** [comment]
Interestingly I get that warning on my regular gmail account but not gsuite legacy account.

**Comment by FromSkyrim** [comment]
mute the thread

letechnology <notifications@github.com> 于 2019年3月20日周三 上午11:08写道：

**Comment by sachin427** [comment]
Got this email today—related to this issue?

> > 

Hello,

Although you don’t need to take any action, we wanted to let you know that the following third-party apps will no longer be able to access some data in your Google Account, including your Gmail content. This change will go into effect starting March 31, 2019.

Got Your Back: Gmail Backup
We are making this change as part of ongoing efforts to make sure your data is protected and private. These apps haven’t yet complied with our updated data privacy requirements (https://cloud.google.com/blog/products/g-suite/elevating-user-trust-in-our-api-ecosystems) announced on October 8, 2018.

You can always view, manage and remove apps you’ve given access to your account by visiting your Google Account.


Thanks,
The Google Accounts team

**Comment by jay0lee** [comment]
GYB 1.20 is now available. Basic instructions for installing and fixing the issue are in the release notes:

https://github.com/jay0lee/got-your-back/releases

can a few people try upgrading and fixing and give me feedback on the process?

**Comment by davebalzotti** [comment]
Awesome thanks Jay!

**Comment by sachin427** [comment]
Thanks, Jay. Went through the entire authorization process without issue, but here's what happened when I tried running command: gyb --email email3432932@gmail.com --search "label:Test". I tried to revoke my previous authorization, but same error

Select the actions you wish GYB to be able to perform for inbox825@gmail.com

[ ]  0)  Gmail Backup And Restore - read/write mailbox access
[ ]  1)  Gmail Backup Only - read-only mailbox access
[ ]  2)  Gmail Restore Only - write-only mailbox access and label management
[*]  3)  Gmail Full Access - read/write mailbox access and message purge
[ ]  4)  No Gmail Access

[*]  5)  Groups Restore - write to G Suite Groups Archive
[*]  6)  Storage Quota - Drive app config scope used for --action quota

      7)  Continue
7
Traceback (most recent call last):
  File "gyb.py", line 2026, in <module>
  File "gyb.py", line 1365, in main
  File "gyb.py", line 321, in requestOAuthAccess
  File "oauth2client\_helpers.py", line 133, in positional_wrapper
  File "oauth2client\client.py", line 2135, in flow_from_clientsecrets
  File "oauth2client\clientsecrets.py", line 165, in loadfile
  File "oauth2client\clientsecrets.py", line 122, in _loadfile
  File "json\__init__.py", line 296, in load
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 11 column 1 (char 47
0)
[8612] Failed to execute script gyb

C:\gyb>

**Comment by jay0lee** [comment]
Looks like a typo that leaves a bad character in the client_secrets.json
file. Edit your client_secrets.json file and you'll see an out of place `
character at the start of one line. Delete that character and see if it
solves.

I'll also see about creating an updated build.

Jay

**Comment by sachin427** [comment]
That solved that issue, but another one came up when trying to restore:

C:\gyb>gyb --email email5654454@gmail.com --action restore

Using backup folder GYB-GMail-Backup-email5654454@gmail.com

Traceback (most recent call last):
  File "gyb.py", line 2026, in <module>
  File "gyb.py", line 1614, in main
sqlite3.OperationalError: database resume is locked
[4324] Failed to execute script gyb

**Comment by sachin427** [comment]
Sorry, that was a mistake on my part...everything works! Thank you, Sir

**Comment by rhlahuja** [comment]
Works for me now, thanks!

**Comment by Time-Saving** [comment]
> GYB 1.20 is now available

Thanks, Jay!  I am curious, though:  https://cloud.google.com/blog/products/g-suite/elevating-user-trust-in-our-api-ecosystems says that a security assessment fee "is paid by the developer and may range from $15,000 to $75,000 (or more) depending on the size and complexity of the application."  Do you have a wealthy patron who is covering this, or are you paying it yourself out of the goodness of your heart, or are you setting up a paid version of GYB, or ...?  If you are paying this yourself for our benefit, thank you even more!  Wow!

**Comment by jay0lee** [comment]
Each GYB user will now create their own project. You don't need to be verified to authenticate against your own project. Problem solved (or worked around I guess).
