### ISSUE TITLE
GYB hangs when backing up to NFS mount point

### ISSUE THREAD

**Issue by xenorites** [jay0lee/got-your-back#196]
Full steps to reproduce the issue:
1. Mount an NFS share between two Linux hosts - the NFS server option `async` may be part of the issue
2. Attempt to back up with `--target-folder` being on the NFS share, or GAM running from the NFS share

Expected outcome (what are you trying to do?):

GAM successfully backs up

Actual outcome (what errors or bad behavior do you see instead?):

GAM hangs after creating the `.sqlite` file; console displays `Using backup folder [backup_folder]`. Am unable to kill the task with anything less than `kill -9`; have left it for over an hour to see if it would progress.

**Comment by jay0lee** [comment]
This is not likely to be GYB's fault, using SQLite over NFS is simply not recommended as a few Google searches will reveal, lot's of problems.

I suggest you experiment with performing the backup / restore to a local filesystem and then afterwards (or before) copying to/from NFS
