### ISSUE TITLE
setup.py py2exe error on Mac Yosemite

### ISSUE THREAD

**Issue by wilsonmar** [jay0lee/got-your-back#20]
I am working on a Mac, Yosemite version.
When I run setup.py install, I'm getting this error:

  File "setup.py", line 2, in &LT;module>
    import py2exe, sys, os
ImportError: No module named py2exe

Isn't py2exe for Windows only?
How can I get past this?

**Comment by jay0lee** [comment]
setup.py was only meant for Windows compilation of GYB, not Macs.
