### ISSUE TITLE
Add some message identificator to error for messages that can't be restored from mbox

### ISSUE THREAD

**Issue by bahusoid** [jay0lee/got-your-back#201]
I have some messages in pretty large mbox file that can't be restored due to "ERROR: 400: Bad Request." error.

So can you add some info to error so that problem messages can be found and inspected in mbox file manually.

Looking at my mbox file it looks like Message-ID a good candidate for it:
`Message-ID: <00f801d309d9$c6c07050$544150f0$@com>`

**Comment by Adam0111** [comment]
Hey,
It would be very helpful to make a youtube video on how to restore a .mbox file (GoogleTakeOut file)......
