### ISSUE TITLE
GYB does not support mbox --> group restoration

### ISSUE THREAD

**Issue by TimetravelerDD** [jay0lee/got-your-back#202]
It seems GYB does not support mbox --> group restoration (at least according to this post from 2014)

If so, would it be possible to support it? I think it would be quite useful if the original account doesn't exist anymore but only the mbox backup from Google takeout/vault.

Alternatively a feature to convert mbox to GYB and vice versa would be awesome as well.

Looking forward to hear your feedback!

Cheers, Timetraveler

> GYB does not support mbox --> group restoration, it can only restore a GYB
> backup to a group. You can try backing up the maibox with GYB and then
> restoring from there.
> 
> Jay Lee
> 

On Fri, Nov 21, 2014 at 6:34 AM, bjarnek notifications@github.com wrote:

> Tried making one of the service accounts using the instructions and still
> get an error. Am i doing anything wrong here ?
> 
> python gyb.py --action restore-group --action restore-mbox --local-folder input/ --email test-indbakke-samarbejde@mydomain.com.test-google-a.com --service-account 110042144726-5s76aeu20g3p6ki544an2s94ekt67847@developer.gserviceaccount.com --use-admin myuser@mydomain.com
> Traceback (most recent call last):
>   File "gyb.py", line 1323, in <module>
>     main(sys.argv[1:])
>   File "gyb.py", line 575, in main
>     imapconn = gimaplib.ImapConnect(generateXOAuthString(options.email, options.service_account), options.debug)
>   File "gyb.py", line 269, in generateXOAuthString
>     service = apiclient.discovery.build('oauth2', 'v2', http=http)
>   File "/Users/myuser/Downloads/got-your-back-0.29/oauth2client/util.py", line 128, in positional_wrapper
>     return wrapped(_args, *_kwargs)
>   File "/Users/myuser/Downloads/got-your-back-0.29/apiclient/discovery.py", line 192, in build
>     resp, content = http.request(requested_url)
>   File "/Users/myuser/Downloads/got-your-back-0.29/oauth2client/util.py", line 128, in positional_wrapper
>     return wrapped(_args, *_kwargs)
>   File "/Users/myuser/Downloads/got-your-back-0.29/oauth2client/client.py", line 475, in new_request
>     self._refresh(request_orig)
>   File "/Users/myuser/Downloads/got-your-back-0.29/oauth2client/client.py", line 653, in _refresh
>     self._do_refresh_request(http_request)
>   File "/Users/myuser/Downloads/got-your-back-0.29/oauth2client/client.py", line 710, in _do_refresh_request
>     raise AccessTokenRefreshError(error_msg)
> oauth2client.client.AccessTokenRefreshError: internal_failure
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jay0lee/got-your-back/issues/14#issuecomment-63958836
> .

_Originally posted by @jay0lee in https://github.com/jay0lee/got-your-back/issues/14#issuecomment-63966844_

**Comment by jay0lee** [comment]
restoring from mbox to group has been supported since 1.40. It should "just work" with --action restore-group and --local-folder /path/to/mall/the/mboxes
