### ISSUE TITLE
Missing upgrade instructions in README / wiki

### ISSUE THREAD

**Issue by nekromoff** [jay0lee/got-your-back#203]
GYB offers new version for download, but installation will fail with 

```
File /home/xxxx/bin/gyb/oauth2service.json already exists. Please delete or rename it before attempting to create another project.
Project creation failed. Trying again.
```

repeated ad infinitum, unless break `CTRL+D` is applied.

**Comment by spockmetals** [comment]
> GYB offers new version for download, but installation will fail with
> 
> ```
> File /home/xxxx/bin/gyb/oauth2service.json already exists. Please delete or rename it before attempting to create another project.
> Project creation failed. Trying again.
> ```
> 
> repeated ad infinitum, unless break `CTRL+D` is applied.

Same reply on command 

`bash <(curl -s -S -L https://git.io/gyb-install)
`

**Comment by spockmetals** [comment]
Same error while upgrading with

`bash <(curl -s -S -L https://git.io/gyb-install)
`

**Comment by nekromoff** [comment]
That's what I meant (using install instructions for upgrade), sorry!

**Comment by jay0lee** [comment]
Add a -l to the very end to upgrade the binary without running through setup also. I can add this to the README (or someone is welcome to add it via a pull request)

**Comment by nekromoff** [comment]
Works great, thanks. Closing this issue.
