### ISSUE TITLE
restore-mbox doesn't seem to honor --label-prefix

### ISSUE THREAD

**Issue by cwalkatron** [jay0lee/got-your-back#216]
Full steps to reproduce the issue:
1. Do an mbox export from Google Vault 
2. `gyb --action restore-mbox --email me@mydomain.com --label-prefix gybrestore`
3. login as me@mydomain in Gmail. All the mail is restores, but all the labels are at the top level.

Expected outcome (what are you trying to do?):
I am trying to do an mbox restore into an account, but would like all the messages to be under a label.

Actual outcome (what errors or bad behavior do you see instead?):
I see all the messages restore, but --label-prefix is not applied.

**Comment by erozcomar** [comment]
Hi. Same problem here.
I've tried version 1.30 and 1.31 with --label-restored but it didn't work for me.
Try with local account, and with --service-account without positive results.
All the mail is restores, but all the labels are at the top level.
Any debug to help?
Regards

**Comment by cwalkatron** [comment]
Unfortunately, I can't contribute to open source projects without jumping through some company hoops, but I will tell you that it's a 2-line change to `gyb.py` to make this work. Sorry that is a really unhelpful comment.

**Comment by aalkz** [comment]
I had this problem as well, everything restored perfectly, but I could never manage to get the label argument applied.

**Comment by jay0lee** [comment]
this should be fixed in latest GYB versions, if not please re-open.

**Comment by reflecx** [comment]
label-prefix for mbox restore doesn't work. I looked through the source code, the label-prefix code is only in the restore action, it's not executed within the restore-mbox action
