### ISSUE TITLE
1.29 Missing valid API key

### ISSUE THREAD

**Issue by dsl101** [jay0lee/got-your-back#219]
Running for the first time on Windows 10 results in:
```
Creating project "Got Your Back Project"...
Checking project status...
 enabling API drive.googleapis.com...

403: b'{\n  "error": {\n    "code": 403,\n    "message": "The request is missing a valid API key.",\n    "status": "PERMISSION_DENIED"\n  }\n}\n' - b'{\n  "error": {\n    "code": 403,\n    "message": "The request is missing a valid API key.",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
```

Full steps to reproduce the issue:
1. Run `gyb --action create-project --email XXX@gmail.com`
2. Complete authentication steps
3. Sign ToS at https://console.cloud.google.com/start
4. Press Enter in command line window

**Comment by jay0lee** [comment]
This should be fixed in [1.30](https://git.io/releases).
