### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by garyo** [jay0lee/got-your-back#221]
Now that I'm doing using GYB, I'd like to remove the Google Cloud project and any stray permissions it created -- is there an approved way to do that?

**Comment by MagTun** [comment]
I think you need  :
- to delete the project created by gyb on https://console.developers.google.com: open your project, click on the little 3 dots on the top right and then select `Shut down project`
- to remove the 3rd party access to your Google account : https://myaccount.google.com/security, scroll down to `Third-party apps with account access` and  click on `Manage third-party access`. Then select the apps and click on `Remove access`. 

But a confirmation from the developer would be necessary.
