### ISSUE TITLE
Avoid giving gmail authorization to "GAM Project Creation"

### ISSUE THREAD

**Issue by mightypanda** [jay0lee/got-your-back#231]
Hello,
I'd love to use the tool, but i would not like to give full access to my account to "GAM Project Creation" as requested during install.
Are there other alternatives, like creating a new app in developer console?

Thank you!

**Comment by githublabla** [comment]
> Hello,
> I'd love to use the tool, but i would not like to give full access to my account to "GAM Project Creation" as requested during install.
> Are there other alternatives, like creating a new app in developer console?
> 
> Thank you!

Hey,
That is a very good question! :D and I'm looking for the answer too.
It's like giving a full access to your gmail account to somebody you don't even know.
Interesting...

**Comment by jay0lee** [comment]
As part of the setup process, you temporarily (max 1 hour) authorize GYB to create an API project for itself for future use. This is what this page is referring to. This is working as intended.

**Comment by dreammaker** [comment]
So is it possible to revoke access after the initial setup process and still have the app work?

**Comment by Taytay** [comment]
I had the same question. Is there a way to do this and keep all of the authorizations and keys local somehow instead of using Oauth to grant these permissions? The permissions are (understandably) vast, and it feels like I'd be handing the keys to the kingdom to this service running on Appspot.
