### ISSUE TITLE
What does "killed up" message mean when creating a backup?

### ISSUE THREAD

**Issue by jason-dark** [jay0lee/got-your-back#232]
When running on G Cloud shell:
`gyb --email user@domain.com --service-account  --local-folder ~/email_backups/user`

I get this output:
```
Got 5689 Message IDs
GYB needs to examine 5689 messages
GYB already has a backup of 0 messages
GYB needs to backup 5689 messages
backed up 400 of 5689 messages
backed up 500 of 5689 messages
Killed up 1800 of 5689 messages
```

I can't find what the `Killed up` message refers to. I've looked through the source code but can't seem to find it in here either.

When running the same command from my local Windows machine this message does not occur.

Any ideas?

**Comment by jay0lee** [comment]
As you found GYB does not contain the term killed in the source code. This is likely some other process on your machine being killed by the OS out of memory detection or similar, it's not a GYB issue.

**Comment by thenickdude** [comment]
In my case this was due to GYB being killed by the Out-Of-Memory killer due to memory exhaustion (you can diagnose that by checking the kernel log, like /var/log/kern.log, where it'll record that the OOM killer took action).
