### ISSUE TITLE
retainining previously backed up emails during subsequent backups

### ISSUE THREAD

**Issue by sackio** [jay0lee/got-your-back#236]
If one runs backup A, saving all emails to a local directory. Then, one runs another backup B at a later date, saving all emails to the same local directory, will GYB delete or leave untouched any emails downloaded during backup A which were deleted on the server before backup B?

**Comment by arddg** [comment]
Hi! Same question here. Can somebody answer it please?

**Comment by billdenney** [comment]
If a message was moved to trash before the backup occurs, the GYB wiki page answers that "there's currently no way to backup Trash and Spam with GYB".  But, that answer conflicts with the description of the `--spam-trash` command line argument.

I wanted to know the same answer, so I tested it.  The process I used was:

1. Send an email to the account
2. Backup the account, and confirm that the email is in the backup
3. Move the email to trash, and backup the account again
    1. One fewer message ID was detected
4. Check if the file still exists.  It does.

**Comment by billdenney** [comment]
@jay0lee, I tested the `--spam-trash` option and updated the wiki page to indicate that you can backup spam and trash with that option.  If I'm wrong, please revert the change.

**Comment by arddg** [comment]
I think the question was not about spam/trash. I'll try to explain.
1. GYB makes full backup.
2. Email user deletes some messages from Inbox folder and empties recycle bin folder
3. GYB makes next backup
So will those deleted messages be deleted from GYB backup too? Or will GYB retain those messages forever in the backup?
I have made some tests too and it seems that GYB does not delete any messages from backup. But it was just express testing so I'm not 100% sure about that.
