### ISSUE TITLE
Getting SyntaxError on running any gyb function in Terminal

### ISSUE THREAD

**Issue by casparderoij** [jay0lee/got-your-back#237]
Running on the latest version of OSX (10.14.15).

Followed installation instructions, running the most recent OSX release.

When I try to run the --estimate line to test if things are working, I get the following error:

File "gyb", line 1
SyntaxError: Non-UTF-8 code starting with '\xcf' in file gyb/gyb on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Can't find any other reference to this here. Is this something related to my computer? Any help would be greatly appreciated!

**Comment by jay0lee** [comment]
You downloaded the compiled version of GYB but you're trying to run it with Python, just execute the gyb file like you would a normal binary.
