### ISSUE TITLE
error: Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by thatneat** [jay0lee/got-your-back#240]
Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue. ☑️
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki
  * _kind of_. The linux instructions to run `gyb.py` only work when you download the source distribution (1.31) and install the requirements file. I did this. I also downloaded what appeared to be the latest binary distribution (the one with `glibc2.23`) and had to run `./gyb` instead of `python3 gyb.py` . Either way, I was prompted to run `--action create-project` instead of `--action estimate`. Either way, the error message was the same.

This appears related to an old issue, #194 .

## Full steps to reproduce the issue:
I have tried this with the latest source distribution as well as the latest binary distribution. I have tried this with a gmail account and a Google Apps domain account.

1. (with source distribution) run `python3 gyb.py --email [MY EMAIL] --action create-project`
2. go to the link provided and click on my account

## Expected outcome (what are you trying to do?):
a project is created and everything works

## Actual outcome (what errors or bad behavior do you see instead?):
I'm redirected to an error page that says:

> ⚠️
> Sign in with Google temporarily disabled for this app
> This app has not been verified yet by Google in order to use Google Sign In.

screenshot:
![image](https://user-images.githubusercontent.com/3341011/70343438-1fc68700-180c-11ea-8dbc-8c873ad63466.png)

**Comment by jay0lee** [comment]
Thanks for catching this. It may take me awhile to get this resolved but in the meantime you can workaround the issue by whitelisting the GAM Creation project:

Go to https://admin.google.com/AdminHome?hl=en#Oauth2ScopeManagement:subtab=trusted
Click the yellow + Circle at bottom right.
For app type select "Web Application"
For OAuth2 Client ID put:
297408095146-fug707qsjv4ikron0hugpevbrjhkmsk7.apps.googleusercontent.com
Go grab a cup of coffee (wait 5-10 minutes).
After a few minutes, you should be able to rerun the install or rerun GYB command and be allowed to accept the application.

**Comment by wyoibc** [comment]
Does whitelisting GAM Creation Project introduce any vulnerabilities?

**Comment by jay0lee** [comment]
No. If it makes you uncomfortable you can remove the whitelisting after
you've finished the setup process.

**Comment by VaibhavAvasarala** [comment]
This workaround is for G-Suite users only. What about non G-Suite accounts?

**Comment by jay0lee** [comment]
What do you mean? Cloud Identity? Google Apps Free?

**Comment by VaibhavAvasarala** [comment]
What i meant was for, for google accounts which are not of G-Suite category, this workaround doesn't help.

**Comment by funkmuseum** [comment]
Hello !
What VaibhavAvasarala said is happening also for me :
>> Go to https://admin.google.com/AdminHome?hl=en#Oauth2ScopeManagement:subtab=trusted
>> This workaround is for G-Suite users only. What about non G-Suite accounts?

I mean, I do not have an G-Suite account (administrator), I have only a regular Gmail account .
Next, trying to use gyb (in the Windows command prompt) , I get the following response:

C:\GYB>gyb --action create-project --email funkmuseum@gmail.com
Go to the following link in your browser:
        https://gyb-shortn.jaylee.us/xxyyzz
Enter verification code:

Well, If I try to access that link, I get a login request :

Choose an account to continue to GAM Project Creation

.... and after login (using my regular Gmail account) , I get the following response from GSuite page (admin.google.com):

admin.google.com is for G Suite accounts only. Regular Gmail accounts cannot be used to sign in to admin.google.com. Learn more

So ... how may I resolve the problem, while I do not have any admin account ?!

Thanks a lot and have a nice day,
Funkmuseum

**Comment by bryantech** [comment]
I have a QNAP with archived accounts. I tried restoring and I am getting this error. I also tried restore with new GYB and was told the data is in version 5 and 6 is needed.

**Comment by jay0lee** [comment]
this is now fixed.

**Comment by benjepstein** [comment]
I seem to be getting this same error now with the newest version (1.34).  Any thoughts?
