### ISSUE TITLE
--label-restored doesn't work without --strip-labels when restoring mboxes

### ISSUE THREAD

**Issue by lm2807** [jay0lee/got-your-back#241]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Have mbox file, NOT from google (no metadata xml)
2. Attempt to import mbox to `user@gmail.com`, and label imported mail via `--label-restored`:
  `gyb --email user@gmail.com --action restore-mbox --label-restored "TestLabel" --local-folder mbox_folder/`
3. Confirm that the mail is imported to `user@gmail.com` in All Mail but mail has NOT been labeled.
4. Repeat command from step 2, this time with additional `--strip-labels`:
  `gyb --email user@gmail.com --action restore-mbox --strip-labels --label-restored "TestLabel" --local-folder mbox_folder/`
5. Confirm that the mail has been imported to `user@gmail.com` and has been labeled correctly.

Expected outcome (what are you trying to do?):
Label defined via `--label-restored` should be applied regardless of the use of `--strip-labels`

Actual outcome (what errors or bad behavior do you see instead?):
Label defined via `--label-restored` is only applied when `--strip-labels` is also set.

**Comment by jay0lee** [comment]
fix will be in 1.32.
