### ISSUE TITLE
cant open file gyb.py

### ISSUE THREAD

**Issue by yogdude** [jay0lee/got-your-back#242]
extracted gyb on mac to a sub-folder in the home directory and when i try to run the python3 gyb.py --email youremail@gmail.com --action estimate it gives this error /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'gyb.py': [Errno 2] No such file or directory

in the gyb folder extracted there is only a gyb executable, cant see any gyb.py in it. 

i installed the  gyb-1.33-macos-x86_64-MacOS10.14.4.tar.xz on my mac running 10.15.2

**Comment by jay0lee** [comment]
This is the expected behavior. Just execute gyb binary and don't worry about Python, it's built-in to that gyb binary. If you want to use your own Python download the src archive instead of the MacOS binary.

**Comment by yogdude** [comment]
thanks. 

for the benefit of newbies: to execute the gyb binary from terminal run this command ./gyb --email youremail@gmail.com --action estimate
