### ISSUE TITLE
Discontinuing support for JSON-RPC and Global HTTP Batch Endpoints And Error injection schedule

### ISSUE THREAD

**Issue by adminintersog** [jay0lee/got-your-back#243]
Hello,

Our company uses your software GYB for backup emails.
Once  we got the following message  from Google :
![oneprb](https://user-images.githubusercontent.com/59828084/72253774-f66af900-360a-11ea-8e56-2aeacf6131f4.png)
![one](https://user-images.githubusercontent.com/59828084/72253795-0256bb00-360b-11ea-9d8b-36bcc9035989.png)

Could you please explain this message? Would your software be working in the near future?

Thank you.

**Comment by jay0lee** [comment]
The latest version of GYB does not use these endpoints. Make sure you've upgraded to the latest GYB.
