### ISSUE TITLE
Uploading MBOX backup works, but emails are invisible

### ISSUE THREAD

**Issue by Protofall** [jay0lee/got-your-back#246]
I wanted to backup my old Apple Mail emails that use the MBOX format. I did so by starting to follow this guide <https://www.bitrecover.com/blog/import-apple-mail-to-gmail/> (Up until they recommended their dodgy software). Then I started using GYB by downloading the latest release, Windows v1.34. I ran the setup commands then `gyb --email MY-EMAIL@gmail.com --action restore-mbox --local-folder "c:\gyb\MacMailBackup\Archive.mbox"` and aside from 3 "Bad request" errors it said it uploaded just fine.

When I checked my gmail account I saw nothing new, however I knew some of the names of the old emails so I searched them and they did show up. I've checked all the tabs on the left sidebar, but they only appear under "All Mail". These invisible emails don't seem to have any label that I can see.

This could be the same issue discussed in #191. Is this intended behaviour or should they be put into their own label? And do you know if there's a way to easily assign all these "invisible" emails a label?

**Comment by jay0lee** [comment]
this is working as intended since you are not adding any labels to the restore with `--label-restored mbox` or similar. These "invisible" messages can be found via search or under all mail as you found.

**Comment by Protofall** [comment]
Ah damn, I didn't know there was a label parameter. Thanks for the help
