### ISSUE TITLE
Email restored with incorrect time

### ISSUE THREAD

**Issue by panmail** [jay0lee/got-your-back#248]
I'm using GYB 1.34 in Windows 10 trying to backup from one gmail account and restore to another.

0) ran gyb-setup.bat and configured my 2 gmail accounts by providing oauth ids and secrets.
1) gyb --email xxx@gmail.com --action backup --local-folder "F:\gybBackUp"
2) gyb --email yyy@gmail.com --action restore --local-folder "F:\gybBackUp" 

Backup took about 1hr for 11GB worth of gmail emails.
Restore took like 8x, or 8hrs, to complete.  got a few "ERROR: 400 Expected a single 'From' header.  Skipping message restore, you can retry later with --fast-restore" along the way.

What I noticed is that some emails were sent, say Jan 22nd 2019 1:59pm, in the xxx@gmail.com account, has now been restored to be sent, Feb 23rd 2020 16:03, in the yyy@gmail.com account.

**Comment by jay0lee** [comment]
This is the expected behavior it some of your messages have a bad date
header. GYB tells Google to set the message date based off the date header,
however if Gmail servers can't properly parse the date header they have to
fallback to the time the message was imported.

Jay

**Comment by panmail** [comment]
Hi Jay,

Is there any ways to identify from a gyb backup log (?? perhaps **_msg-db.sqlite_** ??) which messages are affected?  or maybe a command line switch to turn on error logging?

Further more would it be possible to manually edit the downloaded .eml files so the gyb restore could stamp the affected emails with the correct date?

ATM, since there is at-least 1 message out of 32K that I could spot check as being affected, I couldn't really trust the entire restore because I need the email histories to reflect what really took place.  I feel we are almost there.

You have a very unique and awesome piece of utility which I don't know why Google doesn't provide.  Very much appreciate your help.

John

**Comment by jay0lee** [comment]
No way for GYB too identify as Google doesn't report whether it parsed the
header correctly or not.

Can you share headers for some messages that did not get correct date?

**Comment by panmail** [comment]
below is the original email header 
and the imported email header which has yesterday's date.
it should have been Jan 22, 2019, not sure why this date isn't on the original email header though.
please let me know what else I could provide?

![image](https://user-images.githubusercontent.com/7851873/75161179-3aecb880-56d0-11ea-8296-73754c868625.png)

**Comment by jay0lee** [comment]
Well there is NO Date: header on the original message that I can see so
that would explain why Google had to add a Date: header itself. Based on
the screenshot there's no way for Google to know that the message was from
Jan 2019....

Jay Lee

**Comment by panmail** [comment]
that my thought too.
do you think this is an issue with the export step because in my browser,
google is reporting the correct sent date so the correct sent date is saved
within google somewhere.
i'll try the export again and see if the issue persists with the same email.

**Comment by jay0lee** [comment]
There's no date header on the original message, it's not an export issue,
it's that the data just isn't there. At some point the email got imported
to Google without a date header, however that was done it looks like the
"internal date" was set but the Date header was not.

Again, not much GYB can do to fix this.

Jay Lee

**Comment by panmail** [comment]
hmmmm .... that's interesting.
so there's an "internal date" kept somewhere by Gmail and this doesn't get
exported by GYB nor Google Takeout?

**Comment by jay0lee** [comment]
correct, Gmail API does see the internal date.
