### ISSUE TITLE
failed to execute script pyi_rth_multiprocessing

### ISSUE THREAD

**Issue by pipiscrew** [jay0lee/got-your-back#250]
hi all, 

today I downloaded **gyb-1.35-windows-x86_64.zip** (also gyb-1.35-windows-x86_64.msi) tried... 

one thing here
when changing **pyinstaller** version, you have to write that requires 
VC++ 2015 runtimes. [microsoft download](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

the **main issue** is that 

when execute the **gyb-setup.bat** getting 

> C:\gyb>gyb-setup
> 
> Please enter your Google email address: test@gmail.com
> Traceback (most recent call last):
>   File "Lib\site-packages\PyInstaller-4.0.dev0+a1f92c6a08-py3.8.egg\PyInstaller\
> loader\rthooks\pyi_rth_multiprocessing.py", line 17, in <module>
>   File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+a1f92c6a08-py3.8.egg\Py
> Installer\loader\pyimod03_importers.py", line 489, in exec_module
>   File "multiprocessing\__init__.py", line 16, in <module>
>   File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+a1f92c6a08-py3.8.egg\Py
> Installer\loader\pyimod03_importers.py", line 489, in exec_module
>   File "multiprocessing\context.py", line 6, in <module>
>   File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+a1f92c6a08-py3.8.egg\Py
> Installer\loader\pyimod03_importers.py", line 489, in exec_module
>   File "multiprocessing\reduction.py", line 16, in <module>
>   File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+a1f92c6a08-py3.8.egg\Py
> Installer\loader\pyimod03_importers.py", line 489, in exec_module
>   File "socket.py", line 49, in <module>
> ImportError: DLL load failed while importing _socket: The parameter is incorrect

when executing the **gyb.exe** 
C:\gyb>gyb

> Traceback (most recent call last):
>   File "Lib\site-packages\PyInstaller-4.0.dev0+a1f92c6a08-py3.8.egg\PyInstaller\
> loader\rthooks\pyi_rth_multiprocessing.py", line 17, in <module>
>   File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+a1f92c6a08-py3.8.egg\Py
> Installer\loader\pyimod03_importers.py", line 489, in exec_module
>   File "multiprocessing\__init__.py", line 16, in <module>
>   File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+a1f92c6a08-py3.8.egg\Py
> Installer\loader\pyimod03_importers.py", line 489, in exec_module
>   File "multiprocessing\context.py", line 6, in <module>
>   File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+a1f92c6a08-py3.8.egg\Py
> Installer\loader\pyimod03_importers.py", line 489, in exec_module
>   File "multiprocessing\reduction.py", line 16, in <module>
>   File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+a1f92c6a08-py3.8.egg\Py
> Installer\loader\pyimod03_importers.py", line 489, in exec_module
>   File "socket.py", line 49, in <module>
> ImportError: DLL load failed while importing _socket: The parameter is incorrect
> .
> [2952] Failed to execute script pyi_rth_multiprocessing

then came across with 
[pyinstaller/pyinstaller - Failed to execute script pyi_rth_multiprocessing](https://github.com/pyinstaller/pyinstaller/issues/4066)

an author with the same error, used [pypi](https://pypi.org/project/auto-py-to-exe/) to pack the files and the error disappear.

**Comment by jay0lee** [comment]
Can you offer more details about the version of windows you are running?

**Comment by pipiscrew** [comment]
tested on two machines with Windows7x64

**Comment by pipiscrew** [comment]
please read also this :
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess

**Comment by pipiscrew** [comment]
so, I download Python v3.8 installer, didnt start 

![743](https://user-images.githubusercontent.com/3852762/75612181-e3b07300-5b29-11ea-8854-28c4118e4003.png)

where is no KB2533625 [ref - stackoverflow ](https://stackoverflow.com/a/59339132)

[ms download](https://download.microsoft.com/download/F/1/0/F106E158-89A1-41E3-A9B5-32FEB2A99A0B/Windows6.1-KB2533623-x64.msu)

and finally 
![744](https://user-images.githubusercontent.com/3852762/75612212-3853ee00-5b2a-11ea-9dba-95b65a7a3bdb.png)

thanks for your time @jay0lee
