### ISSUE TITLE
AttributeError: 'OperationalError' object has no attribute 'message'

### ISSUE THREAD

**Issue by djwesterfield** [jay0lee/got-your-back#253]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
Yes
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki
Yes

Full steps to reproduce the issue:
1. I selected the prompt for 'Gmail Restore Only'
2. Verified all of the links
3. Use snippit: 
gyb --email theemail@gmail.com --action restore --local-folder "D:\Download\Mail"
4. Received this error:
Using backup folder D:\Downloads\Mail
Traceback (most recent call last):
  File "gyb.py", line 1125, in get_db_settings
sqlite3.OperationalError: no such table: settings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 2171, in <module>
  File "gyb.py", line 1550, in main
  File "gyb.py", line 1129, in get_db_settings
AttributeError: 'OperationalError' object has no attribute 'message'
[26836] Failed to execute script gyb

Expected outcome (what are you trying to do?):
I was expecting it would upload all of my .mbox emails to my new gmail address.
Actual outcome (what errors or bad behavior do you see instead?):
Nothing was transferred.

**Comment by jay0lee** [comment]
`--action restore` implies that your files in D:\Downloads\Mail are stored in GYB's own format. Since they are mbox files you need to run:

```
gyb --email theemail@gmail.com --action restore-mbox --local-folder "D:\Download\Mail"
```
