### ISSUE TITLE
400 Error during backup. Msg "Inner request count exceeds the limit. Received: 100, Limit: 50"

### ISSUE THREAD

**Issue by wicknet** [jay0lee/got-your-back#255]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. ./gyb --email user@myDomain.org --action backup --service-account

Expected outcome (what are you trying to do?):
Full backup of user's gSuite account

Actual outcome (what errors or bad behavior do you see instead?):
Evey 100 count of messages have the message below:
backed up 2400 of 185999 messages                                               
400: b'{\n  "error": {\n    "code": 400,\n    "message": "Inner request count exceeds the limit. Received: 100, Limit: 50",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n' - b'{\n  "error": {\n    "code": 400,\n    "message": "Inner request count exceeds the limit. Received: 100, Limit: 50",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n'
 - Giving up.
backed up 2500 of 185999 messages                                               
400: b'{\n  "error": {\n    "code": 400,\n    "message": "Inner request count exceeds the limit. Received: 100, Limit: 50",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n' - b'{\n  "error": {\n    "code": 400,\n    "message": "Inner request count exceeds the limit. Received: 100, Limit: 50",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n'

This problem is restricted only to one user's account - no new data is backed up. The same command works for 3 other test accounts in the same domain with 0 errors. 

Since the user is leaving the organization, he wanted to re-create his work mailbox on his personal gmail with all the threads and labels intact, with the help of gyb.

**Comment by superbarney** [comment]
I am experiencing the same error with GYB 1.37, on two separate Windows machines and a Ubuntu 19.10 VM. The account has about 20000 emails.

In the mailing list, someone mentioned that it is only occuring for accounts that has more than 10000 emails.

**Comment by wicknet** [comment]
The command has been tested to work fine for users with larger mailboxes. 

Hoping there is a config setting to reduce requests to 50 instead of 100 for this user's mailbox backup.

**Comment by mystix** [comment]
Running gyb 1.36 on MacOS 10.15.3 with Python 3.7.2.

I'm seeing the same error for 1 of 4 accounts from the same domain.

The account in question has less than 2000 emails.

**Comment by terbolous** [comment]
Experiencing the same with 1 account. Initially I was running GYB 1.10, but upgrading to latest 1.36 didn't help.

**Comment by terbolous** [comment]
Specifying `--batch-size 49` worked in my case

**Comment by wicknet** [comment]
OMG! Thank you SO much for that tip. 

Specifying the batch size immediately got rid of the problem!
