### ISSUE TITLE
Inner request count exceeds the limit. Received: 100, Limit: 50

### ISSUE THREAD

**Issue by seedeewhy** [jay0lee/got-your-back#256]
Full steps to reproduce the issue:
1.  gyb --email someone@mydomain.com --service-account
2.
3.

Expected outcome (what are you trying to do?):
Starts backing up

Actual outcome (what errors or bad behavior do you see instead?):
>gyb --email someone@mydomain.com --service-account

Using backup folder GYB-GMail-Backup-someone@mydomain.com
Got 113 Message IDs
GYB needs to examine 113 messages
GYB already has a backup of 0 messages
GYB needs to backup 113 messages

400: b'{\n  "error": {\n    "code": 400,\n    "message": "Inner request count exceeds the limit. Received: 100, Limit: 50",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n' - b'{\n  "error": {\n    "code": 400,\n    "message": "Inner request count exceeds the limit. Received: 100, Limit: 50",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n'
 - Giving up.
backed up 113 of 113 messages

GYB needs to refresh 0 messages

Tried with different users but all triggered the same error.
Just downloaded new gyb 5 mins ago.

**Comment by edenk27** [comment]
Hi, I had the same problem and found this closed issue https://github.com/jay0lee/got-your-back/issues/255
The solution that worked for me was specifying --batch-size 49

**Comment by martinh-joventures** [comment]
> Hi, I had the same problem and found this closed issue #255
> The solution that worked for me was specifying --batch-size 49

This worked for me too.
