### ISSUE TITLE
Update Instructions for --action create-project

### ISSUE THREAD

**Issue by ghost** [jay0lee/got-your-back#261]
When creating a project you are met with this prompt:

1. Enter "GYB" for "Application name".
2. Leave other fields blank. Click "Save" button.
3. Choose "Other". Enter a desired value for "Name". Click the blue "Create" button.
4. Copy your "client ID" value.

At step 3 your choices for "application type" are: Web Application, Android, Chrome app, iOS, TVs and Limited Input devices, Desktop app, Universal Windows Platform (UWP).

There is no choice for "other" as stated in the prompt.

**Comment by DJBROKEBOY1** [comment]
@zachravingsmiles Did you happen to install on Mac on Catalina? I'm a little stuck on the install

**Comment by whatamidoingwrong** [comment]
It worked for me when I selected "Desktop app."  I hope this helps.

**Comment by gene1wood** [comment]
This was duplicated in #272 and fixed in #273
