### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by zorflieg** [jay0lee/got-your-back#268]
Hi i'm using the latest version of gyb on macOS mojave, setup the gmail user, trying to import mbox.

--
Wolfy:gyb zorflieg$ ./gyb --email zorflieg@gmail.com --action restore-mbox --local-folder /Users/zorflieg/Downloads/gyb/mbox.mbox
ERROR: Folder /Users/zorflieg/Downloads/gyb/mbox.mbox does not exist. Cannot restore.
--

It is a mbox file exported from thunderbird with some test emails in it.

The file does exist.

I've tried sudo, no sudo.

I've tried moving the mbox file to another folder, checked file permissions.

Added gyb to 'full disk access' in macOS security.

It just tells me my mbox file isn't there when it is?

Does anyone know why it thinks it's not there?

**Comment by jay0lee** [comment]
GYB is looking for a _folder_ and will migrate all mbox files in the specified folder, you are specifying an exact filename.

Create a folder called mbox, put mbox.mbox file in the folder and run GYB again making sure --local-folder specifies the folder not the file.

**Comment by zorflieg** [comment]
Got it. Totally my fault.
Maybe the wiki could say:
'Use the --local-folder option to specify the path where you've extracted all of your mbox files and not a specific mbox file.'
For dummies like me.
Just as i think a common use of this excellent program could be dumping one large label/folder called 'export' or 'archive' in say a single mbox and then bulk import a single mbox file.
I immediately thought as i didn't have multiple mboxes i should specify the mbox and not a folder full of 1 mboxes.
Just a suggestion.
