### ISSUE TITLE
Error when restoring folders to new account

### ISSUE THREAD

**Issue by taesu99** [jay0lee/got-your-back#27]
I am having difficulty transferring folders from local folder to new email account
OS: Windows 07
C:\gyb>gyb --email [email] --action restore --local-folder "[folder label]"
Using backup folder [folder label]
using IMAP folder [Gmail]/All Mail
restoring message 1 of [number] from [eml file]
error retrieving uid: [' [APPENDUID 11 17581] <Success> [THROTTLED]']: retrying...
Traceback <most recent call last>:
File "gyb.py", line 1323, in <module>
File "gyb.py", line 911, in main
UnboundLocalError: local variable 'restored_uid' referenced before assignment

**Comment by edhillis** [comment]
I'm also getting this error, but only with one of the accounts I am restoring. 
OS: Windows 8, GYB 0.31 windows x64

It started here:

  Using backup folder \gyb-folders\allys
  using IMAP folder [Gmail]/All Mail
  restoring message 1539 of 8329 from 2014\10\31\11-16288.eml
  imaplib.abort error:command: APPEND => socket error: EOF, retrying...
  restoring message 1954 of 8329 from 2014\9\17\11-14595.emll
  imaplib.abort error:command: APPEND => socket error: EOF, retrying...
  restoring message 3281 of 8329 from 2014\1\27\11-10811.eml
  error retrieving uid: ['[APPENDUID 11 12170] (Success) [THROTTLED]']: retrying...

Then I deleting the backup folder, backed up again, and tried to restore again, and now I get this:

  Using backup folder \gyb-folders\allys
  using IMAP folder [Gmail]/All Mail
  restoring message 1 of 7369 from 2015\1\26\11-18577.eml
  error retrieving uid: ['[APPENDUID 11 13246] (Success) [THROTTLED]']: retrying...
  Traceback (most recent call last):
    File "<string>", line 1333, in <module>
    File "<string>", line 914, in main
  UnboundLocalError: local variable 'restored_uid' referenced before assignment

So it seems that making a new backup doesn't help. Do I need to start over with the restore -- delete from the destination account what has already been restored to it?

**Comment by Huby1** [comment]
Hi, 
I have the same issue. I want to restore from my full backup only specific labels:
I try first to estimate and see if it retrieves the same amount of data that I have identify under gmail:
gyb --email source.email@gmail.com --action estimate --search "label:toto"

Using backup folder GYB-GMail-Backup-source.email@gmail.com
Email: source.email@gmail.com
Messages to estimate:0

In real I have 5 conversations in my gmail account that has this label !!
I have tried many different syntax but always getting the same result... 
Jay, can you help please with that it is quite urgent for me ? 

Many Thanks,

**Comment by volcanicc** [comment]
Hi there, all good backing up old gmail, and , now when restoring to new gmail, its starts working then the following errors pop up...
__________________________
TelstraAA7T8F4S:gyb dg$ python gyb.py --email new@domain.com --action restore --local-folder \GYB-GMail-Backup-source@gmail.com --label-restored “PORTED”

Using backup folder GYB-GMail-Backup-source@gmail.com
using IMAP folder [Gmail]/All Mail
restoring message 1 of 16053 from 2015/8/19/640547985-194683.emlTraceback (most recent call last):
  File "gyb.py", line 1323, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 911, in main
    r, d = imapconn.uid('STORE', restored_uid, '+X-GM-LABELS', labels_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 760, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1070, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 905, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: UID command error: BAD ['Could not parse command']

**Comment by jay0lee** [comment]
IMAP versions are no longer supported, please upgrade to the latest version.
