### ISSUE TITLE
err: 404 when creating a project?

### ISSUE THREAD

**Issue by whatamidoingwrong** [jay0lee/got-your-back#270]
Sorry, this is my first time and perhaps I'm just dumb, but what am I doing wrong here?

OS: Windows 10

Steps:
1. Downloaded gyb-1.36-windows-x86_64
2. Extracted to C:\ (So the files are located in C:\gyb)
3. Ran Command Line
4. Per wiki, typed: `gyb --email [myemailhere]@gmail.com --action estimate`
5. GYB returned: 
ERROR: Please configure a project
To make GYB run you will need to populate the client_secrets.json file. Try
running:
gyb --action create-project --email [myemailhere]@gmail.com
[Errno 2] No such file or directory: 'C:\\gyb\\client_secrets.json'`
6. I ran `gyb --action create-project --email [myemailhere]@gmail.com` and was prompted with the short URL link, I followed the link to my Google Authorization screen, approved the GAM Project, then copied the verification code and pasted that string into the command prompt.
7. GYB then returned: 
Creating project "Got Your Back Project"...
Checking project status...
 enabling API drive.googleapis.com...
 enabling API gmail.googleapis.com...
 enabling API groupsmigration.googleapis.com...
 enabling API vault.googleapis.com...
Creating Service Account
404: b'{\n  "error": {\n    "code": 404,\n    "message": "Service account projects/gyb-project-[aaa]-[aaa]-[aaa]/serviceAccounts/gyb-project-[aaa]-[aaa]-[aaa]@gyb-project-[aaa]-[aaa]-[aaa].iam.gserviceaccount.com does not exist.",\n    "status": "NOT_FOUND"\n  }\n}\n' - b'{\n  "error": {\n    "code": 404,\n    "message": "Service account projects/gyb-project-[aaa]-[aaa]-[aaa]/serviceAccounts/gyb-project-[aaa]-[aaa]-[aaa]@gyb-project-[aaa]-[aaa]-[aaa].iam.gserviceaccount.com does not exist.",\n    "status": "NOT_FOUND"\n  }\n}\n' 
**Note: I replaced the specific letters in the 404 error message with [aaa], as those may be unique to accessing my email account, and I don't want to broadcast that information to everyone.**

There's nothing in the wiki (that I can find?) about first creating a project, nonetheless, following the in-program instructions doesn't work either. 

The only other bit of pertinent information I can think of worth noting is that I'm almost out of space in my Gmail account (~99%), which is why I desire to use this program in the first place.

Please advise.

Thank you,
-whatamidoingwrong

**Comment by ericscampbell** [comment]
minor fyi: it isn't that your account is nearly full.   I'm seeing the exact same steps and the same error on a test account I set up just to try this out.  I'm using Win10.   It is a business account (gsuite basic).  I'll try with a personal and a Mac tomorrow.

**Comment by whatamidoingwrong** [comment]
Thanks for confirming it isn't just me that is getting the error.  Mine is a personal Gmail account.

**Comment by anpanmant** [comment]
I am having the exact same issue. Tried both 1.35 and 1.36 with no luck.

Also, if you go to your Google Cloud Service Platform, it seems each failed attempt also created a project. I had multiple of them. Deleted them all and tried again but still do not work.

**Comment by ericscampbell** [comment]
I can confirm this same issue occurs when using 1.36 on Mac OS X 10.14.

I don't have mfa/2fa turned on for this particular gmail account so that's not it either.

**Comment by jay0lee** [comment]
I'm looking into this. Seems Google made a change on their end that means it takes longer for the service account to exist (and thus be found). Hope to have a fixed version out "soon".

**Comment by jay0lee** [comment]
This is now fixed in 1.37:

https://git.io/gam-releases

**Comment by whatamidoingwrong** [comment]
Thank you!
