### ISSUE TITLE
403: Insufficient Permission

### ISSUE THREAD

**Issue by remram44** [jay0lee/got-your-back#275]
Full steps to reproduce the issue:
1. Run installer `bash install-gyb.sh` (from https://git.io/gyb-install)
2. Follow prompts

Expected outcome (what are you trying to do?):

setup completes with no error

Actual outcome (what errors or bad behavior do you see instead?):

```
Select the actions you wish GYB to be able to perform for remirampin@gmail.com

[ ]  0)  Gmail Backup And Restore - read/write mailbox access
[*]  1)  Gmail Backup Only - read-only mailbox access
[ ]  2)  Gmail Restore Only - write-only mailbox access and label management
[ ]  3)  Gmail Full Access - read/write mailbox access and message purge
[ ]  4)  No Gmail Access

[ ]  5)  Groups Restore - write to G Suite Groups Archive
[ ]  6)  Storage Quota - Drive app config scope used for --action quota

      7)  Continue
7

Go to the following link in your browser:

        https://gyb-shortn.jaylee.us/ufewhp

Enter verification code: 4/***********

403: Insufficient Permission: Request had insufficient authentication scopes. - insufficientPermissions
User authorization failed. Trying again. Say N to skip user authorization.

Do you want to authorize GYB to backup email for remirampin@gmail.com? (yes or no) yes

403: Insufficient Permission: Request had insufficient authentication scopes. - insufficientPermissions
User authorization failed. Trying again. Say N to skip user authorization.
```

**Comment by jay0lee** [comment]
This error is because GYB attempts to verify your authentication was successful by checking your quota but you have that unselected. I'll need to find a way to account for that but for now you can just ignore the error and continue, everything else should work.

**Comment by remram44** [comment]
I don't mind enabling quota access, thanks for the quick reply.

**Comment by jay0lee** [comment]
Let's keep this open so I'm reminded to fix.

**Comment by mcdave1975** [comment]
Hi JayOlee,

Select the actions you wish GYB to be able to perform for remirampin@gmail.com

[ ]  0)  Gmail Backup And Restore - read/write mailbox access
[*]  1)  Gmail Backup Only - read-only mailbox access
[ ]  2)  Gmail Restore Only - write-only mailbox access and label management
[ ]  3)  Gmail Full Access - read/write mailbox access and message purge
[ ]  4)  No Gmail Access

[ ]  5)  Groups Restore - write to G Suite Groups Archive
[ ]  6)  Storage Quota - Drive app config scope used for --action quota

      7)  Continue
7

Go to the following link in your browser:

        https://gyb-shortn.jaylee.us/ufewhp

Enter verification code: 

Where I can find the Verfication code?
