### ISSUE TITLE
Mbox file won't import into new email

### ISSUE THREAD

**Issue by ShawnVahle** [jay0lee/got-your-back#278]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Setup gyb
2. did a backup of new email account (worked correctly I believe as it made the folder and all of the email files that currently reside in new email)
3. Typed in command prompt: gyb --email [hidden]@[domain].com --action restore-mbox --local-folder "C:\localfolder" --label-restored "name"

Expected outcome (what are you trying to do?):
exported all gmail emails from old account. Then downloaded the files from vault onto c drive. want to export files back to a different email address under the same domain.
Actual outcome (what errors or bad behavior do you see instead?):
Got the error:

File "gyb.py", line 1138, in get_db_settings
sqlite3.OperationalError: no such table: settings

Traceback (most recent call last): 
 File "gyb.py", Line 2203, in <module>
 File "gyb.py", line 1572, in main
 File "gyb.py", line 1142, in get_db_settings
(AttributeError: 'OperationalError' object has no attribute 'message'

I've tried to delete backup folder. I've tried to move the location of the mbox file. I've tried to use another computer. I must be missing something.

**Comment by lifers5555** [comment]
Any chance you're trying to import mbox "folders" from Mac Mail? I'm having this exact issue.

**Comment by octavioamu** [comment]
I notice the problem was the folder need to be the "Takeout" with all the data not "Takeout/Mail"
