### ISSUE TITLE
Daily Limit issue

### ISSUE THREAD

**Issue by peddinti** [jay0lee/got-your-back#28]
Hi i am trying to upload mbox emails and having the following issue

Traceback (most recent call last):
  File "gyb.py", line 1323, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 560, in main
    requestOAuthAccess(auth_as, options.debug)
  File "gyb.py", line 204, in requestOAuthAccess
    credentials = oauth2client.tools.run(FLOW, storage, short_url=True, http=http)
  File "/usr/local/google/home/vmk/Downloads/got-your-back-0.29/oauth2client/util.py", line 128, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/google/home/vmk/Downloads/got-your-back-0.29/oauth2client/tools.py", line 169, in run
    url_result = service.url().insert(body={'longUrl': authorize_url}).execute()
  File "/usr/local/google/home/vmk/Downloads/got-your-back-0.29/oauth2client/util.py", line 128, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/google/home/vmk/Downloads/got-your-back-0.29/apiclient/http.py", line 680, in execute
    raise HttpError(resp, content, uri=self.uri)
apiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/urlshortener/v1/url?alt=json returned "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.">

**Comment by JPT62089** [comment]
I'm having a similar issue with backing up emails. Right now I'm resorting to GMail Backup, but it's painfully slow... I have tried enabling URL Shortener in the API console with no luck. My error:

Traceback (most recent call last):
  File "gyb.py", line 1323, in <module>
  File "gyb.py", line 560, in main
  File "gyb.py", line 204, in requestOAuthAccess
  File "oauth2client\util.pyo", line 128, in positional_wrapper
  File "oauth2client\tools.pyo", line 169, in run
  File "oauth2client\util.pyo", line 128, in positional_wrapper
  File "apiclient\http.pyo", line 680, in execute
apiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapi
s.com/urlshortener/v1/url?alt=json returned "Daily Limit for Unauthenticated Use
 Exceeded. Continued use requires signup.">

**Comment by jay0lee** [comment]
Can one of you try 0.30 (released moments ago) and see if it solves the
issue for you?

https://github.com/jay0lee/got-your-back/releases




Jay Lee

**Comment by JPT62089** [comment]
Hi jay0lee, that was one fast response! Thank you for the update, it works perfectly now. Gmail Backup has been running for almost an hour now and only got to 33% and gyb is already over 20%... Love gyb! I dunno what I'd do without it.

**Comment by online** [comment]
Hi @jay0lee, ffter upgrading to version 0.30 I have this error in the console:

```
E:\Backups\GYB (email backups)\GYB>gyb --email myemail@gmail.com --local-folder "e:\Backup
s\GYB (email backups)\GYB\Letters" --action backup

Using backup folder e:\Backups\GYB (email backups)\GYB\Letters
Using folder [Gmail]/&BBIEQQRP- &BD8EPgRHBEIEMA-
GYB needs to examine 330184 messages
GYB already has a backup of 330183 messages
GYB needs to backup 1 messages
backed up 1 of 1 messages

GYB needs to refresh 330183 messages
refreshed 10000 of 330183 messagesTraceback (most recent call last):
  File "gyb.py", line 1323, in <module>
  File "gyb.py", line 795, in main
AttributeError: 'NoneType' object has no attribute 'group'
```

Please help me solve this problem.

**Comment by Ebruddah** [comment]
Thanks... Version 0.30 did the trick. Great tool, glad its being updated regularly.  Keep up the good fight!

**Comment by mjconroy52** [comment]
Hi I am trying to run gyb version .30 and encounter the "Daily Limit" issue.  I have my browser open (tried both Chrome and Iexplorer) and am logged into Gmail.  Gyb executes and then an authorization window opens in Gmail, which I authorize-- and I get a page that fails to open and I get a gyb message
"Your browser has been opened to visit https://goo.gl/P3AY9r" which means nothing to me . I have tried re-running with nobrowser.txt in the GYB directory and get asked for an 'authorization code' (not my Google password, which doesn't work).   

Any suggestions appreciated, thanks.

**Comment by jay0lee** [comment]
This is fixed in newer versions. Please upgrade.
