### ISSUE TITLE
invalid_grant: Bad Request

### ISSUE THREAD

**Issue by polisski** [jay0lee/got-your-back#281]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. run backup 
`gyb --email=********@gmail.com --action=backup --local-folder=/gmail/*********// `

2. got error message 
`ERROR: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')`

3. Account is valid, just checked it,  Previous backup has been taken 07.07.2020

**Comment by mneiger** [comment]
Hi,

Same here with version 1.38.

**Comment by polisski** [comment]
> 
> UPDATE
> My bad, one has to remove the cfg file to renew the token.
Thanks a lot! This helped me too!
