### ISSUE TITLE
Project setup issue 

### ISSUE THREAD

**Issue by nsharpley** [jay0lee/got-your-back#285]
1. Enter "GYB" for "Application name".
2. Leave other fields blank. Click "Save" button.
3. Choose "Other". Enter a desired value for "Name". Click the blue "Create" button.

Cannot find "Other" anywhere.

After clicking SAVE I return to the OAuth Conset Screen.   No "Other".

4. Copy your "client ID" value.

Stuck.

**Comment by rtclarkson** [comment]
Same issue

**Comment by hljames** [comment]
Same!
