### ISSUE TITLE
Too many queries per minute

### ISSUE THREAD

**Issue by quasisphere** [jay0lee/got-your-back#287]
Full steps to reproduce the issue:
1. Try to backup a gmail account.

Expected outcome (what are you trying to do?):

All emails are downloaded.

Actual outcome (what errors or bad behavior do you see instead?):

Some mails are not downloaded (although majority are).
During download there are complaints like the one below about too many queries per minute made:

`<HttpError 403 when requesting https://www.googleapis.com/gmail/v1/users/me/messages/******?format=raw&fields=id%2ClabelIds%2CinternalDate%2Craw&alt=json returned "Quota exceeded for quota metric 'Queries' and limit 'Queries per minute per user' of service 'gmail.googleapis.com' for consumer 'project_number:******'.">`

**Comment by prosilire** [comment]
@quasisphere I got the same thing, so I have limited the batch size to 4 using 
`--batch-size 4`
Instead of 100 in a batch, this significantly slows down the upload such that I'm uploading just fewer than 3000 per minute (that seemed to be the cut-off).
