### ISSUE TITLE
ERROR: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

### ISSUE THREAD

**Issue by tincanfury** [jay0lee/got-your-back#290]
hadn't checked on my crontab run backup, but recently I tried to run manually and noticed,

/opt/bin/gyb --email <>@gmail.com --action backup --local-folder /home/<>/Backup/gyb-<>
ERROR: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')
$ gyb --short-version
1.39

Not sure what I need to do to resolve this issue, but for the time being I can't backup my email anymore.
thanks!

**Comment by Begalov** [comment]
`gyb-1.38-windows-x86_64.zip` last worked in June, today throw error
after update to `gyb-1.39-windows-x86_64.zip` result the same

**Comment by Begalov** [comment]
> You can just delete the .cfg file named after the email address and then reauth.
> 
> Jay

https://groups.google.com/g/got-your-back/c/D-k547AuyBo/m/c_FzpQPjCAAJ

It worked
