### ISSUE TITLE
i686 architecture listed but not supported?

### ISSUE THREAD

**Issue by gtoal** [jay0lee/got-your-back#293]
Although the installer help info says:

` -a      Architecture to install (i686, x86_64, armv7l, aarch64). Default is to detect your arch with "uname -m".
`
when push comes to shove...

```
    case $myarch in
      x86_64) gybfile="linux-x86_64-$useglibc.tar.xz";;
      arm64|aarch64) gybfile="linux-arm64-$useglibc.tar.xz";;
      *)
        echo_red "ERROR: this installer currently only supports x86_64 and aarch64. Looks like you're running on $gybarch. You'll need to try the Python source. Exitin\
g."
        exit
    esac

```
And checking in the api resources there is no i686 version.  Any plans to add that support? (or remove it from the help info).

**Comment by jay0lee** [comment]
No plans to have a 32-bit x86 Linux version, no.
