### ISSUE TITLE
question on labels and on dates

### ISSUE THREAD

**Issue by caspertone2003** [jay0lee/got-your-back#297]
Is there any way to just bakcup labels and restore labels, no email down/up?

Are restored emails receiving their original receive timestamp or do they receive the date of restore?

Thanks!

**Comment by Chaity411** [comment]
#296

**Comment by caspertone2003** [comment]
Hello,
is there any reason why my simple question is just closed without answer?
#296 does not address my question.

**Comment by jay0lee** [comment]
Because your simple post was filed as a bug. Read the guidelines and post
questions to the discussion group.
