### ISSUE TITLE
Setup problem with Google

### ISSUE THREAD

**Issue by skydaver** [jay0lee/got-your-back#301]
I've done an install today, so I'm nearly certain I have the correct release.

I'm copy/pasting the instructions directly from the Wiki, and from the command prompts in Terminal (MacOS, 11.1)
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

I'm stuck in the authorization with Google. I do not know what to do, since the instructions in the script do not match what happens when I create the project. I'm quite ignorant of this part of Google, and have probably selected the wrong options.

After I create credentials (and I'm guessing that might be part of what is wrong) and try to specify the actions I want done for my email account, I get the following error message:
Error 403: access_denied
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer (my gmail address.).
Learn more
Request Details
access_type=offline
login_hint=myemailaddress.
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
state=l0FN9uEDBMpDmY8SUaLJen0JvQqM06
code_challenge_method=S256
prompt=consent
client_id=1083763507479-pkeerpkembpv2m7684j7mlv3is61rrur
code_challenge=nKOgAN7vcVbZjwV5N7dO8uBsYm7_SzNAi5z8neN5Hbk
scope=https://www.googleapis.com/auth/userinfo.email https://mail.google.com/ https://www.googleapis.com/auth/apps.groups.migration https://www.googleapis.com/auth/drive.appdata openid

Hand holding gratefully received.

**Comment by nitz** [comment]
Hi @skydaver. You want to add your google account as a test user to the API Project you set up:

![image](https://user-images.githubusercontent.com/602691/106187637-e2415d80-6173-11eb-9117-74f2fc5ba853.png)

**Comment by wsolorza** [comment]
How do I fix this?

https://a.cl.ly/8LukOAYK

https://a.cl.ly/YEuX9247

**Comment by nitz** [comment]
Take your "app" out of production back to testing.

**Comment by skydaver** [comment]
Just tickling this to freshen it up. Life has been hectic, and I haven't had a chance to retry. With luck, this month will be better
