### ISSUE TITLE
Missing builds for 1.41 - installer fails.

### ISSUE THREAD

**Issue by elliotnev27** [jay0lee/got-your-back#305]
I've attempted to install on a Macbook Air M1 (11.2) with `bash <(curl -s -S -L https://git.io/gyb-install)` and running `install-gyb.sh` both will give me the same output.

> You are running MacOS 11.2
> 
> Checking GitHub URL https://api.github.com/repos/jay0lee/got-your-back/releases for latest GYB release (unauthenticated)...
> 
> Getting file and download URL...
> 
> ERROR: Attribute: browser_download_url for macos-x86_64.tar.xz version latest not found

It looks like only the source code was put in release and not the various builds the installers depend on.

**Comment by jay0lee** [comment]
strange, not sure how that happened. Try now.

**Comment by elliotnev27** [comment]
Resolved :)
