### ISSUE TITLE
Error 400 using version 1.41

### ISSUE THREAD

**Issue by taesu99** [jay0lee/got-your-back#306]
Full steps to reproduce the issue:
1. create project

Expected outcome (what are you trying to do?):
Create project to initiate backup
Actual outcome (what errors or bad behavior do you see instead?):Creating project "Got Your Back Project"...
Checking project status...
 enabling API drive.googleapis.com...
 enabling API gmail.googleapis.com...
 enabling API groupsmigration.googleapis.com...
 enabling API iap.googleapis.com...
 enabling API vault.googleapis.com...
Creating Service Account
Setting project consent screen...

400: b'{\n  "error": {\n    "code": 400,\n    "message": "Request contains an invalid argument.",\n    "status": "INVALID_ARGUMENT"\n  }\n}\n' - 400

**Comment by jay0lee** [comment]
I've just released GYB 1.42 which should fix this issue. Can you upgrade and confirm?

**Comment by taesu99** [comment]
Thank you it worked.
