### ISSUE TITLE
import external mbox files (protonmail) via GYB to gmail

### ISSUE THREAD

**Issue by pvanderhoeven** [jay0lee/got-your-back#312]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. export protonmail mailbox to mbox via protonmail-importer / exporter app
2. setup GYB as described 
3. gyb --email my@email.com --action restore-mbox --local-folder "C:\Users\xxx\yyy"

Expected outcome (what are you trying to do?):

import external mbox folders into gmail

Actual outcome (what errors or bad behavior do you see instead?):

gyb --email my@email.com --action restore-mbox --local-folder "C:\Users\xxx\yy"
Traceback (most recent call last):0%
  File "gyb.py", line 2286, in <module>
  File "gyb.py", line 1986, in main
  File "gyb.py", line 1408, in restored_message
sqlite3.IntegrityError: datatype mismatch
[13208] Failed to execute script gyb

**Comment by jay0lee** [comment]
I have no access to protomail so I'd need a sample export that can reproduce this issue.
