### ISSUE TITLE
Restore is very slow compared to backup (Cloud console)

### ISSUE THREAD

**Issue by furby** [jay0lee/got-your-back#314]
Full steps to reproduce the issue:

1. `gyb --email user.account@domain.com --service-account --action backup`

2. `gyb --email group.@domain.com--action restore-group --local-folder GYB-GMail-Backup-backedupuser@imaginecurve.com --use-admin admin.email.@domain.com`

Expected outcome (what are you trying to do?):

The backup to group from a local (Google Cloud Shell) should not take a whole day

Actual outcome (what errors or bad behavior do you see instead?):

The backup took a minute or  2 to get (30k) emails but the restore takes many hours. It's on the Google Cloud Shell so I would assume there's not network speed limit. 
What is great is that it in incremental though so I can take a couple of days to do it.

Just seems oddly slow or is that what should be expected?

**Comment by jay0lee** [comment]
Have you tested this with GYB 1.50?

In general, yes, writing (restore) is slower than reading (backup)?

**Comment by furby** [comment]
Sorry, I should have said, I'm using 1.42. Let me upgrade and see if that makes it better

**Comment by furby** [comment]
No, it's still really slow. Maybe even a little slower...
If that's just the way it handles the restore then I can just do it over a couple of days. As I say the incremental feature is great 👍 
Thanks for the quick reply and the tool

**Comment by jay0lee** [comment]
Yep, this is really just a function of Google's API performance. Writing data to Gmail / Groups is just slower than reading it.
