### ISSUE TITLE
Installation results in "ERROR: Attribute: browser_download_url for macos-x86_64.tar.xz version latest not found"

### ISSUE THREAD

**Issue by moret** [jay0lee/got-your-back#315]
Hi! I tried to install GYB as described on the Wiki and on README, but got the following error message:
```sh
~$ bash <(curl -s -S -L https://git.io/gyb-install)
You are running MacOS 11.2.3

Checking GitHub URL https://api.github.com/repos/jay0lee/got-your-back/releases for latest GYB release (unauthenticated)...

Getting file and download URL...

ERROR: Attribute: browser_download_url for macos-x86_64.tar.xz version latest not found
```

### Full steps to reproduce the issue:
1. Run `bash <(curl -s -S -L https://git.io/gyb-install)`

### Expected outcome (what are you trying to do?):
GYB installed.

### Actual outcome (what errors or bad behavior do you see instead?):
Error message about a tarball not found.

**Comment by oduvan** [comment]
same issue here macOS Big Sur 11.2

**Comment by jay0lee** [comment]
This should be fixed now. Can you try again?
