### ISSUE TITLE
Label causing import error

### ISSUE THREAD

**Issue by eakkas** [jay0lee/got-your-back#316]
I am importing a large (500K+ messages) mbox to Gmail. The process started fine, imported a few thousand messages and got interrupted with the following message:

```
Creating label Muted
400: Invalid label name - invalidArgument
```

When I re-run the command, it exits with the same message. I guess "Muted" causes a conflict. I'd be okay skipping importing the messages with the label "Muted" but I don't think that's an option. I would appreciate the groups input on how I can resolve this issue.

**Comment by jay0lee** [comment]
Can you try running the restore with the additional argument of:
```
--extra-reserved-labels muted
```
this tells GYB to treat Muted as a reserved label it should not try to create. Instead it will be created as `_Muted`.

**Comment by eakkas** [comment]
Thanks. I ended up doing --strip-labels. I may redo the whole thing and try your suggestion.
