### ISSUE TITLE
ERROR: 400: Request contains an invalid argument.. Skipping message restore.

### ISSUE THREAD

**Issue by ilium007** [jay0lee/got-your-back#317]
```
❯ ./gyb --version                                                                                                                                                           52%   LIBERTY_AC 702 Mbps
Got Your Back 1.50
https://git.io/gyb
Jay Lee - jay0lee@gmail.com
Python 3.9.4 64-bit final
google-api-client 2.2.0
macOS-10.15.7-x86_64-i386-64bit x86_64
Path: /Users/xxxx/support/gyb_personal/gyb
OpenSSL 1.1.1k  25 Mar 2021
www.googleapis.com connects using TLSv1.3 TLS_AES_256_GCM_SHA384
```

I run this command:
`❯ ./gyb --email xxxx@gmail.com --local-folder /Users/xxxx/support/gyb_xxxxx@xxxxx.com.au --action restore --label-restored restored`

I get this error:
`ERROR: 400: Request contains an invalid argument.. Skipping message restore.`

I seems this same issue may have been reported before and fixed in 1.4.1

**Comment by jay0lee** [comment]
The error indicates Gmail server did not like the message, it could be malformed or contain a virus, the server does not specify but there's really nothing GYB can do here except report the error and move on to the next email. This is working as intended. If it's just one or a handful of messages I'd suggest just ignoring it. Otherwise you'll need to investigate what's unique and problematic with that email.

Jay

**Comment by ilium007** [comment]
Ok thanks. No viruses here :D but I'll just ignore it.

**Comment by ilium007** [comment]
How do I identify the email in question? I can't find anything in the --debug output to identify the actual email.

**Comment by jay0lee** [comment]
--debug output of a rerun should show the raw message. It's base64 encoded
so you'll need to run it through a decoder (there's plenty of them online
if you Google it).

Jay

**Comment by ilium007** [comment]
Ahh ok - I was hoping there was a simple reference back to the local .eml file it used to attempt the restore.

**Comment by ilium007** [comment]
So.... I decoded the base64 text and I remember the email. It was one that contained an AES encrypted attachment that contained a website SSL **private** key that I had to send to an overseas partner. It really urks me that Google will not allow us to **securely** send sensitive attachments that have been encrypted because they can't look inside them.

Not a GYB problem I know.
