### ISSUE TITLE
Trojan detected on msi x64 installer 1.50

### ISSUE THREAD

**Issue by logicafuzzy** [jay0lee/got-your-back#318]
Trojan:Win32/Zpevdo.B detected by Windows Virus&Threat protection
  
![image](https://user-images.githubusercontent.com/1773484/118772653-48b5cd00-b884-11eb-9f6b-df6fb7aa2b7d.png)

Full steps to reproduce the issue:
1. Download version 1.50 .msi or .zip x64 [release](https://github.com/jay0lee/got-your-back/releases)
2. Wait for antivirus or Windows V&T protection to trigger

Expected outcome (what are you trying to do?): no trojans :)

Actual outcome (what errors or bad behavior do you see instead?): Trojan:Win32/Zpevdo.B detected

Note: no trojan detected in x86 versions and for versions <=1.42

**Comment by logicafuzzy** [comment]
Could likely be a false positive, if no one else is having the same issue

**Comment by seedeewhy** [comment]
Experienced this too when trying to download gyb-1.50-windows-x86_64.zip.
![image](https://user-images.githubusercontent.com/60246768/118793791-84c05080-b8cb-11eb-857c-0575ea071883.png)

**Comment by seedeewhy** [comment]
32bit version works fine though. Is it really a false positive?

**Comment by HubHugGit** [comment]
Avira anti virus detected the characteristics of a trojan in gyb.exe  from gyb-1.50-windows-x86.zip

**Comment by b0park** [comment]
Microsoft ATP also doesn't like it, Virustotal isn't a fan either. https://www.virustotal.com/gui/file/28768d79a038c6975100b6951a623bfe0dcf9c6db2f44d1e30789f70f1414274/detection

**Comment by jay0lee** [comment]
I have zero ability to prevent these false positives across vendors. Please
report this as a false positive to your AV vendor.

Jay Lee

**Comment by wazimshizm** [comment]
![image](https://user-images.githubusercontent.com/22341034/121771771-d00d0c80-cbb4-11eb-9f23-9790930ba862.png)

Same issue, suddenly gyb commands don't work, tried to redownload & chrome won't let it.

Windows defender + no 3rd party antivirus.

**Comment by Flippertie** [comment]
I'm getting this on a clean windows install, with just windows defender, no 3rd part antivirus. 
64 bit versions (MSI and zip) blocked as virus. Installed cleanly using the gyb-1.50-windows-x86.msi

**Comment by jay0lee** [comment]
This is antivirus vendors being overly aggressive and detecting all compiled Python executables as a virus. I added some changes in 1.52 that should hopefully mitigate the issue but the problem is how AV vendors decide a file is malicious, not GYB.
