### ISSUE TITLE
Restore errors

### ISSUE THREAD

**Issue by bryantech** [jay0lee/got-your-back#319]
I am trying restore and I am getting this error.

Using backup folder H:\accounts\patrick@stand
Traceback (most recent call last):
  File "gyb.py", line 1141, in get_db_settings
sqlite3.OperationalError: no such table: settings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyb.py", line 2206, in <module>
  File "gyb.py", line 1575, in main
  File "gyb.py", line 1145, in get_db_settings
AttributeError: 'OperationalError' object has no attribute 'message'
[10160] Failed to execute script gyb

Windows 7 Pro

GYB version used for backup 1.39

Gyb version used for restore 1.39

Gyb 1.50 throws a python error so I can't use it.

**Comment by bryantech** [comment]
Source: Workspace account. I don't have admni rights to the account.

Destination Workspace account I have admin rights on the new account.

**Comment by bryantech** [comment]
anyone?

**Comment by jay0lee** [comment]
Please upgrade to the latest version of GYB. Note that Windows 7 is obsolete and no longer supported by Python. You'll need to upgrade.
