### ISSUE TITLE
Feature request: inverse order for populating Groups

### ISSUE THREAD

**Issue by meksone** [jay0lee/got-your-back#32]
Hi, I've been using GYB many times, mainly for small backup/restore operations on Google Apps accounts and groups.
I've noticed that when restoring e-mail to groups, the order of the messages is determined by the upload time and not by the message date header.
Is possible to add a switch in restore-group option to make GYB use inverse order (from older to newer messages), so the message order in group remain correct (newer messages on top, older on bottom)?

Many thanks!

**Comment by jay0lee** [comment]
I wasn't able to reproduce this behavior. Closing this issue but feel free to re-open with more details about the issue (and using the latest GYB release which is currently 0.44).
