### ISSUE TITLE
Installation under CentOS

### ISSUE THREAD

**Issue by tothand** [jay0lee/got-your-back#33]
Hi,

I've tried to use GYB on a CentOS 6.6 and encountered some errors. I thought I share my solutions maybe someone will benefit from them.

Error:
`'module' object has no attribute 'SignedJwtAssertionCredentials'`

Solution:
You have to install pyOpenSSL and python-crypto2.6 (I'm using python 2.6)

The pyOpenSSL rpm prvovided by CentOS base repo is currently v0.10 which is not enough
because then it will produce another similar error:
`'module' object has no attribute 'sign'`

So you have to install a more recent version. I've used pip to install like this:
`yum install python-pip`

You'll need to install
`yum install python-devel openssl-devel libffi-devel`

Then
`pip install pyopenssl`

And now it's working like a charm.

Happy backup :)

**Comment by bripsch** [comment]
Tothand -

I have gotten the same error when trying to use GYB for Google apps for education, and was interested in trying your fix.  Unfortunately, I'm a little lost when trying to follow your directions.  Could you post a more noob-friendly guide to your fix?

Thanks for your time,
B

**Comment by tothand** [comment]
Hi,

If you run the 3 commands:
```
yum install python-pip
yum install python-devel openssl-devel libffi-devel
pip install pyopenssl
```

It should fix the issue. There are different possibilities why it doesn't work
for you e.g. if you already have the modules installed but they are the wrong
versions.

It's hard to tell. Where did you get lost. What you have managed so far and
what is the current error?

T

**Comment by bripsch** [comment]
I think the main issue is that I am running this on osx and not Linux.  I can try this all on a CentOS machine but I do not have access to one currently.  I tried to do brew installs of these but it did not work.  Any thoughts?  I know osx is a different world

**Comment by tothand** [comment]
Well, unfortunately I have no idea about this on OSX.
My logic says:
- check if python is working correctly (check python version too, it is possible to have multiple python version installed and maybe the proper openssl lib is only installed in one but the system using the other by default)
- check if pyopenssl is installed (start a python interactive shell and try ```from OpenSSL import crypto```). About checking its version...I guess you can find the installed libraries somewhere (e.g.: ```/System/Library/Frameworks/Python.framework``` )

Maybe someone with a "python on OSX"  background can help you better than this.

**Comment by bripsch** [comment]
Good news!  after trying what you said plus like 10 other things, I finally thought to just uninstall Python 2 and let it default to Python 3, and it worked!  So that's cool.  Thanks for responding with your efforts!

**Comment by tothand** [comment]
Cool. Glad if something what I said helped you to find the right solution :)
