### ISSUE TITLE
Problem Setting up GYB Service Account

### ISSUE THREAD

**Issue by jeff-bernier** [jay0lee/got-your-back#34]
I am trying to setup a service account to use with GYB, and the instructions point me to enable the "Groups Migration API", but the API listing has changed completely in the Google Developers Console. I do not see this API listed.

Which API should I enable? I have this setup for another Google Apps for Education domain whe that API appeared in the old listing in the Dev Console.
The Google Apps APIs I can choose from are:
Drive API
Drive SDK
Calendar API
Gmail API
Google Apps Marketplace SDK
Admin SDK
Contacts API
CalDAV API

Any ideas?

**Comment by Duleepa** [comment]
Hi, all you have to do is "search" for the Groups Migration API. Basically Google no longer lists them all.

**Comment by daniejstriata** [comment]
When I look at the API's for my service account. I'm sure most of them is not needed and on by default.

Admin SDK
BigQuery API	
Google Cloud SQL	
Google Cloud Storage	
Google Cloud Storage JSON API	
Groups Migration API
