### ISSUE TITLE
One VirusTotal vendor flagging Windows installer as malicious

### ISSUE THREAD

**Issue by bartolialberto** [jay0lee/got-your-back#341]
I have downloaded gyb-1.53-windows-x86_64.msi and submitted to VirusTotal.

Zillya flagged this file as malicious (see attachment)

![image](https://user-images.githubusercontent.com/83402622/150118662-47fd4566-5bd7-4d1f-a40e-f49ed0e6fc66.png)

**Comment by jay0lee** [comment]
This should be reported to the AV vendor as a false positive. There's nothing I can do on my end to direct their mistake. Unfortunately this is extremely common for them.
