### ISSUE TITLE
Add a way to strip headers or HTML or both

### ISSUE THREAD

**Issue by bmintz** [jay0lee/got-your-back#35]
## My predicament

Currently I'm using GYB to download messages that match a certain search query, such as:
```bash
gyb --email example@example.com.gmail.com --action backup --search \
'((from:email1@example.com||from:email2@example.com)||(to:email1@example.com||from:email2@example.com))' \ 
 --local-folder GYB-markov'
```

When creating [continuous-time Markov chains](http://en.wikipedia.org/wiki/Continuous-time_Markov_chain) using a Gmail search query, most headers and all HTML tags are very undesirable. If I don't strip all of the mail-headers and HTML tags **first**, I'd end up with sentences like:
`The quick brown fox jumped over my crappy --Content-type=UTF-8.` or,
`X-SPF-Verdict is my favorite kind of soup.`

Anyway, I propose one command line option:
---

### --strip <none|html|headers|all>
When using the `--backup` option, remove some content from the message after it's been backed-up.
If `--format` is missing, `--format strip-none` is implied.

#### none
Do not remove any HTML tags, message headers, or anything.

#### html
Only removes HTML tags from messages after backup. Nothing else.

#### all
Strip _absolutely everything_. This includes **all** headers, and **all** HTML tags.

## Notes
* This might involve adding a dependency upon [BeautifulSoup](http://www.crummy.com/software/BeautifulSoup/) or something.
* --strip all is the implied default.
Actually implementing this may be done by either "stripping first, saving later," or "save first, strip in place." My _guess_ (just a hunch), is that the latter would be more secure and require less memory.

## P.S.
I _*really*_ love this project. Thanks for all you do!! :heart:.

**Comment by jay0lee** [comment]
GYB is a backup/restore tool. It's not really focused on local modification of the backed up messages. Closing this as it's not something the project can support.
