### ISSUE TITLE
GYB gmail access failed after Google no longer supports OAuth 1.0

### ISSUE THREAD

**Issue by lichen98** [jay0lee/got-your-back#36]
Dear Developer,

GYB has been my go to tool for backing up and migrating Gmail accounts. It has worked wonderfully. Thank you!

GYB recently stopped working (last automatic backup completed was on May 5). When it runs, GYB could not gain access (access was granted before when automatic backup was setup):
![image](https://cloud.githubusercontent.com/assets/3083635/7656229/234adafc-fade-11e4-9dae-87db1b5da00a.png)

When GYB tries to open a browser page for user to grant GYB access to gmail, this page opens up:
https://support.google.com/a/answer/6224347?p=oauth&rd=1

It looks like Google has changed the authentication process from OAuth 1.0 to OAuth 2.0 (Why do these big companies always break things that work!?).

Could this be fixed soon?

Thanks so much for such a wonderful tool. I hope it could continue to benefit users.

Best regards,
lichen98

**Comment by jay0lee** [comment]
GYB 0.30 uses OAuth 2.0 which is supported. Please make sure you've updated and are using the most recent version.
