### ISSUE TITLE
Broken pipe on restore with gyb HEAD

### ISSUE THREAD

**Issue by bkix** [jay0lee/got-your-back#37]
Hi,

following error occures with an mbox-file that i try to push back to google. Seems there is "something" in there gyb or google don't like. Filesize maybe? This is an mbox-file from Google Vault, so I wonder why this seems to be incompatible in some way.

Is there a way how I can manually edit the mbox-file to get past this error?
If this is an error with one message, how about an option to drop this single message from recovery?

> imaplib.abort error:socket error: [Errno 32] Broken pipe, retrying...
>  35:00.37 > OEFJ1 AUTHENTICATE XOAUTH2
  35:00.42 < + 
  35:00.42 write literal size 160
  35:00.75 < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT
  35:00.75 < OEFJ1 OK XXXXX@YYYYY.de authenticated (Success)
  35:00.75 > OEFJ2 CAPABILITY
  35:00.90 < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT
  35:00.90 < OEFJ2 OK Success
  35:00.90 > OEFJ3 ID ("name" "Got Your Back: Gmail Backup" "version" "0.30" "vendor" "Jay Lee" "contact" "jay0lee@gmail.com")
  35:01.05 < * ID ("name" "GImap" "vendor" "Google, Inc." "support-url" "http://support.google.com/mail" "version" "gmail_imap_150512.06_p1" "remote-host" "94.198.xxx.xxx")
  35:01.05 < OEFJ3 OK Success
  35:01.05 > OEFJ4 SELECT "[Gmail]/Alle Nachrichten"
  35:02.19 < * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $Phishing $NotPhishing)
  35:02.19 < * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $Phishing $NotPhishing \*)] Flags permitted.
  35:02.19 < * OK [UIDVALIDITY 11] UIDs valid.
  35:02.19 < * 109343 EXISTS
  35:02.19 < * 0 RECENT
  35:02.19 < * OK [UIDNEXT 132575] Predicted next UID.
  35:02.19 < * OK [HIGHESTMODSEQ 2349217]
  35:02.19 < OEFJ4 OK [READ-WRITE] [Gmail]/Alle Nachrichten selected. (Success)
  35:02.26 > OEFJ5 APPEND "[Gmail]/Alle Nachrichten" (\Seen) "12-Dec-2014 12:06:07 +0100" {5101070}
  35:02.41 < + go ahead
  35:02.41 write literal size 5101070

Regards
Ben

**Comment by jay0lee** [comment]
IMAP version is no longer supported, please upgrade to latest release.
