### ISSUE TITLE
Fails to restore MBOX file

### ISSUE THREAD

**Issue by jpstormcrow** [jay0lee/got-your-back#39]
The restore ran for quite some time then it died. Now everytime I go to run it I am getting the same error.

Here is the error with debug

![5-29-2015 11-50-16 am](https://cloud.githubusercontent.com/assets/12661835/7886568/e4982b22-05f8-11e5-9564-ca679263a6da.png)

**Comment by goyalvishal4** [comment]
Remove all whitespaces from your label names. This resolved same error in my case.
