### ISSUE TITLE
A way to do batch archiving (all users) with the service-account option?

### ISSUE THREAD

**Issue by bripsch** [jay0lee/got-your-back#43]
I'm using the service-account command with google apps for education, and currently have to backup one email at a time.  Is there a way to batch process these so I can just set it up and let it go?

**Comment by daniejstriata** [comment]
I would generate a list of users using GAM and then use that list to create a script to read the GAM list and import and run repeatedly for each user in GYB.

**Comment by bripsch** [comment]
I solved this with this code:

for email in [email1] [email2] [email3] do gyb email $email --service-account 1234567@developer.gserviceaccount.com

It will run for all the the emails in that string, one at a time.

Hope this helps!
