### ISSUE TITLE
backup with --search and default labels renamed after restor !!

### ISSUE THREAD

**Issue by Huby1** [jay0lee/got-your-back#46]
Hi All, 

From GYB 0.31 under Windows 7, the backup from search return inconsistent response, even not close to what exist. So I decided to test the Linux version under Ubuntu 14.04.02 LTS and surprise the backup with search and restore works like a charm ! I guess there is something with the Python version on the Windows release..?
BUT !! nothing is smooth at least for me .. after restoring a full version (from GMail/All Mail) I was very surprise to find that the basic labels (Inbox, Draft, etc.) stay empty and that new labels instead are created and use as the default system folders, they look like: "\\Inbox", "\Draft" etc...
I even cannot move the mails manually from there to the original Inbox !! 
I don't know if Google has again changed something but I would be very happy if someone could help..  

Many Thanks,
Jo

**Comment by BradGraham** [comment]
I'm seeing the same issue.  Some of the labels restore correctly, other restore with "label/sublabel" (including the quotes).

I'm using:

Got Your Back 0.29
Jay Lee - jay0lee@gmail.com
Python 2.7.8 64-bit final
Windows-2008ServerR2-6.1.7601-SP1 AMD64

**Comment by Huby1** [comment]
This is really wiered ! have you identify since when you have the issue ? for my side it is 2 days ago, but it was also the first time I use the linux version. obviously on windows version 0.31 64-bits doesn't show this issue for me.

Linux version I use: 
Got Your Back 0.31
Jay Lee - jay0lee@gmail.com
Python 2.7.6 64-bit final
Linux-3.16.0-45-generic-x86_64-with-Ubuntu-14.04-trusty x86_64


Windows version I use at the other side:
Got Your Back 0.31
Jay Lee - jay0lee@gmail.com
Python 2.7.10 64-bit final
Windows-7-6.1.7601-SP1 AMD64

**Comment by jay0lee** [comment]
IMAP versions are no longer supported. Please upgrade to latest release.

**Comment by Huby1** [comment]
Hi Jay,

Thanks for replying.
Iam not sure how to uograde to latest version of Imap .. can you give us some more tip to do it ?

Many Thanks,
