### ISSUE TITLE
GYB not creating backup folder or files. No error.

### ISSUE THREAD

**Issue by captainrva** [jay0lee/got-your-back#47]
I followed the Wiki and everything looks like it works but the folder is empty. I tried with the defaults so GYB would make it's own folder but it doesn't exist after doing it that way either. Windows 7 64bit. Bellow is the message I get that makes me think it worked but it doesn't. Any help would be great.

---------------------------------------------------------------
Using backup folder C:\gmailbackups\scott
Using folder [Gmail]/All Mail
GYB needs to examine 702 messages
GYB already has a backup of 0 messages
GYB needs to backup 702 messages
backed up 702 of 702 messages

GYB needs to refresh 0 messages

C:\gyb-64>
-------------------------------------------------------------

After running it the 2nd time I get this:

-------------------------------------------------------------
Using backup folder C:\gmailbackups\scott
Using folder [Gmail]/All Mail
GYB needs to examine 702 messages
GYB already has a backup of 702 messages
GYB needs to backup 0 messages

GYB needs to refresh 702 messages
refreshed 702 of 702 messages
----------------------------------------------------------------

But the folder is still empty,

**Comment by jay0lee** [comment]
You are using an old version. Upgrade to latest release and try again with a fresh directory.
