### ISSUE TITLE
Whitespaces in labels throwing error.

### ISSUE THREAD

**Issue by goyalvishal4** [jay0lee/got-your-back#48]
Dear gyb Team
Whitespaces in labels throwing undiscripted error.
Kindly adjust code to allow labels with whitespaces too, if feasible. or at least add proper error description, so that users can easily understand fix the error.

**Comment by jay0lee** [comment]
This should not be occurring on GYB 0.43 and newer. If you're still seeing this issue, please re-open and provide full output details.
