### ISSUE TITLE
Server responded with NO ['System Error (Failure)']

### ISSUE THREAD

**Issue by JPT62089** [jay0lee/got-your-back#50]
Hello jay0lee,

I'm having an issue with using gyb. Whenever I backup email from a users account it works successfully for some time. It will eventually be unable to continue. I tried deleting the backup folder and start it over but it always stops at around the same point. I tried service account and logging into the account to back up and neither one worked successfully. It seems like it stops after 10k-13k emails.

Here's the log:

Using backup folder GYB-GMail-Backup-username@domain.com
Using folder [Gmail]/All Mail
GYB needs to examine 16304 messages
GYB already has a backup of 0 messages
GYB needs to backup 16304 messages
backed up 10500 of 16304 messages
Server responded with NO ['System Error (Failure)'], will retry in 2.0 secondbacked up 11200 of 16304 messages
Server responded with NO ['System Error (Failure)'], will retry in 2.0 seconds
Server responded with NO ['System Error (Failure)'], will retry in 4.0 seconds
Server responded with NO ['System Error (Failure)'], will retry in 8.0 seconds
Server responded with NO ['System Error (Failure)'], will retry in 16.0 seconds
Server responded with NO ['System Error (Failure)'], will retry in 32.0 seconds
Server responded with NO ['System Error (Failure)'], will retry in 64.0 seconds
Server responded with NO ['System Error (Failure)'], will retry in 128.0 seconds
Error: failed to retrieve messages.
NO ['System Error (Failure)']

**Comment by KrhisthianARG** [comment]
Hello jay0lee,
                           I have the same problem! :(

**Comment by JPT62089** [comment]
So glad it's not just me! That (hopefully) means I didn't blow something up on my end :D

When did this start for you, KrhisthianARG? I only noticed it yesterday after probably a month of not using it.

**Comment by JPT62089** [comment]
The new version (0.41) looks to have fixed the issues. Also good to hear GYB is moving to Gmail API! :smile:

**Comment by KrhisthianARG** [comment]
Hello Jpt62089!
                         excuse me for delay! I'm using the script several months ago. This error only happened to me once. I will try the version 0.41.

Sorry for my English.

Regards
