### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by maltokyo** [jay0lee/got-your-back#53]
When running latest version, I get this error, on both mac and linux (first run on machine).

python gyb.py --email mymail@mymail.com --action estimate
Traceback (most recent call last):
  File "gyb.py", line 60, in <module>
    import httplib2
  File "/Users/me/scripts/got-your-back-master/httplib2/__init__.py", line 352
    print('%s:' % h, end=' ', file=self._fp)
                        ^
SyntaxError: invalid syntax

**Comment by jay0lee** [comment]
GYB 0.40+ uses Python 3.4.

**Comment by maltokyo** [comment]
thanks!
