### ISSUE TITLE
NameError: name 'sqlcur' is not defined

### ISSUE THREAD

**Issue by maltokyo** [jay0lee/got-your-back#54]
Get error:
NameError: name 'sqlcur' is not defined when running "--action estimate" for first time.

=====

Select the actions you wish GYB to be able to perform for XXXXXXX

[ ]  0)  Gmail Backup And Restore - read/write mailbox access
[*]  1)  Gmail Backup Only - read-only mailbox access
[ ]  2)  Gmail Restore Only - write-only mailbox access and label management
[ ]  3)  Gmail Full Access - read/write mailbox access and message purge
[ ]  4)  No Gmail Access

[ ]  5)  Groups Restore - write to Google Apps Groups Archive
[*]  6)  Storage Quota - Drive app config scope used for --action quota

      7)  Continue
7
Go to the following link in your browser:

    https://goo.gl/lFYMGa

Enter verification code: XXXXXXXXX
Authentication successful.
Got 195582 Message IDs                                                          
GYB needs to examine 195582 messages
Traceback (most recent call last):
  File "gyb.py", line 1491, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1454, in main
    if not newDB and message_is_backed_up(message_num['id'], sqlcur,
NameError: name 'sqlcur' is not defined

**Comment by haemi** [comment]
facing the same issue... are there any updates on this?

**Comment by maltokyo** [comment]
Fix for this is here:
https://github.com/jay0lee/got-your-back/issues/59

**Comment by jay0lee** [comment]
this is fixed in master (soon to be 0.44)
