### ISSUE TITLE
Attempting to use --service-account  feature with GYB 0.41

### ISSUE THREAD

**Issue by BradGraham** [jay0lee/got-your-back#55]
After creating a new auth for GYB 0.41 and adding the new service account, I get "gyb.exe: error: unrecognized arguments: [service account....]"

**Comment by JPT62089** [comment]
Same issue here. I'm assuming that the feature isn't quite updated for 0.4x :(

**Comment by bripsch** [comment]
I too am having this issue

**Comment by px-progers** [comment]
Experiencing this issue as well after upgrading to GYB 0.41.

**Comment by px-progers** [comment]
It appears the behavior of the application has changed but the instructions have not yet been updated. This issue can be resolved by doing the following:

- In the Google developers console, generate a new JSON key for your service account (if you don't already have one).
- Place the generated JSON file in the gyb directory, and rename to `oauth2service.json`.
- Re-run your gyb command, but omit the service account email address after the --service-account option. For example: `gyb --email you@gmail.com --local-folder .\backups\you@gmail.com --service-account`

**Comment by gbarreto1972** [comment]
After I did the oauth2service.json file, I'm getting a different error:

Traceback (most recent call last):
  File "<string>", line 1491, in <module>
  File "<string>", line 890, in main
  File "<string>", line 423, in buildGAPIServiceObject
KeyError: 'client_email'

Any clues on how to fix this issue?

**Comment by jay0lee** [comment]
service account should be functional in 0.43.

**Comment by garec** [comment]
Hi is this fixed in current release?  I am getting same error as @gbarreto1972

**Comment by garec** [comment]
Fixed for me.  I recreated my Google service account per the instructions (had old one from .29) and it works.  sorry to bother.
