### ISSUE TITLE
When restoring message: "'str' does not support the buffer interface" (and Conflict with Gmail's System Labels)

### ISSUE THREAD

**Issue by rakochi** [jay0lee/got-your-back#57]
I made some edits to my copy of gyb to get it working, one of which was checking if a user had any system-applied labels (such as "Starred" or "Important") and then removing those from the list of labels being applied to the message, because otherwise it would give me an "HTTP 400 - Invalid label name" error.

I am not sure if maybe my edits have caused an issue but now I get the following error:

Using backup folder /Users/rakochi/Downloads/Takeout_2/Mail

Restoring from /Users/rakochi/Downloads/Takeout_2/Mail/Colloquium.mbox
Important,Colloquium
['Colloquium']
 restoring single large message (1/101)                                         Traceback (most recent call last):
  File "gyb.py", line 1499, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1219, in main
    mimetype='message/rfc822')
  File "/Users/rakochi/got-your-back-0.41/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/rakochi/got-your-back-0.41/googleapiclient/http.py", line 472, in __init__
    fd = BytesIO(body)
TypeError: 'str' does not support the buffer interface

Note that "Colloquium" is the only label that is being applied.  Also, I did not make changes to anything outside of gyb.py either.

**Comment by hrvoojex** [comment]
On a fresh installed Ubuntu 14.04.3 I run:
python3 gyb --email name.surname@address.com

and I got a message:

Traceback (most recent call last):
  File "gyb.py", line 1489, in <module>
    doGYBCheckForUpdates()
  File "gyb.py", line 316, in doGYBCheckForUpdates
    f.write(str(now_time))
TypeError: 'str' does not support the buffer interface

**Comment by dougjuh** [comment]
I found the simplest solution to these errors; it works fine for me.  Edit your gyb.py and search for "open(last_update_check_file" (there are 3 of them).  Change the 'rb' to 'r' or 'wb' to 'w'.  The file it's trying to use is a text file, not a byte file.

**Comment by TJMcK** [comment]
thanks dougjuh, I had this error and editing gyb.py as per your comments worked... but unfortunately I'm now getting a different error: "ValueError: invalid literal for int() with base 10..." :(

**Comment by michaelng** [comment]
I added something in line 298.

```python
if os.path.isfile(last_update_check_file):
    f = open(last_update_check_file, 'r')
    if (f.readline() != ''):
        last_check_time = int(f.readline())
    else:
        last_check_time = 0
    f.close()
```

**Comment by TJMcK** [comment]
After adding above code I get this:
...
Traceback (most recent call last):
  File "gyb.py", line 1496, in <module>
    doGYBCheckForUpdates()
  File "gyb.py", line 290, in doGYBCheckForUpdates
    if os.path.isfile(last_update_check_file):
UnboundLocalError: local variable 'last_update_check_file' referenced before assignment
...

**Comment by jay0lee** [comment]
these should be fixed in latest release.
