### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by nischg** [jay0lee/got-your-back#58]
Probably a newbie error, but when I try to run the tool I get the following back:

    Traceback (most recent call last):
      File "gyb.py", line 60, in <module>
        import httplib2
      File "/home/pi/gyb/httplib2/__init__.py", line 352
        print('%s:' % h, end=' ', file=self._fp)
                        ^
    SyntaxError: invalid syntax

I tried to find some information to no avail. I'm on raspbian wheezy and using the latest release.

**Comment by rakochi** [comment]
Are you running Python 2.x or Python 3?  I am not sure what is the earliest version of Python 3 you can install to get this to run, but I installed the latest version of Python 3 to fix this error.

**Comment by nischg** [comment]
I'm running Python 2, but it seems I'm having some larger issues with Python altogheter, since Flexget isn't working either:

    Traceback (most recent call last):
      File "/usr/local/bin/flexget", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
        working_set.require(__requires__)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: apscheduler

**Comment by maltokyo** [comment]
it wont run on python 2, at least for me, on Linux or Mac

**Comment by winterflags** [comment]
With Python 2.x I get the exact same syntax error when running:
`python gyb.py --email=myadress@gmail.com --action=backup`

With Python3 I get another error:
`python3 gyb.py --email=myadress@gmail.com --action=backup`

`Traceback (most recent call last):
  File "gyb.py", line 61, in <module>
    import oauth2client.client
  File "/got-your-back-0.41/oauth2client/client.py", line 32, in <module>
    import six
ImportError: No module named 'six'`

**Comment by ShrmnK** [comment]
I resolved the issue by copying `six.py` downloaded from https://pypi.python.org/pypi/six/#downloads into the root of the project (alongside `gyb.py`).

**Comment by dougjuh** [comment]
I also installed Python 3 on my Mac and gyp now works.  To install module 'six', I entered:  pip3 install six

To fix the "TypeError: 'str'" errors, see my solution in issue #57.

**Comment by mikezemans** [comment]
Hello - I too got the initial error at the start of this string, then followed everyone's advice to stomp out subsequent bugs...
    *  was running P2 on OSX 10.8.5, so downloaded/installed Python 3
    *  downloaded/installed module 'six'
    *  put a copy of 'six.py' into the root of the project folder (alongside 'gyb.py')

However, I know encounter a new error that I'm hoping the group can help me with.  When I run...

    python3 gyb.py --email MYEMAIL@mydomain.com --action estimate

I now get the error:  
    File "gyb.py", line 1489, in <module>
        doGYBCheckForUpdates()
     File "gyb.py", line 300, in doGYBCheckForUpdates
        last_check_time = int(f.readline())
    ValueError: invalid literal for int() with base 10: b''

Any ideas?

**Comment by jay0lee** [comment]
this should be fixed in master where six.py is included in source builds. 0.44 will include this fix.
