### ISSUE TITLE
ImportError when running action estimate

### ISSUE THREAD

**Issue by bripsch** [jay0lee/got-your-back#64]
I get this error:

File "gyb.py", line 61, in <module>
    import oauth2client.client
  File "GYB/oauth2client/client.py", line 32, in <module>
    import six
ImportError: No module named 'six'

When running the action estimate command for Google authorization.

Any thoughts?

**Comment by kfishster** [comment]
you have to install the "six" module. If you have pip installed, you can run 
'pip3 install six'

**Comment by bripsch** [comment]
Thanks!  That appeared to help.  However, now I am running into a fresh error when I run --action estimate:

Traceback (most recent call last):
  File "gyb.py", line 1489, in <module>
    doGYBCheckForUpdates()
  File "gyb.py", line 300, in doGYBCheckForUpdates
    last_check_time = int(f.readline())
ValueError: invalid literal for int() with base 10: b''

What's going on here?

**Comment by kfishster** [comment]
I've also encountered this. I followed a tutorial that downloaded the 0.41 version of gyb. I downloaded the current repo's zip and used that version of the program, which seemed to work!

**Comment by bripsch** [comment]
I'm already running 0.41, is there anything I need to do to modify it to work correctly? Where is the tutorial that you followed?

**Comment by kfishster** [comment]
Well, I meant to say to delete the 0.41 version and download it from the repository directly!

**Comment by bripsch** [comment]
Thanks again, that worked!  I deleted the one I d/l from the releases page, and just got the master .zip

**Comment by daniejstriata** [comment]
I wonder why the version from the zip does not work? I also got mine working by using git.
