### ISSUE TITLE
Win7 --action restore-mbox results in AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by michaelgundlach** [jay0lee/got-your-back#65]
Windows 7 with no Python installed (I do have Cygwin installed with python2 and python3 in it but they shouldn't be related.)

Followed install instructions: Downloaded Windows .zip, unzipped, ran gyb.exe with "estimate" action, authenticated with Google to a new, empty Gmail account.

Then attempted to restore a 9GB Google Takeout MBOX file to the new, empty Gmail account.  The result was

AttributeError: 'str' object has no attribute 'decode'.

See screenshot.

Apologies if this is a known issue!

![screenshot](https://cloud.githubusercontent.com/assets/5141333/9772431/3351515a-570a-11e5-9619-4f86947e302e.png)

**Comment by jamesliew** [comment]
Just wanna share that I faced this error on Mac too. I hope someone can help us on this.

**Comment by tonycolangeli** [comment]
Appears to have started with .40 release. Downloaded .31 and successfully restored MBOX file

Unfortunately I don't know enough python to contribute further.

**Comment by RinaldoB** [comment]
Hi, Im also trying to restore an mbox file. After some tweaks I faced the problem of system labels ("starred" etc) not being able to be restored - the script abprted. @tonycolangeli how did you get around this? does .31 really work with mbox files? I tried without success

**Comment by tikityler** [comment]
![image](https://cloud.githubusercontent.com/assets/15217704/10615023/a8237c8a-771a-11e5-8651-edd1d6601cd9.png)
I get the same error, when I try to use the .31 release I get this instead.
![image](https://cloud.githubusercontent.com/assets/15217704/10615070/fa02fbfc-771a-11e5-8244-fabed4fd4496.png)

**Comment by tonycolangeli** [comment]
tikityler -
You need to remove the sqlite files left by v.41 in the directories with your .mbox. GYB checks the data in those. That's what's throwing the errors in your second screenshot.

**Comment by tikityler** [comment]
Thank you tonycolangeli, that worked perfectly, I could have sworn I had downloaded seperate files to try with the different version to prevent something like that. My bad.
