### ISSUE TITLE
Restore all messages in order, by date?

### ISSUE THREAD

**Issue by winterflags** [jay0lee/got-your-back#68]
I am just done restoring over 70,000 emails to a new account, but I was a bit distraught to see that they aren't restored in order. Instead, it seems like many of the oldest messages are in fact "on top" although there is a high degree of randomness.

Is there anything that can be done to order the copying by date, or to "reverse" the order it copies messages into the new account?

Best regards,
W

**Comment by RinaldoB** [comment]
@winterflags how did you manage to get it to work? which version/os did you use? did you face pproblems with conflicting labels?

**Comment by jay0lee** [comment]
This is not expected behavior. Can you provide more details about what you are seeing? How did you backup these messages? What version were you using?

Please retry with a newer version of GYB (0.44 or later) and if you can reproduce the issue, re-open this ticket with full details.
