### ISSUE TITLE
Group email size limit

### ISSUE THREAD

**Issue by SquareSocket** [jay0lee/got-your-back#7]
I am getting this error while uploading to the group : line 665, in method
    raise MediaUploadSizeError("Media larger than: %s" % maxSize)
apiclient.errors.MediaUploadSizeError: Media larger than: 16777216

I have read on google's group support page : Yes, the maximum size limit for messages sent to a group is 25 MB, including attachments (the normal Gmail limit). (https://support.google.com/a/answer/167085?hl=en) . How can I change this?

**Comment by jay0lee** [comment]
This is a limitation of Google Groups Email Migration API, it's not something GYB can control. Will see about catching this error and continuing to next message though.

**Comment by jay0lee** [comment]
These messages should be skipped over in the latest 0.44 release of GYB. Closing.
