### ISSUE TITLE
Label count over roughly 5K errors out with "409: Label name exists or conflicts - aborted"

### ISSUE THREAD

**Issue by fourjay** [jay0lee/got-your-back#75]
This is probably an API issue, but seems worth reporting.
I'm migrating student mailboxes, some of which are massive (upwards of 30K messages). 
These download fine.
Somewhere around 5K messages uploading can start generating:
"409: Label name exists or conflicts - aborted"
This will kill (what appears to be) every subsequent upload.
I workaround by going into the SQLite db and deleting all labels, at which point Google accepts the remaining messages.

**Comment by jay0lee** [comment]
would need more information on the labels that are causing this. Try running with --debug.
