### ISSUE TITLE
Need help with Error: invalid literal for int()

### ISSUE THREAD

**Issue by mikezemans** [jay0lee/got-your-back#76]
Hello - I initially experienced the error at the start of issue #58, then followed everyone's great advice in that thread to stomp out subsequent bugs I ran into...
* was running P2 on OSX 10.8.5, so downloaded/installed Python 3
* downloaded/installed module 'six'
* put a copy of 'six.py' into the root of the project folder (alongside 'gyb.py')

However, I now encounter a new error that I'm hoping the group can help me with. When I run...

>  python3 gyb.py --email MYEMAIL@mydomain.com --action estimate

I now get the error:

>  File "gyb.py", line 1489, in 
>  doGYBCheckForUpdates()
>  File "gyb.py", line 300, in doGYBCheckForUpdates
>  last_check_time = int(f.readline())
>  ValueError: invalid literal for int() with base 10: b''

Any ideas?

**Comment by cleverless** [comment]
Delete ~/gyb/lastcheck.txt

**Comment by trawick** [comment]
same crash+backtrace here, no file ~/gyb/lastcheck.txt

**Comment by cleverless** [comment]
By ~/gyb/ I mean the project root directory. 
The error you're reporting makes no sense unless it succeeded in finding the file first.

**Comment by nunolf** [comment]
Having the same issue as reported in this thread. After removing the lastcheck.txt I get another error:

'''
[nuno@archy got-your-back-0.41]$ python3 -V
Python 3.5.0

[nuno@archy got-your-back-0.41]$ rm -f lastcheck.txt

[nuno@archy got-your-back-0.41]$ python3 gyb.py --email xxxx@gmail.com --action estimate
Traceback (most recent call last):
  File "gyb.py", line 1489, in <module>
    doGYBCheckForUpdates()
  File "gyb.py", line 316, in doGYBCheckForUpdates
    f.write(str(now_time))
TypeError: a bytes-like object is required, not 'str'
'''

**Comment by michaelng** [comment]
Having the same issue in ubuntu server.

**Comment by andreas-wilm** [comment]
Had the same issue. Problem was that last_update_check_file is opened in binary mode but than text was written unencoded as string. Removing the 'b' from the two open() attempts in gyb.py fixes the issue for me (Anaconda Python 3.5.1 on OS X)

**Comment by MetalWingsWeb** [comment]
I had the same issue and fixed this error with @andreas-wilm suggestion.

**Comment by andreas-wilm** [comment]
Just wanted to issue a pull request when I noticed this was fixed in 559344339c30bf3edb2bf9def89a5b79df1854b9 (version 0.41)

**Comment by MetalWingsWeb** [comment]
@andreas-wilm This is strange, because I've downloaded version 0.41 and had the same problem unfortunately. I dunno if it is because of my OSX configurations. But, it is already fixed.

**Comment by andreas-wilm** [comment]
It's for sure fixed in the mentioned commit (the version number might not have been updated there yet)

**Comment by jay0lee** [comment]
This was fixed in 0.41. 0.42 is the latest:

https://github.com/jay0lee/got-your-back/releases
