### ISSUE TITLE
Very different number of messages in original and backed up account

### ISSUE THREAD

**Issue by Jenn8** [jay0lee/got-your-back#79]
Hi, 

This may not be an issue as such, but I have backed up a work google account to a free gmail account using gyb. The original account has around 8000 messages listed in the inbox, while the backed up account has only 4,000. 

I know that google is not great at counting messages, but that seems a big disparity! Interestingly, the account size is roughly the same. 

Is there any way I can check whether the backup has worked or whether there is actually an issue?
Thanks

**Comment by jay0lee** [comment]
You're probably counting conversations in Gmail, not messages. A conversation can contain many messages. Try turning conversation view off.
