### ISSUE TITLE
Daily Limit issue

### ISSUE THREAD

**Issue by mjconroy52** [jay0lee/got-your-back#80]
Hi I am trying to run gyb version .30 and encounter the "Daily Limit" issue. I have my browser open (tried both Chrome and Iexplorer) and am logged into Gmail. Gyb executes and then an authorization window opens in Gmail, which I authorize-- and I get a page that fails to open and I get a gyb message
"Your browser has been opened to visit https://goo.gl/P3AY9r" which means nothing to me . I have tried re-running with nobrowser.txt in the GYB directory and get asked for an 'authorization code' (not my Google password, which doesn't work).

Any suggestions appreciated, thanks.

PS I had posted this in the thread for this issue (#28) but no responses, so I figured that discussion was closed.  i apologize for any redundancy/ breach of etiquette (I'm new to this and haven't figured out the ropes yet). Thanks.

**Comment by jay0lee** [comment]
This is fixed in newer versions of GYB. Time to upgrade:

https://github.com/jay0lee/got-your-back/releases
