### ISSUE TITLE
updates to dev console / service account procedures

### ISSUE THREAD

**Issue by haroldwong** [jay0lee/got-your-back#81]
Hiya
First of all thank you for all the updates and for creating these useful admin tools.

Since the wiki was updated the procedures for creating and configuring for service account access has changed. When I try to follow the steps as best I can I get stuck at the security > manage API client access. This client name has not been registered with Google yet. 
I would like to request an updated guide for service account portion of the backup
Thank you for all your hard work

**Comment by jay0lee** [comment]
Take a crack at the updated instructions at:

https://github.com/jay0lee/got-your-back/wiki#google-apps-for-work-and-edu-admins-backup-restore-and-estimate-users-and-restore-to-groups

and let me know if you run into any issues.

Jay

**Comment by haroldwong** [comment]
That is exactly what I did and got it to work with windows, I uninstalled my python 2.7 on mac and installed 3 and on that end I am getting weird errors. Before I was getting the six error... I will try to play with it more and if I cant get it to work I will open an issue.
