### ISSUE TITLE
400: Invalid label name - invalidArgument

### ISSUE THREAD

**Issue by apendergrass** [jay0lee/got-your-back#82]
I'm most of the way through restoring my email, and I got this error: 

400: Invalid label name - invalidArgument

Any ideas?

**Comment by jay0lee** [comment]
Did the restore continue or die on that email?

On Sat, Jan 16, 2016 at 11:56 AM apendergrass <notifications@github.com>
wrote:

> I'm most of the way through restoring my email, and I got this error:
>
> 400: Invalid label name - invalidArgument
>
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/got-your-back/issues/82>.
>
-- 

Jay Lee

**Comment by apendergrass** [comment]
It died

**Comment by jay0lee** [comment]
Can you run the command again with:

--debug > label-failure-output.txt

at the end? This will create a file called label-failure-output.txt. Email the file to me, jay0lee@gmail.com (don't attach it here).

Jay

**Comment by jay0lee** [comment]
Thanks for the email. It looks like you had messages with the label "Migrated". While you can create a label named Migrated in the UI, Gmail API doesn't like that name. Can you try grabbing the current master branch of GYB:

https://github.com/jay0lee/got-your-back/archive/master.zip

and see if it fixes the issue for you? The messages should be restored to a label named "Migrated-Restored" to workaround the Gmail label naming limitation.

**Comment by apendergrass** [comment]
Thanks for being so responsive Jay!

Hm, this might be a lame error on my part, but now it doesn't run because I don't have (and can't figure out how to install) OpenSSL.  

ImportError: No module named 'OpenSSL'

I'm on a mac... it looks like pyOpenSSL is a thing I could get... will downloading and installing [OpenSSL](https://www.openssl.org/source/) also work? It's not straightforward to do it seems, but should be possible... 

Thoughts?

**Comment by apendergrass** [comment]
Oh wait! It works if I get pyOpenSSL! Nevermind! 

But it still crashes with the invalidArgument error. 

I can also change the name of the label now that I know what it is, and re-backup and re-restore...

**Comment by apendergrass** [comment]
I did that, and it's now past where it was stuck before (based on the message count).  For future reference, the label name that I changed had actually been "Migrated/archive" so maybe the problem was that the slash got lost in the mix.

**Comment by jay0lee** [comment]
Made some further changes to label creation handling of invalid label names.
