### ISSUE TITLE
Label names being duplicated upon restore (with and without spaces)

### ISSUE THREAD

**Issue by maltokyo** [jay0lee/got-your-back#83]
When restoring to another gmail account, somehow the labels are being duplicated.  One version of labels with the spaces, and another version without spaces.  See attached screenshots.

Orig email account:
![image](https://cloud.githubusercontent.com/assets/1388507/12377343/e96a8f26-bd1a-11e5-9e45-c3f8a4b5f82b.png)

Restored gmail account:
![image](https://cloud.githubusercontent.com/assets/1388507/12377342/d3acdac2-bd1a-11e5-8dd7-51176c6fa2cb.png)

**Comment by jay0lee** [comment]
What version of GYB are you using? Run:

gyb --version

to see. Also, which of the labels are the messages actually being labelled with (if not both?)

**Comment by maltokyo** [comment]
Version:
===============
Got Your Back 0.44
http://git.io/gyb
Jay Lee - jay0lee@gmail.com
Python 3.4.3 64-bit final
Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty x86_64
===============

I messages are being labelled with a new label all together, with the word "restored" concatenated to my labels.  I even tried removing all spaces from labels, and replacing with a hyphen, but this didnt work either, it started to remove the hyphens.. 

![image](https://cloud.githubusercontent.com/assets/1388507/12403138/3a100f74-be32-11e5-9cb7-45d2c0af8366.png)

**Comment by maltokyo** [comment]
Any further info that you would like?  Happy to let you login to the server, where the script is running.  Please let me know.

**Comment by maltokyo** [comment]
This still occurs for me, every time.  Please let me know how I can help you to find the issue.

**Comment by maltokyo** [comment]
Any news, I am happy to help where I can, or leave my server login with you..

**Comment by jay0lee** [comment]
This should be fixed in most recent release (today). You will of course need to remove the bad duplicates manually.

**Comment by maltokyo** [comment]
Thanks!
