### ISSUE TITLE
Chats (Hangouts and Talk) must be fetched with "format": "full"

### ISSUE THREAD

**Issue by agoode** [jay0lee/got-your-back#84]
Hangouts don't have a `raw` representation. But the text can still be fetched with `"format": "full"`. This needs to be handled in a special way if you are defaulting to `raw`.

**Comment by agoode** [comment]
This also applies to older Google Talk messages. The `raw` representation is also truncated. So it seems you want to use `full` for all chat messages.

**Comment by jay0lee** [comment]
Backing up chats and restoring chats via GYB / Gmail API has never worked very well, they can't be restored back to a CHATS label and they usually end up unthreaded if they are restored. Changed GYB to use a default search of "-is:chat" for backup and to NOT backup any messages it sees that have a label of CHATS.
