### ISSUE TITLE
v0.44 reports missing api-ms-win-crt-runtime-I1-1-0.dll at launch and error loading python35.dll

### ISSUE THREAD

**Issue by IT-adventure303** [jay0lee/got-your-back#86]
Thanks jay0lee for working on the recent gyb code updates and providing this useful tool.    

On my Windows 7 Pro 64-bit system, upon launch of gyb.exe v0.44, v0.43, or v0.42 from command line with any action, including simply "gyb --version", a pop-up dialog appears immediately titled 
"gyb.exe - System Error", with only available action "OK", dialog content is 
"The program can't start because
api-ms-win-crt-runtime-I1-1-0.dll is missing from your computer.
Try reinstalling the program to fix this problem. "
upon dismissing dialog, the following line is printed in the command window and then program exits
> Error loading Python DLL: C:\Users\my_username\AppData\Local\Temp\_MEI46922\python35.dll (error code 126)

with "my_username"  above being replaced with my real user name. 

I had been successfully running v0.41 on the same system back on Jan 11 and didn't encounter this missing DLL problem.  I just verified the v0.41 version still starts without this error, but today when I run the older v0.41, I see a notice about new version and then it immediately errors out as follows: 
>N:\gyb-0.41-windows\gyb>gyb --version
>
>There's a new version of GYB!!!
>
>Traceback (most recent call last):
>  File "<string>", line 1489, in <module>
>  File "<string>", line 324, in doGYBCheckForUpdates
>TypeError: must be str, not bytes
>
>N:\gyb-0.41-windows\gyb> 

I'm hoping the new Unicode encoding fix will allow me to continue my migration which stopped about halfway through while using v0.41 (after 1693 messages) with the previously reported 
> UnicodeEncodeError: 'latin-1' codec can't encode characters in position 8418-841
9: ordinal not in range(256)

Let me know if any other specific information would be helpful.

**Comment by svnpenn** [comment]
:+1:

**Comment by jay0lee** [comment]
Can both of you try upgrading to 0.45?

**Comment by svnpenn** [comment]
@jay0lee same on 0.45

**Comment by svnpenn** [comment]
@jay0lee same on 0.45. Also since this is a Windows only program, arent you testing the releases yourself?

**Comment by garec** [comment]
@svnpenn Linux & Mac code available at https://github.com/jay0lee/got-your-back/releases   -- ie it is not a windows only program ... instructions at https://github.com/jay0lee/got-your-back/wiki#step-1-download-gyb

**Comment by svnpenn** [comment]
Why even provide a Windows build if it doesnt even pass a sanity check?

**Comment by IT-adventure303** [comment]
Unfortunately, version 045 gyb.exe for windows generates same missing .dll and exit code 126 under Win 7-64b Pro as found with 042, 0.43, and 0.44 as described in top post. 
![gyberrorcapture-20160228](https://cloud.githubusercontent.com/assets/16812184/13381806/20a97a6a-de22-11e5-8835-66526f86f2cc.JPG)

**Comment by Nann3q** [comment]
I can confirm that this issue is reproduced on my Server2012 R2 Standard 64 Bit, with gyb version 045.

> Error loading Python DLL: C:\Users\oadmin\AppData\Local\Temp\3\_MEI39322\python35.dll (error code 126)

Any ETA for a fix?

**Comment by jay0lee** [comment]
Apparently there is an issue with pyinstaller, Python 3.5.1 and Windows 10 that produces binaries which won't run on some older versions of Windows. See:

https://github.com/pyinstaller/pyinstaller/issues/1566

I've recompiled 0.45 on an older version of Windows and pushed it here. No changes to GYB, just recompiled on older version of Windows:

https://github.com/jay0lee/got-your-back/releases/tag/v0.45

Can someone test 0.45a and confirm it works (where the previous 0.45 windows release did not)?

**Comment by Nann3q** [comment]
Thanks Jay0lee, I can confirm the recompiled v0.45  works fine now on the same Server2012 R2 machine where I had the problem before.

\m/
