### ISSUE TITLE
Handling Labels with Forward Slashes

### ISSUE THREAD

**Issue by willpolley** [jay0lee/got-your-back#87]
These were all single labels which were restored as nested labels. They used the date format:
* 2015 Registrations
 * 2/8
 * 3/1
 * 3/22
 * etc

![screenshot-2016-01-25-13 38 58](https://cloud.githubusercontent.com/assets/859997/12560555/66b0e1de-c369-11e5-97da-17e89a161158.png)

**Comment by nrw** [comment]
i'm encountering this, too. anyone got a workaround or fix?

**Comment by jay0lee** [comment]
Gmail has considers / to be the divider for label hierarchies. GYB assumes that labels with a / in their name should also have their parent label created and does this by default. I recognize this is inconvenient to users who have labels like this with a / in their name but the alternative of not creating these parent labels is equally as inconvenient and is also more prevalent.

Closing issue as won't fix.
