### ISSUE TITLE
Is there an easy way to check the output and see if any emails were found?

### ISSUE THREAD

**Issue by brandonusher** [jay0lee/got-your-back#88]
I work for a K-12 School District and we are getting requests for a list of emails containing certain words etc.

I have a script that loops through and searched every users inbox, no problem. Is there a way to get the output of the command and see if there were any emails found?

I'm using PowerShell and here is what my full command would look like:
```powershell
.\gyb.exe --service-account --search "these are my search parameters" --email "student@domain.k12.ca.us" --action backup --local-folder "C:\EmailSearches\student@domain.k12.ca.us"
```

**Comment by jay0lee** [comment]
The issue tracker is for bug reports. Please post how to questions to the discussion group:

https://groups.google.com/group/got-your-back
