### ISSUE TITLE
v0.44 OpenSSL error line 64 

### ISSUE THREAD

**Issue by rappnews** [jay0lee/got-your-back#89]
In Terminal on Mac OS, execution kept choking with this error:

Traceback (most recent call last):
  File "gyb.py", line 64, in <module>
    from OpenSSL import crypto
ImportError: No module named 'OpenSSL'

After deleting those lines in gyb.py (comment seemed to indicate they were for the Win version), everything worked fine. In fact gyb is working great, thank you.

**Comment by serpro** [comment]
Same happens in Ubuntu

**Comment by fexblanco** [comment]
Same in MacOSX

**Comment by dcroal** [comment]
In Ubuntu you can use python3 and install pyopenssl
sudo apt-get install python3-openssl
This solves the problem for me

**Comment by jay0lee** [comment]
This should be fixed in 0.45:

https://github.com/jay0lee/got-your-back/releases
