### ISSUE TITLE
Temp error backendError - while restoring

### ISSUE THREAD

**Issue by NightLockK** [jay0lee/got-your-back#90]
![backend](https://cloud.githubusercontent.com/assets/17395496/13207138/d1c94c3c-d902-11e5-9284-1ee0c9a1f16a.PNG)

Backend Error stops restore after 10 attempts?
How can this be fixed?

**Comment by garec** [comment]
I have same issue/question.
I am getting this error a lot on a huge account 8+GB 50,000+ email account using .44.

As workaround, what I do for now is watch script every hour or so and restart as needed. It shows remaining messages to restore, picks up after a try or two and continues..

**Comment by locura79** [comment]
I have this problem too, but it's happening so often that I have to check my restore every 5-10 minutes. My current message count is 18,278, and there are a lot of audio and photo attachments.

**Comment by davesmylie** [comment]
I'm getting the same error on 0.45. Seems to be mostly on large (10k+) inboxes.

**Comment by davesmylie** [comment]
This seems to be constant error now (for me) - starts immediately on doing the restore.
Is there a way to see what the actual error is?  Suspecting maybe google blocking the IP for sending too much traffic maybe?

**Comment by roflmao** [comment]
Breaks for me as well. 

```
# python3 gyb.py --email X --action restore --strip-labels --local-folder GYB-GMail-Backup-X --label-restored "X" --fast-restore --batch-size 100

Using backup folder GYB-GMail-Backup-X
restoring 100 messages (100/180906)                                             
Temp error backendError. Backing off 16 seconds...attempt 5/10

Temp error backendError. Backing off 32 seconds...attempt 6/10

Temp error backendError. Backing off 60 seconds...attempt 7/10

Temp error backendError. Backing off 60 seconds...attempt 8/10

Temp error backendError. Backing off 60 seconds...attempt 9/10

Temp error backendError. Backing off 60 seconds...attempt 10/10

500: Backend Error - backendError
```

**Comment by davesmylie** [comment]
I'm starting to think that the error is as given above and is on googles end. I kept at it for a few days  and eventually was able to get most emails restored.

Perhaps the delay should increase more than 60 second so as not to give the impression that's it's only going to be  a short outage. (Or supply the actual error from google)

**Comment by jay0lee** [comment]
This should be fixed by:

https://github.com/jay0lee/got-your-back/commit/fcdcf457bc75eab7eee76950a2b4cba91533ffa9

GYB will still retry these operations but should continue the restore if they ultimately fail.

**Comment by mullcom** [comment]
Hello. Today i am trying to import to other e-mail after a while i get this.

> 500: Backend Error - backendError
>  - Giving up.
> restoring 5 messages (3664/36968)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> Temp error backendError. Backing off 32 seconds...attempt 6/10
> Temp error backendError. Backing off 60 seconds...attempt 7/10
> Temp error backendError. Backing off 60 seconds...attempt 8/10
> Temp error backendError. Backing off 60 seconds...attempt 9/10
> restoring 5 messages (3960/36968)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> restoring 5 messages (7270/36968)
> Temp error backendError. Backing off 16 seconds...attempt 5/10
> Temp error backendError. Backing off 32 seconds...attempt 6/10
> Temp error backendError. Backing off 60 seconds...attempt 7/10
> Temp error backendError. Backing off 60 seconds...attempt 8/10
> Temp error backendError. Backing off 60 seconds...attempt 9/10

I using latest version.

**Comment by rpearce** [comment]
It's working ... eventually. I'm at ~32 hours of the program running.

```sh
Temp error backendError. Backing off 16 seconds...attempt 5/10
Temp error backendError. Backing off 32 seconds...attempt 6/10
Temp error backendError. Backing off 60 seconds...attempt 7/10
Temp error backendError. Backing off 60 seconds...attempt 8/10
Temp error backendError. Backing off 60 seconds...attempt 9/10
Temp error backendError. Backing off 60 seconds...attempt 10/10
500: Temporary System Problem. Try again later. - backendError
 - Giving up.
 restoring 15 messages (38038) - 57.43%
Temp error backendError. Backing off 16 seconds...attempt 5/10
Temp error backendError. Backing off 32 seconds...attempt 6/10
Temp error backendError. Backing off 60 seconds...attempt 7/10
Temp error backendError. Backing off 60 seconds...attempt 8/10
Temp error backendError. Backing off 60 seconds...attempt 9/10
Temp error backendError. Backing off 60 seconds...attempt 10/10
500: Temporary System Problem. Try again later. - backendError
 - Giving up.
 restoring 15 messages (38296) - 57.61%
```

**Comment by Celestica-Edward** [comment]
For the emails that cannot be restored when it reaches "Giving up", can we get more feedback on the email metadata, such as subject & message-id? This way, we can review that email in another client like Thunderbird and try to figure out why it can't be restored or review it manually.

**Comment by aviech** [comment]
heya, getting the same error here, i'm migrating around 400k Mails via the google migration service, but also trying to migrate a few into google groups via the GYB restore group command, but after 1 or 2 Mails, i'm getting a 503 error. Anyone found a workaround for this? Thanks, patrick

**Comment by jarekwg** [comment]
I'm getting the same when restoring to a group. Happens consistently every time it hits message 2..
In the couple of rare cases I had a "message 3", that failed too
```
Restoring from 132.3kb file <redacted>.eml...
 message 2 - 100.00%
Temp error 503. Backing off 16 seconds...attempt 5/10

Temp error 503. Backing off 32 seconds...attempt 6/10

Temp error 503. Backing off 60 seconds...attempt 7/10

Temp error 503. Backing off 60 seconds...attempt 8/10

Temp error 503. Backing off 60 seconds...attempt 9/10

Temp error 503. Backing off 60 seconds...attempt 10/10

503: b'' - 503
 - Giving up.
 message 3 - 100.00%
Temp error 503. Backing off 16 seconds...attempt 5/10

Temp error 503. Backing off 32 seconds...attempt 6/10

Temp error 503. Backing off 60 seconds...attempt 7/10

Temp error 503. Backing off 60 seconds...attempt 8/10

Temp error 503. Backing off 60 seconds...attempt 9/10

Temp error 503. Backing off 60 seconds...attempt 10/10

503: b'' - 503
 - Giving up.

Restoring from 10.94kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 44.02kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 172.81kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 81.47kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 13.98kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 107.79kb file <redacted>.eml...
 message 2 - 100.00%
Temp error 503. Backing off 16 seconds...attempt 5/10

Temp error 503. Backing off 32 seconds...attempt 6/10

Temp error 503. Backing off 60 seconds...attempt 7/10

Temp error 503. Backing off 60 seconds...attempt 8/10

Temp error 503. Backing off 60 seconds...attempt 9/10

Temp error 503. Backing off 60 seconds...attempt 10/10

503: b'' - 503
 - Giving up.

Restoring from 36.02kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 5.32kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 145.6kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 25.24kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 5.3kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 102.8kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 774.62kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 100.53kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 837.62kb file <redacted>.eml...
 message 1 - 100.00%
Restoring from 30.37kb file <redacted>.eml...
 message 2 - 100.00%
Temp error 503. Backing off 16 seconds...attempt 5/10

Temp error 503. Backing off 32 seconds...attempt 6/10

Temp error 503. Backing off 60 seconds...attempt 7/10

Temp error 503. Backing off 60 seconds...attempt 8/10

Temp error 503. Backing off 60 seconds...attempt 9/10

Temp error 503. Backing off 60 seconds...attempt 10/10

503: b'' - 503
 - Giving up.

Restoring from 310.15kb file <redacted>.eml...
 message 1 - 100.00%
 ```

Something that fails this consistently smells like it might be a bug, rather than a true 503..

However, aside from identifying the issue and finding a fix, I wonder whether it would make sense to offer an option to control the number of retries. Currently it's hardcoded to 10. I have a couple hundred thousand emails to load into a group; not _huuugely_ fussed if a small subset fail, so setting nretries to 3 would be fine for me and save a lot of time.

btw, thanks for your hard work on this tool @jay0lee! It's immensely appreciated, especially the care gone into trust, both on security and robustness fronts.
