### ISSUE TITLE
Errors running got-your-back

### ISSUE THREAD

**Issue by eiger3970** [jay0lee/got-your-back#94]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. Run command on Linux $ python3 gyb.py --emailaddress@gmail.com --action estimate > select Allow on opened browser > error appears:
Terminal error: 403: Insufficient Permission - insufficientPermissions.
2. Run command on Mac $ python3 gyb.py --emailaddress@gmail.com --action estimate > error: Traceback (most recent call last):
  File "gyb.py", line 49, in <module>
    import sqlite3
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module name '_sqlite3'.

Expected outcome (what are you trying to do?):
Back up gmail emails and labels, so I can transfer emails and labels to a new gmail account.

Actual outcome (what errors or bad behavior do you see instead?): Errors as above.

**Comment by eiger3970** [comment]
This is fixed and now works.

**Comment by jay0lee** [comment]
Thanks for the update.
