### ISSUE TITLE
Using CSV to backup entire domain

### ISSUE THREAD

**Issue by bripsch** [jay0lee/got-your-back#96]
So, I'm trying to backup emails from my entire domain (~700 users) -- I can create a CSV from the google admin panel, but I don't know how to draw from the CSV in order to backup all of the emails.  With GAM, there is a csv command, which works beautifully, but that doesn't exist for GYB.  Here is what I have tried:

for email in company.csv do gyb --email %email --service-account --batch-size 20

But it just hangs, with no error outputted (this was with a trial CSV with only 2 emails).

Am I getting the formatting wrong?  I have tried a few different ways but to no avail.  Any help is appreciated!

**Comment by jay0lee** [comment]
This isn't really a GYB issue (bug). Please open a thread on the discussion group.

Jay

**Comment by jaikumarm** [comment]
I recently had to help a buddy with this, and wrote this quick script.. adding it here in case someone runs into this in the future.
```
#!/bin/bash
# Purpose: Read Users Report CSV File from G-Suite and perform backup to local mailbox 
# based on predefined search query
# ------------------------------------------
GYB_BIN=/home/backupusr/bin/gyb/gyb
BACKUP_FOLDER=/mnt/backup/gsuite
LOGFILE_NAME=$BACKUP_FOLDER/gyb_logs/$(basename $0)-`date +"%Y-%m-%d-%H-%M"`.gyb.log
USERS_CSV_FILE="/mnt/backup/gsuite/all_users.csv"
SEARCH_REGEX="older_than:3y"
[ ! -f $GYB_BIN ] && { echo "$GYB_BIN file not found"; exit 99; }
[ ! -d $BACKUP_FOLDER ] && { echo "$BACKUP_FOLDER folder not found"; exit 99; }
[ ! -f $USERS_CSV_FILE ] && { echo "$USERS_CSV_FILE file not found"; exit 99; }
cd $BACKUP_FOLDER
while IFS="," read -r User skip
do
    echo "Backing up $SEARCH_REGEX of mails from mbox of : $User"
    $GYB_BIN --email $User --action backup --search $SEARCH_REGEX --batch-size 10 --service-account | tee -a $LOGFILE_NAME
    fi
done < $USERS_CSV_FILE
```
