### ISSUE TITLE
Missing message data in .eml files

### ISSUE THREAD

**Issue by MarcusPope** [jay0lee/got-your-back#99]
I just downloaded the latest windows release (https://github.com/jay0lee/got-your-back/releases/tag/v0.45), and I'm running on windows 7, py2.7.5 x32 (if that even matters, seems like the exe was fully contained.)

First I ran the get estimate flag and when it prompted for access levels I selected Read only / backup only access.  It popped up the browser and I authorized the client. It gave me an estimate of 28mb, which should have been near 600mb (and my spam/trash folders are empty.)

Next I used this cli option:

gyb --email xxx@gmail.com --local-folder "C:\email"

The output showed processing 750 messages, and those emails were stubbed out in the expected output path.

However, most of the emails are 1 line only showing who the email was from "From: addy@domain.com"

I'm not sure how to get to the permissions prompt again, so I didn't try a different setting.  

There are a couple emails that saved as json-ish objects, and (coincidentally?) 100 items that downloaded correctly, so I thought maybe it's an issue with the subsequent blocks of batch downloads. So I wiped out my downloads, and tried again with a batch-size 50 to see if the number of downloaded messages was only 50 but the results were the same.

I reviewed the timestamps of failed and successful downloads and it seems that most of the good ones are from 2013 and before.  But many of the bad ones are from the same timeframe.

I haven't touched python in years, but I'm an experienced software developer and I can work with Linux too if you'd like some debugging help.  I was thinking about trying the previous version, but figured I'd wait for some guidance from you first.

Thanks!
-Marcus

**Comment by MarcusPope** [comment]
Update:

I tried the previous version of gyb and got the same results.  I was also able to try doing a read/write accessible configuration and that didn't help.  However, I tried it with a different gmail account and was able to backup the full account (about 300mb) of well formed emails.  

As far as I can tell there is no difference between the accounts, they are both just standard personal gmail accounts.  I created the account that works back in 2004, and the "broken" account in 2008.

In the next couple of days I'm going to try a pop3-pull on the broken account into the working account, and see if the messages then download successfully from the working account.

-Marcus

**Comment by jay0lee** [comment]
These broken messages are chats (Google Talk or Hangouts). There's an issue with Gmail API which causes only the From: header to be returned, not the chat body itself. The API doesn't really support restore of chat messages anyway (nor is chat backup the goal of GYB).

You can either ignore these messages or skip their backup with:

--search "-is:chat"

to only backup non-chat messages.

Jay
